<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PgQuery\Protobuf\AST;

use Flow\PgQuery\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.AlterOpFamilyStmt</code>.
 */
class AlterOpFamilyStmt extends Message
{
    /**
     * Generated from protobuf field <code>string amname = 2 [json_name = "amname"];</code>.
     */
    protected $amname = '';

    /**
     * Generated from protobuf field <code>bool is_drop = 3 [json_name = "isDrop"];</code>.
     */
    protected $is_drop = false;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node items = 4 [json_name = "items"];</code>.
     */
    private $items;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node opfamilyname = 1 [json_name = "opfamilyname"];</code>.
     */
    private $opfamilyname;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var array<Node> $opfamilyname
     * @var string $amname
     * @var bool $is_drop
     * @var array<Node> $items
     *                  }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string amname = 2 [json_name = "amname"];</code>.
     *
     * @return string
     */
    public function getAmname()
    {
        return $this->amname;
    }

    /**
     * Generated from protobuf field <code>bool is_drop = 3 [json_name = "isDrop"];</code>.
     *
     * @return bool
     */
    public function getIsDrop()
    {
        return $this->is_drop;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node items = 4 [json_name = "items"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node opfamilyname = 1 [json_name = "opfamilyname"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getOpfamilyname()
    {
        return $this->opfamilyname;
    }

    /**
     * Generated from protobuf field <code>string amname = 2 [json_name = "amname"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setAmname($var)
    {
        GPBUtil::checkString($var, true);
        $this->amname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_drop = 3 [json_name = "isDrop"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setIsDrop($var)
    {
        GPBUtil::checkBool($var);
        $this->is_drop = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node items = 4 [json_name = "items"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node opfamilyname = 1 [json_name = "opfamilyname"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setOpfamilyname($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->opfamilyname = $arr;

        return $this;
    }
}
