<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PgQuery\Protobuf\AST;

use Flow\PgQuery\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.AlterEnumStmt</code>.
 */
class AlterEnumStmt extends Message
{
    /**
     * Generated from protobuf field <code>string new_val = 3 [json_name = "newVal"];</code>.
     */
    protected $new_val = '';

    /**
     * Generated from protobuf field <code>bool new_val_is_after = 5 [json_name = "newValIsAfter"];</code>.
     */
    protected $new_val_is_after = false;

    /**
     * Generated from protobuf field <code>string new_val_neighbor = 4 [json_name = "newValNeighbor"];</code>.
     */
    protected $new_val_neighbor = '';

    /**
     * Generated from protobuf field <code>string old_val = 2 [json_name = "oldVal"];</code>.
     */
    protected $old_val = '';

    /**
     * Generated from protobuf field <code>bool skip_if_new_val_exists = 6 [json_name = "skipIfNewValExists"];</code>.
     */
    protected $skip_if_new_val_exists = false;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node type_name = 1 [json_name = "typeName"];</code>.
     */
    private $type_name;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var array<Node> $type_name
     * @var string $old_val
     * @var string $new_val
     * @var string $new_val_neighbor
     * @var bool $new_val_is_after
     * @var bool $skip_if_new_val_exists
     *           }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string new_val = 3 [json_name = "newVal"];</code>.
     *
     * @return string
     */
    public function getNewVal()
    {
        return $this->new_val;
    }

    /**
     * Generated from protobuf field <code>bool new_val_is_after = 5 [json_name = "newValIsAfter"];</code>.
     *
     * @return bool
     */
    public function getNewValIsAfter()
    {
        return $this->new_val_is_after;
    }

    /**
     * Generated from protobuf field <code>string new_val_neighbor = 4 [json_name = "newValNeighbor"];</code>.
     *
     * @return string
     */
    public function getNewValNeighbor()
    {
        return $this->new_val_neighbor;
    }

    /**
     * Generated from protobuf field <code>string old_val = 2 [json_name = "oldVal"];</code>.
     *
     * @return string
     */
    public function getOldVal()
    {
        return $this->old_val;
    }

    /**
     * Generated from protobuf field <code>bool skip_if_new_val_exists = 6 [json_name = "skipIfNewValExists"];</code>.
     *
     * @return bool
     */
    public function getSkipIfNewValExists()
    {
        return $this->skip_if_new_val_exists;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node type_name = 1 [json_name = "typeName"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getTypeName()
    {
        return $this->type_name;
    }

    /**
     * Generated from protobuf field <code>string new_val = 3 [json_name = "newVal"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setNewVal($var)
    {
        GPBUtil::checkString($var, true);
        $this->new_val = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool new_val_is_after = 5 [json_name = "newValIsAfter"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setNewValIsAfter($var)
    {
        GPBUtil::checkBool($var);
        $this->new_val_is_after = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string new_val_neighbor = 4 [json_name = "newValNeighbor"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setNewValNeighbor($var)
    {
        GPBUtil::checkString($var, true);
        $this->new_val_neighbor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string old_val = 2 [json_name = "oldVal"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setOldVal($var)
    {
        GPBUtil::checkString($var, true);
        $this->old_val = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool skip_if_new_val_exists = 6 [json_name = "skipIfNewValExists"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setSkipIfNewValExists($var)
    {
        GPBUtil::checkBool($var);
        $this->skip_if_new_val_exists = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node type_name = 1 [json_name = "typeName"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setTypeName($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->type_name = $arr;

        return $this;
    }
}
