<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PgQuery\Protobuf\AST;

/**
 * Protobuf type <code>pg_query.BoolExprType</code>.
 */
class BoolExprType
{
    /**
     * Generated from protobuf enum <code>AND_EXPR = 1;</code>.
     */
    public const AND_EXPR = 1;

    /**
     * Generated from protobuf enum <code>BOOL_EXPR_TYPE_UNDEFINED = 0;</code>.
     */
    public const BOOL_EXPR_TYPE_UNDEFINED = 0;

    /**
     * Generated from protobuf enum <code>NOT_EXPR = 3;</code>.
     */
    public const NOT_EXPR = 3;

    /**
     * Generated from protobuf enum <code>OR_EXPR = 2;</code>.
     */
    public const OR_EXPR = 2;

    private static $valueToName = [
        self::BOOL_EXPR_TYPE_UNDEFINED => 'BOOL_EXPR_TYPE_UNDEFINED',
        self::AND_EXPR => 'AND_EXPR',
        self::OR_EXPR => 'OR_EXPR',
        self::NOT_EXPR => 'NOT_EXPR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value
            ));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string) $name);

        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name
            ));
        }

        return constant($const);
    }
}
