<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PgQuery\Protobuf\AST;

use Flow\PgQuery\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.ClusterStmt</code>.
 */
class ClusterStmt extends Message
{
    /**
     * Generated from protobuf field <code>string indexname = 2 [json_name = "indexname"];</code>.
     */
    protected $indexname = '';

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 1 [json_name = "relation"];</code>.
     */
    protected $relation;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node params = 3 [json_name = "params"];</code>.
     */
    private $params;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var RangeVar $relation
     * @var string $indexname
     * @var array<Node> $params
     *                  }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearRelation() : void
    {
        $this->relation = null;
    }

    /**
     * Generated from protobuf field <code>string indexname = 2 [json_name = "indexname"];</code>.
     *
     * @return string
     */
    public function getIndexname()
    {
        return $this->indexname;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node params = 3 [json_name = "params"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 1 [json_name = "relation"];</code>.
     *
     * @return null|RangeVar
     */
    public function getRelation()
    {
        return $this->relation;
    }

    public function hasRelation()
    {
        return isset($this->relation);
    }

    /**
     * Generated from protobuf field <code>string indexname = 2 [json_name = "indexname"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setIndexname($var)
    {
        GPBUtil::checkString($var, true);
        $this->indexname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node params = 3 [json_name = "params"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 1 [json_name = "relation"];</code>.
     *
     * @param RangeVar $var
     *
     * @return $this
     */
    public function setRelation($var)
    {
        GPBUtil::checkMessage($var, RangeVar::class);
        $this->relation = $var;

        return $this;
    }
}
