<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PgQuery\Protobuf\AST;

use Flow\PgQuery\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CreateRangeStmt</code>.
 */
class CreateRangeStmt extends Message
{
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node params = 2 [json_name = "params"];</code>.
     */
    private $params;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node type_name = 1 [json_name = "typeName"];</code>.
     */
    private $type_name;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var array<Node> $type_name
     * @var array<Node> $params
     *                  }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node params = 2 [json_name = "params"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node type_name = 1 [json_name = "typeName"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getTypeName()
    {
        return $this->type_name;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node params = 2 [json_name = "params"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setParams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->params = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node type_name = 1 [json_name = "typeName"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setTypeName($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->type_name = $arr;

        return $this;
    }
}
