<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PgQuery\Protobuf\AST;

use Flow\PgQuery\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CreateRoleStmt</code>.
 */
class CreateRoleStmt extends Message
{
    /**
     * Generated from protobuf field <code>string role = 2 [json_name = "role"];</code>.
     */
    protected $role = '';

    /**
     * Generated from protobuf field <code>.pg_query.RoleStmtType stmt_type = 1 [json_name = "stmt_type"];</code>.
     */
    protected $stmt_type = 0;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 3 [json_name = "options"];</code>.
     */
    private $options;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $stmt_type
     * @var string $role
     * @var array<Node> $options
     *                  }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 3 [json_name = "options"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>string role = 2 [json_name = "role"];</code>.
     *
     * @return string
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RoleStmtType stmt_type = 1 [json_name = "stmt_type"];</code>.
     *
     * @return int
     */
    public function getStmtType()
    {
        return $this->stmt_type;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 3 [json_name = "options"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->options = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string role = 2 [json_name = "role"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkString($var, true);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RoleStmtType stmt_type = 1 [json_name = "stmt_type"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setStmtType($var)
    {
        GPBUtil::checkEnum($var, RoleStmtType::class);
        $this->stmt_type = $var;

        return $this;
    }
}
