<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PgQuery\Protobuf\AST;

/**
 * Protobuf type <code>pg_query.DefElemAction</code>.
 */
class DefElemAction
{
    /**
     * Generated from protobuf enum <code>DEF_ELEM_ACTION_UNDEFINED = 0;</code>.
     */
    public const DEF_ELEM_ACTION_UNDEFINED = 0;

    /**
     * Generated from protobuf enum <code>DEFELEM_ADD = 3;</code>.
     */
    public const DEFELEM_ADD = 3;

    /**
     * Generated from protobuf enum <code>DEFELEM_DROP = 4;</code>.
     */
    public const DEFELEM_DROP = 4;

    /**
     * Generated from protobuf enum <code>DEFELEM_SET = 2;</code>.
     */
    public const DEFELEM_SET = 2;

    /**
     * Generated from protobuf enum <code>DEFELEM_UNSPEC = 1;</code>.
     */
    public const DEFELEM_UNSPEC = 1;

    private static $valueToName = [
        self::DEF_ELEM_ACTION_UNDEFINED => 'DEF_ELEM_ACTION_UNDEFINED',
        self::DEFELEM_UNSPEC => 'DEFELEM_UNSPEC',
        self::DEFELEM_SET => 'DEFELEM_SET',
        self::DEFELEM_ADD => 'DEFELEM_ADD',
        self::DEFELEM_DROP => 'DEFELEM_DROP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value
            ));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string) $name);

        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name
            ));
        }

        return constant($const);
    }
}
