<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PgQuery\Protobuf\AST;

/**
 * Protobuf type <code>pg_query.DiscardMode</code>.
 */
class DiscardMode
{
    /**
     * Generated from protobuf enum <code>DISCARD_ALL = 1;</code>.
     */
    public const DISCARD_ALL = 1;

    /**
     * Generated from protobuf enum <code>DISCARD_MODE_UNDEFINED = 0;</code>.
     */
    public const DISCARD_MODE_UNDEFINED = 0;

    /**
     * Generated from protobuf enum <code>DISCARD_PLANS = 2;</code>.
     */
    public const DISCARD_PLANS = 2;

    /**
     * Generated from protobuf enum <code>DISCARD_SEQUENCES = 3;</code>.
     */
    public const DISCARD_SEQUENCES = 3;

    /**
     * Generated from protobuf enum <code>DISCARD_TEMP = 4;</code>.
     */
    public const DISCARD_TEMP = 4;

    private static $valueToName = [
        self::DISCARD_MODE_UNDEFINED => 'DISCARD_MODE_UNDEFINED',
        self::DISCARD_ALL => 'DISCARD_ALL',
        self::DISCARD_PLANS => 'DISCARD_PLANS',
        self::DISCARD_SEQUENCES => 'DISCARD_SEQUENCES',
        self::DISCARD_TEMP => 'DISCARD_TEMP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value
            ));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string) $name);

        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name
            ));
        }

        return constant($const);
    }
}
