<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PgQuery\Protobuf\AST;

use Flow\PgQuery\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBUtil, Message};

/**
 * Generated from protobuf message <code>pg_query.InferenceElem</code>.
 */
class InferenceElem extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Node expr = 2 [json_name = "expr"];</code>.
     */
    protected $expr;

    /**
     * Generated from protobuf field <code>uint32 infercollid = 3 [json_name = "infercollid"];</code>.
     */
    protected $infercollid = 0;

    /**
     * Generated from protobuf field <code>uint32 inferopclass = 4 [json_name = "inferopclass"];</code>.
     */
    protected $inferopclass = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     */
    protected $xpr;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var Node $xpr
     * @var Node $expr
     * @var int $infercollid
     * @var int $inferopclass
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearExpr() : void
    {
        $this->expr = null;
    }

    public function clearXpr() : void
    {
        $this->xpr = null;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node expr = 2 [json_name = "expr"];</code>.
     *
     * @return null|Node
     */
    public function getExpr()
    {
        return $this->expr;
    }

    /**
     * Generated from protobuf field <code>uint32 infercollid = 3 [json_name = "infercollid"];</code>.
     *
     * @return int
     */
    public function getInfercollid()
    {
        return $this->infercollid;
    }

    /**
     * Generated from protobuf field <code>uint32 inferopclass = 4 [json_name = "inferopclass"];</code>.
     *
     * @return int
     */
    public function getInferopclass()
    {
        return $this->inferopclass;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @return null|Node
     */
    public function getXpr()
    {
        return $this->xpr;
    }

    public function hasExpr()
    {
        return isset($this->expr);
    }

    public function hasXpr()
    {
        return isset($this->xpr);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node expr = 2 [json_name = "expr"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setExpr($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->expr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 infercollid = 3 [json_name = "infercollid"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setInfercollid($var)
    {
        GPBUtil::checkUint32($var);
        $this->infercollid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 inferopclass = 4 [json_name = "inferopclass"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setInferopclass($var)
    {
        GPBUtil::checkUint32($var);
        $this->inferopclass = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setXpr($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->xpr = $var;

        return $this;
    }
}
