<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PgQuery\Protobuf\AST;

/**
 * Protobuf type <code>pg_query.KeywordKind</code>.
 */
class KeywordKind
{
    /**
     * Generated from protobuf enum <code>COL_NAME_KEYWORD = 2;</code>.
     */
    public const COL_NAME_KEYWORD = 2;

    /**
     * Generated from protobuf enum <code>NO_KEYWORD = 0;</code>.
     */
    public const NO_KEYWORD = 0;

    /**
     * Generated from protobuf enum <code>RESERVED_KEYWORD = 4;</code>.
     */
    public const RESERVED_KEYWORD = 4;

    /**
     * Generated from protobuf enum <code>TYPE_FUNC_NAME_KEYWORD = 3;</code>.
     */
    public const TYPE_FUNC_NAME_KEYWORD = 3;

    /**
     * Generated from protobuf enum <code>UNRESERVED_KEYWORD = 1;</code>.
     */
    public const UNRESERVED_KEYWORD = 1;

    private static $valueToName = [
        self::NO_KEYWORD => 'NO_KEYWORD',
        self::UNRESERVED_KEYWORD => 'UNRESERVED_KEYWORD',
        self::COL_NAME_KEYWORD => 'COL_NAME_KEYWORD',
        self::TYPE_FUNC_NAME_KEYWORD => 'TYPE_FUNC_NAME_KEYWORD',
        self::RESERVED_KEYWORD => 'RESERVED_KEYWORD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value
            ));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string) $name);

        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name
            ));
        }

        return constant($const);
    }
}
