<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PgQuery\Protobuf\AST;

use Flow\PgQuery\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBUtil, Message};

/**
 * Generated from protobuf message <code>pg_query.ParamRef</code>.
 */
class ParamRef extends Message
{
    /**
     * Generated from protobuf field <code>int32 location = 2 [json_name = "location"];</code>.
     */
    protected $location = 0;

    /**
     * Generated from protobuf field <code>int32 number = 1 [json_name = "number"];</code>.
     */
    protected $number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $number
     * @var int $location
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 location = 2 [json_name = "location"];</code>.
     *
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>int32 number = 1 [json_name = "number"];</code>.
     *
     * @return int
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Generated from protobuf field <code>int32 location = 2 [json_name = "location"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 number = 1 [json_name = "number"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->number = $var;

        return $this;
    }
}
