<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PgQuery\Protobuf\AST;

/**
 * Protobuf type <code>pg_query.RowCompareType</code>.
 */
class RowCompareType
{
    /**
     * Generated from protobuf enum <code>ROW_COMPARE_TYPE_UNDEFINED = 0;</code>.
     */
    public const ROW_COMPARE_TYPE_UNDEFINED = 0;

    /**
     * Generated from protobuf enum <code>ROWCOMPARE_EQ = 3;</code>.
     */
    public const ROWCOMPARE_EQ = 3;

    /**
     * Generated from protobuf enum <code>ROWCOMPARE_GE = 4;</code>.
     */
    public const ROWCOMPARE_GE = 4;

    /**
     * Generated from protobuf enum <code>ROWCOMPARE_GT = 5;</code>.
     */
    public const ROWCOMPARE_GT = 5;

    /**
     * Generated from protobuf enum <code>ROWCOMPARE_LE = 2;</code>.
     */
    public const ROWCOMPARE_LE = 2;

    /**
     * Generated from protobuf enum <code>ROWCOMPARE_LT = 1;</code>.
     */
    public const ROWCOMPARE_LT = 1;

    /**
     * Generated from protobuf enum <code>ROWCOMPARE_NE = 6;</code>.
     */
    public const ROWCOMPARE_NE = 6;

    private static $valueToName = [
        self::ROW_COMPARE_TYPE_UNDEFINED => 'ROW_COMPARE_TYPE_UNDEFINED',
        self::ROWCOMPARE_LT => 'ROWCOMPARE_LT',
        self::ROWCOMPARE_LE => 'ROWCOMPARE_LE',
        self::ROWCOMPARE_EQ => 'ROWCOMPARE_EQ',
        self::ROWCOMPARE_GE => 'ROWCOMPARE_GE',
        self::ROWCOMPARE_GT => 'ROWCOMPARE_GT',
        self::ROWCOMPARE_NE => 'ROWCOMPARE_NE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value
            ));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string) $name);

        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name
            ));
        }

        return constant($const);
    }
}
