name = "snippet-upload"
main = "snippet-upload.js"
compatibility_date = "2024-01-01"

# R2 Bucket binding
[[r2_buckets]]
binding = "SNIPPETS_BUCKET"
bucket_name = "flow-php-playground-snippets"
preview_bucket_name = "flow-php-playground-snippets"

