codecov:
  notify:
    after_n_builds: 1

comment:
  layout: "condensed_header, diff, components"
  after_n_builds: 1

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: tests
      carryforward: true
    - name: extension-tests
      carryforward: true
    - name: arrow-extension
      carryforward: true
    - name: flow-php-extension
      carryforward: true
    - name: telemetry-tests
      carryforward: true

component_management:
  individual_components:
    - component_id: etl
      name: etl
      paths:
        - src/core/**
    - component_id: cli
      name: cli
      paths:
        - src/cli/**
    - component_id: lib-array-dot
      name: lib-array-dot
      paths:
        - src/lib/array-dot/**
    - component_id: lib-azure-sdk
      name: lib-azure-sdk
      paths:
        - src/lib/azure-sdk/**
    - component_id: lib-doctrine-dbal-bulk
      name: lib-doctrine-dbal-bulk
      paths:
        - src/lib/doctrine-dbal-bulk/**
    - component_id: lib-filesystem
      name: lib-filesystem
      paths:
        - src/lib/filesystem/**
    - component_id: lib-types
      name: lib-types
      paths:
        - src/lib/types/**
    - component_id: lib-parquet
      name: lib-parquet
      paths:
        - src/lib/parquet/**
    - component_id: lib-parquet-viewer
      name: lib-parquet-viewer
      paths:
        - src/lib/parquet-viewer/**
    - component_id: lib-snappy
      name: lib-snappy
      paths:
        - src/lib/snappy/**
    - component_id: lib-dremel
      name: lib-dremel
      paths:
        - src/lib/dremel/**
    - component_id: lib-postgresql
      name: lib-postgresql
      paths:
        - src/lib/postgresql/**
    - component_id: lib-telemetry
      name: lib-telemetry
      paths:
        - src/lib/telemetry/**
    - component_id: bridge-filesystem-async-aws
      name: bridge-filesystem-async-aws
      paths:
        - src/bridge/filesystem/async-aws/**
    - component_id: bridge-filesystem-azure
      name: bridge-filesystem-azure
      paths:
        - src/bridge/filesystem/azure/**
    - component_id: bridge-filesystem-sftp
      name: bridge-filesystem-sftp
      paths:
        - src/bridge/filesystem/sftp/**
    - component_id: bridge-monolog-http
      name: bridge-monolog-http
      paths:
        - src/bridge/monolog/http/**
    - component_id: bridge-monolog-telemetry
      name: bridge-monolog-telemetry
      paths:
        - src/bridge/monolog/telemetry/**
    - component_id: bridge-openapi-specification
      name: bridge-openapi-specification
      paths:
        - src/bridge/openapi/specification/**
    - component_id: symfony-http-foundation
      name: symfony-http-foundation
      paths:
        - src/bridge/symfony/http-foundation/**
    - component_id: bridge-psr18-telemetry
      name: bridge-psr18-telemetry
      paths:
        - src/bridge/psr18/telemetry/**
    - component_id: bridge-psr3-telemetry
      name: bridge-psr3-telemetry
      paths:
        - src/bridge/psr3/telemetry/**
    - component_id: bridge-psr7-telemetry
      name: bridge-psr7-telemetry
      paths:
        - src/bridge/psr7/telemetry/**
    - component_id: bridge-telemetry-otlp
      name: bridge-telemetry-otlp
      paths:
        - src/bridge/telemetry/otlp/**
    - component_id: bridge-symfony-http-foundation-telemetry
      name: bridge-symfony-http-foundation-telemetry
      paths:
        - src/bridge/symfony/http-foundation-telemetry/**
    - component_id: bridge-symfony-filesystem-bundle
      name: bridge-symfony-filesystem-bundle
      paths:
        - src/bridge/symfony/filesystem-bundle/**
    - component_id: bridge-symfony-filesystem-cache
      name: bridge-symfony-filesystem-cache
      paths:
        - src/bridge/symfony/filesystem-cache/**
    - component_id: bridge-symfony-postgresql-bundle
      name: bridge-symfony-postgresql-bundle
      paths:
        - src/bridge/symfony/postgresql-bundle/**
    - component_id: bridge-symfony-postgresql-cache
      name: bridge-symfony-postgresql-cache
      paths:
        - src/bridge/symfony/postgresql-cache/**
    - component_id: bridge-symfony-postgresql-messenger
      name: bridge-symfony-postgresql-messenger
      paths:
        - src/bridge/symfony/postgresql-messenger/**
    - component_id: bridge-symfony-postgresql-session
      name: bridge-symfony-postgresql-session
      paths:
        - src/bridge/symfony/postgresql-session/**
    - component_id: bridge-symfony-telemetry-bundle
      name: bridge-symfony-telemetry-bundle
      paths:
        - src/bridge/symfony/telemetry-bundle/**
    - component_id: adapter-chartjs
      name: adapter-chartjs
      paths:
        - src/adapter/etl-adapter-chartjs/**
    - component_id: adapter-csv
      name: adapter-csv
      paths:
        - src/adapter/etl-adapter-csv/**
    - component_id: adapter-doctrine
      name: adapter-doctrine
      paths:
        - src/adapter/etl-adapter-doctrine/**
    - component_id: adapter-google-sheet
      name: adapter-google-sheet
      paths:
        - src/adapter/etl-adapter-google-sheet/**
    - component_id: adapter-http
      name: adapter-http
      paths:
        - src/adapter/etl-adapter-http/**
    - component_id: adapter-json
      name: adapter-json
      paths:
        - src/adapter/etl-adapter-json/**
    - component_id: adapter-logger
      name: adapter-logger
      paths:
        - src/adapter/etl-adapter-logger/**
    - component_id: adapter-parquet
      name: adapter-parquet
      paths:
        - src/adapter/etl-adapter-parquet/**
    - component_id: adapter-text
      name: adapter-text
      paths:
        - src/adapter/etl-adapter-text/**
    - component_id: adapter-xml
      name: adapter-xml
      paths:
        - src/adapter/etl-adapter-xml/**
    - component_id: adapter-avro
      name: adapter-avro
      paths:
        - src/adapter/etl-adapter-avro/**
    - component_id: adapter-excel
      name: adapter-excel
      paths:
        - src/adapter/etl-adapter-excel/**
    - component_id: adapter-postgresql
      name: adapter-postgresql
      paths:
        - src/adapter/etl-adapter-postgresql/**
    - component_id: adapter-seal
      name: adapter-seal
      paths:
        - src/adapter/etl-adapter-seal/**
    - component_id: bridge-phpunit-postgresql
      name: bridge-phpunit-postgresql
      paths:
        - src/bridge/phpunit/postgresql/**
    - component_id: bridge-phpunit-telemetry
      name: bridge-phpunit-telemetry
      paths:
        - src/bridge/phpunit/telemetry/**
    - component_id: bridge-phpstan-types
      name: bridge-phpstan-types
      paths:
        - src/bridge/phpstan/types/**
    - component_id: bridge-postgresql-valinor
      name: bridge-postgresql-valinor
      paths:
        - src/bridge/postgresql/valinor/**
