<?php

declare(strict_types=1);

namespace Flow\Bridge\Symfony\TelemetryBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\{ArrayNodeDefinition, TreeBuilder};
use Symfony\Component\Config\Definition\ConfigurationInterface;
use Symfony\Component\Config\Definition\Exception\InvalidConfigurationException;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder() : TreeBuilder
    {
        $treeBuilder = new TreeBuilder('flow_telemetry');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->arrayNode('resource')
                    ->info('OpenTelemetry Resource configuration with automatic detection (https://opentelemetry.io/docs/specs/semconv/resource/)')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('detectors')
                            ->info('Resource detector configuration for automatic attribute detection')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->info('Enable resource detectors (default: true)')
                                    ->defaultTrue()
                                ->end()
                                ->arrayNode('static')
                                    ->info('Static detectors - values that do not change between requests/commands (can be cached)')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('cache')
                                            ->info('File-based caching of static resource attributes. The cache file is intentionally outside Symfony\'s cache lifecycle so build-time cache:warmup does not freeze runtime-dependent attributes (host, process).')
                                            ->addDefaultsIfNotSet()
                                            ->children()
                                                ->booleanNode('enabled')
                                                    ->info('Enable caching of static resource attributes')
                                                    ->defaultTrue()
                                                ->end()
                                                ->scalarNode('path')
                                                    ->info('Absolute path to the cache file. Default: sys_get_temp_dir()/flow_telemetry_resource.cache.')
                                                    ->defaultNull()
                                                ->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('os')
                                            ->info('OS detector - detects os.type, os.name, os.version, os.description')
                                            ->addDefaultsIfNotSet()
                                            ->children()
                                                ->booleanNode('enabled')->defaultTrue()->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('host')
                                            ->info('Host detector - detects host.name, host.arch, host.id')
                                            ->addDefaultsIfNotSet()
                                            ->children()
                                                ->booleanNode('enabled')->defaultTrue()->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('service')
                                            ->info('Service detector - detects service.name and service.version from composer.json')
                                            ->addDefaultsIfNotSet()
                                            ->children()
                                                ->booleanNode('enabled')->defaultTrue()->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('deployment')
                                            ->info('Deployment detector - detects deployment.environment.name from Symfony kernel environment')
                                            ->addDefaultsIfNotSet()
                                            ->children()
                                                ->booleanNode('enabled')->defaultTrue()->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('environment')
                                            ->info('Environment detector - reads OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES')
                                            ->addDefaultsIfNotSet()
                                            ->children()
                                                ->booleanNode('enabled')->defaultTrue()->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('dynamic')
                                    ->info('Dynamic detectors - values that may change between requests/commands (never cached)')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('process')
                                            ->info('Process detector - detects process.pid, process.runtime.*, process.executable.*')
                                            ->addDefaultsIfNotSet()
                                            ->children()
                                                ->booleanNode('enabled')->defaultTrue()->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('custom')
                            ->info('Custom resource attributes that override auto-detected values')
                            ->normalizeKeys(false)
                            ->useAttributeAsKey('name')
                            ->prototype('variable')->end()
                        ->end()
                    ->end()
                ->end()
                ->scalarNode('clock_service_id')
                    ->info('Custom PSR-20 clock service ID. If not provided, uses built-in SystemClock.')
                    ->defaultNull()
                ->end()
                ->scalarNode('framework_logger')
                    ->info('Name of the logger (matching a key under "loggers", or "default") whose PSR-3 wrapper will be aliased to Symfony\'s "logger" service. Leave null to auto-replace only when Symfony\'s default HttpKernel Logger is currently bound.')
                    ->defaultNull()
                ->end()
                ->arrayNode('context_storage')
                    ->info('Context storage configuration')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('type')
                            ->values(['memory', 'service'])
                            ->defaultValue('memory')
                        ->end()
                        ->scalarNode('service_id')
                            ->info('Custom context storage service ID (only for type: service)')
                            ->defaultNull()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('propagator')
                    ->info('Context propagator configuration for distributed tracing')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('type')
                            ->info("Propagator type: 'w3c' (W3C TraceContext + Baggage), 'tracecontext' (W3C TraceContext only), 'baggage' (W3C Baggage only), 'service' (custom)")
                            ->values(['w3c', 'tracecontext', 'baggage', 'service'])
                            ->defaultValue('w3c')
                        ->end()
                        ->scalarNode('service_id')
                            ->info('Custom propagator service ID (only for type: service)')
                            ->defaultNull()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('tracer_provider')
                    ->info('TracerProvider configuration. Defaults to void if omitted.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('sampler')
                            ->info('Trace sampler configuration')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->enumNode('type')
                                    ->values(['always_on', 'always_off', 'trace_id_ratio', 'parent_based', 'service'])
                                    ->defaultValue('always_on')
                                ->end()
                                ->floatNode('ratio')
                                    ->info('Sampling ratio for trace_id_ratio type (0.0 to 1.0)')
                                    ->defaultValue(1.0)
                                    ->min(0.0)
                                    ->max(1.0)
                                ->end()
                                ->scalarNode('service_id')
                                    ->info('Custom sampler service ID (only for type: service)')
                                    ->defaultNull()
                                ->end()
                            ->end()
                        ->end()
                        ->append($this->processorNode('span'))
                    ->end()
                ->end()
                ->arrayNode('meter_provider')
                    ->info('MeterProvider configuration. Defaults to void if omitted.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('temporality')
                            ->info('Aggregation temporality')
                            ->values(['cumulative', 'delta'])
                            ->defaultValue('cumulative')
                        ->end()
                        ->append($this->processorNode('metric'))
                    ->end()
                ->end()
                ->arrayNode('logger_provider')
                    ->info('LoggerProvider configuration. Defaults to void if omitted.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->append($this->processorNode('log'))
                    ->end()
                ->end()
                ->arrayNode('instrumentation')
                    ->info('Auto-instrumentation configuration')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('http_kernel')
                            ->info('HTTP kernel request tracing configuration')
                            ->canBeEnabled()
                            ->children()
                                ->arrayNode('exclude_paths')
                                    ->info('URL paths to exclude from tracing (checked before route resolution)')
                                    ->arrayPrototype()
                                        ->children()
                                            ->scalarNode('path')
                                                ->info('Path pattern (exact or regex with / delimiters)')
                                                ->isRequired()
                                                ->cannotBeEmpty()
                                            ->end()
                                            ->scalarNode('method')
                                                ->info('HTTP method (omit for all methods)')
                                                ->defaultNull()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                                ->booleanNode('context_propagation')
                                    ->info('Enable context propagation from incoming HTTP headers (requires propagator)')
                                    ->defaultTrue()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('console')
                            ->info('Console command tracing configuration')
                            ->canBeEnabled()
                            ->children()
                                ->arrayNode('exclude_commands')
                                    ->info('Command names to exclude from tracing (supports regex with / delimiters)')
                                    ->scalarPrototype()->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('messenger')
                            ->info('Messenger tracing configuration')
                            ->canBeEnabled()
                            ->children()
                                ->booleanNode('context_propagation')
                                    ->info('Enable context propagation across message boundaries (requires propagator)')
                                    ->defaultTrue()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('twig')
                            ->info('Twig template tracing configuration')
                            ->canBeEnabled()
                            ->children()
                                ->booleanNode('trace_templates')
                                    ->info('Trace template rendering')
                                    ->defaultTrue()
                                ->end()
                                ->booleanNode('trace_blocks')
                                    ->info('Trace block rendering')
                                    ->defaultFalse()
                                ->end()
                                ->booleanNode('trace_macros')
                                    ->info('Trace macro execution')
                                    ->defaultFalse()
                                ->end()
                                ->arrayNode('exclude_templates')
                                    ->info('Template paths to exclude from tracing (supports regex with / delimiters)')
                                    ->scalarPrototype()->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('http_client')
                            ->info('HTTP client request tracing configuration')
                            ->canBeEnabled()
                            ->children()
                                ->arrayNode('exclude_clients')
                                    ->info('HTTP client service IDs to exclude from tracing (supports regex with / delimiters)')
                                    ->scalarPrototype()->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('psr18_client')
                            ->info('PSR-18 HTTP client request tracing configuration')
                            ->canBeEnabled()
                            ->children()
                                ->arrayNode('exclude_clients')
                                    ->info('PSR-18 client service IDs to exclude from tracing (supports regex with / delimiters)')
                                    ->scalarPrototype()->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('dbal')
                            ->info('Doctrine DBAL query tracing configuration')
                            ->canBeEnabled()
                            ->children()
                                ->booleanNode('log_sql')
                                    ->info('Whether to include SQL in span attributes')
                                    ->defaultTrue()
                                ->end()
                                ->integerNode('max_sql_length')
                                    ->info('Maximum SQL length in span attributes (0 = no limit)')
                                    ->defaultValue(1000)
                                    ->min(0)
                                ->end()
                                ->arrayNode('exclude_connections')
                                    ->info('Connection names to exclude from tracing (supports regex with / delimiters)')
                                    ->scalarPrototype()->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('cache')
                            ->info('Symfony Cache tracing configuration')
                            ->canBeEnabled()
                            ->children()
                                ->arrayNode('exclude_pools')
                                    ->info('Cache pool service IDs to exclude from tracing (supports regex with / delimiters)')
                                    ->scalarPrototype()->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('tracers')
                    ->info('Named tracer configurations')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('version')
                                ->info('Instrumentation scope version')
                                ->defaultValue('unknown')
                            ->end()
                            ->scalarNode('schema_url')
                                ->info('Schema URL for semantic conventions')
                                ->defaultNull()
                            ->end()
                            ->arrayNode('attributes')
                                ->info('Additional scope attributes')
                                ->normalizeKeys(false)
                                ->useAttributeAsKey('name')
                                ->prototype('variable')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('meters')
                    ->info('Named meter configurations')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('version')
                                ->info('Instrumentation scope version')
                                ->defaultValue('unknown')
                            ->end()
                            ->scalarNode('schema_url')
                                ->info('Schema URL for semantic conventions')
                                ->defaultNull()
                            ->end()
                            ->arrayNode('attributes')
                                ->info('Additional scope attributes')
                                ->normalizeKeys(false)
                                ->useAttributeAsKey('name')
                                ->prototype('variable')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('loggers')
                    ->info('Named logger configurations')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('version')
                                ->info('Instrumentation scope version')
                                ->defaultValue('unknown')
                            ->end()
                            ->scalarNode('schema_url')
                                ->info('Schema URL for semantic conventions')
                                ->defaultNull()
                            ->end()
                            ->arrayNode('attributes')
                                ->info('Additional scope attributes')
                                ->normalizeKeys(false)
                                ->useAttributeAsKey('name')
                                ->prototype('variable')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }

    private function exporterNode(string $signalType) : ArrayNodeDefinition
    {
        $builder = new TreeBuilder('exporter');
        /** @var ArrayNodeDefinition $node */
        $node = $builder->getRootNode();

        $node
            ->info(\ucfirst($signalType) . ' exporter configuration')
            ->addDefaultsIfNotSet()
            ->children()
                ->enumNode('type')
                    ->values(['memory', 'console', 'void', 'otlp', 'service'])
                    ->defaultValue('void')
                ->end()
                ->scalarNode('service_id')
                    ->info('Custom exporter service ID (only for type: service)')
                    ->defaultNull()
                ->end()
                ->arrayNode('otlp')
                    ->info('OTLP exporter configuration (only for type: otlp)')
                    ->children()
                        ->arrayNode('transport')
                            ->info('OTLP transport configuration')
                            ->addDefaultsIfNotSet()
                            ->beforeNormalization()
                                ->always(static function (mixed $v) : mixed {
                                    if (\is_array($v) && ($v['type'] ?? null) === 'grpc' && \array_key_exists('timeout', $v)) {
                                        throw new InvalidConfigurationException(
                                            'The "timeout" parameter is not supported when transport.type is "grpc".',
                                        );
                                    }

                                    return $v;
                                })
                            ->end()
                            ->children()
                                ->enumNode('type')
                                    ->values(['curl', 'http', 'grpc', 'service'])
                                    ->defaultValue('curl')
                                ->end()
                                ->scalarNode('endpoint')
                                    ->info('OTLP endpoint URL (required)')
                                    ->isRequired()
                                    ->cannotBeEmpty()
                                ->end()
                                ->integerNode('timeout')
                                    ->info('Request timeout in seconds (not supported for grpc transport)')
                                    ->defaultValue(30)
                                    ->min(1)
                                ->end()
                                ->arrayNode('headers')
                                    ->info('Additional HTTP headers')
                                    ->normalizeKeys(false)
                                    ->useAttributeAsKey('name')
                                    ->prototype('scalar')->end()
                                ->end()
                                ->integerNode('connect_timeout')
                                    ->info('Connection timeout in seconds (only for curl)')
                                    ->defaultValue(10)
                                    ->min(1)
                                ->end()
                                ->booleanNode('compression')
                                    ->info('Enable automatic response decompression (only for curl)')
                                    ->defaultFalse()
                                ->end()
                                ->booleanNode('follow_redirects')
                                    ->info('Follow HTTP redirects (only for curl)')
                                    ->defaultTrue()
                                ->end()
                                ->integerNode('max_redirects')
                                    ->info('Maximum number of redirects to follow (only for curl)')
                                    ->defaultValue(3)
                                    ->min(0)
                                ->end()
                                ->scalarNode('proxy')
                                    ->info('Proxy server URL (only for curl, e.g., "http://proxy:8080")')
                                    ->defaultNull()
                                ->end()
                                ->booleanNode('ssl_verify_peer')
                                    ->info('Verify SSL peer certificate (only for curl)')
                                    ->defaultTrue()
                                ->end()
                                ->booleanNode('ssl_verify_host')
                                    ->info('Verify SSL host name (only for curl)')
                                    ->defaultTrue()
                                ->end()
                                ->scalarNode('ssl_cert_path')
                                    ->info('Path to SSL client certificate (only for curl)')
                                    ->defaultNull()
                                ->end()
                                ->scalarNode('ssl_key_path')
                                    ->info('Path to SSL client private key (only for curl)')
                                    ->defaultNull()
                                ->end()
                                ->scalarNode('ca_info_path')
                                    ->info('Path to CA certificate bundle (only for curl)')
                                    ->defaultNull()
                                ->end()
                                ->scalarNode('http_client_service_id')
                                    ->info('PSR-18 HTTP client service ID (only for http transport)')
                                    ->defaultNull()
                                ->end()
                                ->scalarNode('request_factory_service_id')
                                    ->info('PSR-17 request factory service ID (only for http transport)')
                                    ->defaultNull()
                                ->end()
                                ->scalarNode('stream_factory_service_id')
                                    ->info('PSR-17 stream factory service ID (only for http transport)')
                                    ->defaultNull()
                                ->end()
                                ->booleanNode('insecure')
                                    ->info('Allow insecure connections (only for grpc)')
                                    ->defaultTrue()
                                ->end()
                                ->scalarNode('service_id')
                                    ->info('Custom transport service ID (only for type: service)')
                                    ->defaultNull()
                                ->end()
                                ->arrayNode('serializer')
                                    ->info('Serializer configuration')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->enumNode('type')
                                            ->values(['json', 'protobuf', 'service'])
                                            ->defaultValue('json')
                                        ->end()
                                        ->scalarNode('service_id')
                                            ->info('Custom serializer service ID (only for type: service)')
                                            ->defaultNull()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $node;
    }

    private function innerProcessorNode(string $signalType) : ArrayNodeDefinition
    {
        $builder = new TreeBuilder('inner_processor');
        /** @var ArrayNodeDefinition $node */
        $node = $builder->getRootNode();

        $childProcessorTypes = ['memory', 'batching', 'passthrough', 'void', 'service'];

        $node
            ->info('Inner processor configuration for severity_filtering (only for type: severity_filtering)')
            ->children()
                ->enumNode('type')
                    ->values($childProcessorTypes)
                    ->isRequired()
                ->end()
                ->integerNode('batch_size')
                    ->info('Batch size for batching processor')
                    ->defaultValue(512)
                    ->min(1)
                ->end()
                ->scalarNode('service_id')
                    ->info('Custom processor service ID (only for type: service)')
                    ->defaultNull()
                ->end()
                ->append($this->exporterNode($signalType))
            ->end();

        return $node;
    }

    private function processorNode(string $signalType) : ArrayNodeDefinition
    {
        $builder = new TreeBuilder('processor');
        /** @var ArrayNodeDefinition $node */
        $node = $builder->getRootNode();

        $processorTypes = ['composite', 'memory', 'batching', 'passthrough', 'void', 'service'];
        $childProcessorTypes = ['memory', 'batching', 'passthrough', 'void', 'service'];

        if ($signalType === 'log') {
            $processorTypes[] = 'severity_filtering';
            $childProcessorTypes[] = 'severity_filtering';
        }

        $node
            ->info(\ucfirst($signalType) . ' processor configuration')
            ->addDefaultsIfNotSet()
            ->children()
                ->enumNode('type')
                    ->values($processorTypes)
                    ->defaultValue('void')
                ->end()
                ->integerNode('batch_size')
                    ->info('Batch size for batching processor')
                    ->defaultValue(512)
                    ->min(1)
                ->end()
                ->scalarNode('service_id')
                    ->info('Custom processor service ID (only for type: service)')
                    ->defaultNull()
                ->end()
                ->enumNode('minimum_severity')
                    ->info('Minimum severity level for severity_filtering processor (only for log processors)')
                    ->values(['trace', 'debug', 'info', 'warn', 'error', 'fatal'])
                    ->defaultValue('info')
                ->end()
                ->arrayNode('processors')
                    ->info('Array of processor configurations (only for type: composite)')
                    ->arrayPrototype()
                        ->children()
                            ->enumNode('type')
                                ->values($childProcessorTypes)
                                ->isRequired()
                            ->end()
                            ->integerNode('batch_size')
                                ->defaultValue(512)
                                ->min(1)
                            ->end()
                            ->scalarNode('service_id')
                                ->defaultNull()
                            ->end()
                            ->enumNode('minimum_severity')
                                ->values(['trace', 'debug', 'info', 'warn', 'error', 'fatal'])
                                ->defaultValue('info')
                            ->end()
                            ->append($this->exporterNode($signalType))
                            ->append($this->innerProcessorNode($signalType))
                        ->end()
                    ->end()
                ->end()
                ->append($this->exporterNode($signalType))
                ->append($this->innerProcessorNode($signalType))
            ->end();

        return $node;
    }
}
