flow_telemetry:
    exporters:
        otlp_http_logs:
            otlp:
                transport:
                    type: curl
                    endpoint: 'http://localhost:4318'
                    timeout_ms: 1000
                    connect_timeout_ms: 250
                    encoding: json
    logger_provider:
        processor:
            type: severity_filtering
            minimum_severity: warn
            inner_processor:
                type: batching
                exporter: otlp_http_logs

    instrumentation:
        twig:
            trace_blocks: false
            trace_macros: false
