<?php

declare(strict_types=1);

namespace Flow\Documentation\Attribute;

enum Module: string
{
    case AVRO = 'AVRO';
    case AZURE_FILESYSTEM = 'AZURE_FILESYSTEM';
    case AZURE_SDK = 'AZURE_SDK';
    case CHART_JS = 'CHART_JS';
    case CORE = 'CORE';
    case CSV = 'CSV';
    case DEPRECATED = 'DEPRECATED';
    case DOCTRINE = 'DOCTRINE';
    case ELASTIC_SEARCH = 'ELASTIC_SEARCH';
    case EXCEL = 'EXCEL';
    case FILESYSTEM = 'FILESYSTEM';
    case FLOE = 'FLOE';
    case GOOGLE_SHEET = 'GOOGLE_SHEET';
    case HTTP = 'HTTP';
    case JSON = 'JSON';
    case MEILI_SEARCH = 'MEILI_SEARCH';
    case MONOLOG_TELEMETRY_BRIDGE = 'MONOLOG_TELEMETRY_BRIDGE';
    case PARQUET = 'PARQUET';
    case PG_QUERY = 'PG_QUERY';
    case POSTGRESQL = 'POSTGRESQL';
    case POSTGRESQL_MIGRATIONS = 'POSTGRESQL_MIGRATIONS';
    case POSTGRESQL_VALINOR_BRIDGE = 'POSTGRESQL_VALINOR_BRIDGE';
    case PSR18_TELEMETRY_BRIDGE = 'PSR18_TELEMETRY_BRIDGE';
    case PSR3_TELEMETRY_BRIDGE = 'PSR3_TELEMETRY_BRIDGE';
    case PSR7_TELEMETRY_BRIDGE = 'PSR7_TELEMETRY_BRIDGE';
    case S3_FILESYSTEM = 'S3_FILESYSTEM';
    case SEAL = 'SEAL';
    case SYMFONY_HTTP_FOUNDATION_TELEMETRY_BRIDGE = 'SYMFONY_HTTP_FOUNDATION_TELEMETRY_BRIDGE';
    case SYMFONY_TELEMETRY_BUNDLE = 'SYMFONY_TELEMETRY_BUNDLE';
    case TELEMETRY = 'TELEMETRY';
    case TELEMETRY_OTLP = 'TELEMETRY_OTLP';
    case TEXT = 'TEXT';
    case TYPES = 'TYPES';
    case XML = 'XML';
}
