name: "🐛Bug Report"
description: "File a bug report. Bug report can be anything, from poor UX, through incorrect behavior to performance degradation."
title: "[Bug]: "
labels: ["triage"]
projects: ["flow-php/projects/1"]
assignees: [norberttech]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this bug report!**
  - type: markdown
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce?
      description: Please provide a code required to reproduce given issue. This will be automatically formatted into a php code, so no need for backticks.
      render: php
    validations:
      required: true
  - type: markdown
    id: data
    attributes:
      label: Data required to reproduce bug locally
      description: |
        If given bug requires more data to reproduce, please provide it here in a convinient format.
            - php array
            - csv
            - json
            - any other format if bug is format specific
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Flow are you using?
      placeholder: "0.17.*"
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Relevant error output
      description: Please copy and paste any relevant error output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
