name: "💡Proposal"
title: "[Proposal]: "
description: "Suggest a new feature or improvement for Flow PHP Framework"
labels: ["proposal"]
assignees: ["norberttech"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to post this idea!**
        Please fill in the details below to help us understand it.
        Ideas evaluated based on their impact and feasibility.

  - type: textarea
    id: proposal-description
    attributes:
      label: "Describe the Proposal"
      description: "What problem does this feature solve? How would it improve Project?"
    validations:
      required: true

  - type: textarea
    id: api-adjustements
    attributes:
      label: API Adjustments
      description: |
        Please provide a high level API required by this proposal. Usually it should be enough to describe:
            - DataFrame class API changes (methods)
            - DSL functions
    validations:
      required: true

  - type: dropdown
    id: author
    attributes:
      label: |
        Are you intenting to also work on proposed change?
        It's perfectly fine to just propose changes and wait for others to pick them up.
      multiple: false
      options:
        - Yes
        - No
        - Maybe

  - type: dropdown
    id: sponsor
    attributes:
      label: |
        Are you interested in sponsoring this change? If you can't find time to work on given proposal but it's
        time sensitive, it might be a good idea to consider sponsoring this change. Please find more details at https://flow-php.com/sponsor/

      multiple: false
      options:
        - Yes
        - No
        - Maybe

  - type: textarea
    id: integration
    attributes:
      label: "Integration & Dependencies"
      description: |
        If proposal requires integration with third party software/library please provide as much data as possible.
          - Link to GitHub Project / Packagist
          - License
          - Dependencies that this integration would bring to Flow
    validations:
      required: false