<?php

declare(strict_types=1);

namespace Flow\PostgreSql\Tests\Unit\Schema\Diff;

use Flow\PostgreSql\QueryBuilder\Schema\ColumnType;
use Flow\PostgreSql\Schema\Column;
use Flow\PostgreSql\Schema\ColumnDefault;
use Flow\PostgreSql\Schema\Diff\ColumnDiff;
use Flow\PostgreSql\Schema\IdentityGeneration;
use PHPUnit\Framework\TestCase;

final class ColumnDiffTest extends TestCase
{
    public function test_adds_generated_column(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('full_name', ColumnType::text(), true),
            new Column(
                'full_name',
                ColumnType::text(),
                true,
                isGenerated: true,
                generationExpression: 'first_name || last_name',
            ),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users DROP full_name', $sqls[0]->toSql());
        static::assertSame(
            'ALTER TABLE public.users ADD COLUMN full_name pg_catalog.text GENERATED ALWAYS AS (first_name || last_name) STORED',
            $sqls[1]->toSql(),
        );
    }

    public function test_adds_identity_column(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('id', ColumnType::integer(), false),
            new Column(
                'id',
                ColumnType::integer(),
                false,
                isIdentity: true,
                identityGeneration: IdentityGeneration::ALWAYS,
            ),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users DROP id', $sqls[0]->toSql());
        static::assertSame(
            'ALTER TABLE public.users ADD COLUMN id int NOT NULL GENERATED ALWAYS AS IDENTITY',
            $sqls[1]->toSql(),
        );
    }

    public function test_changes_generation_expression(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column(
                'full_name',
                ColumnType::text(),
                true,
                isGenerated: true,
                generationExpression: 'first_name || last_name',
            ),
            new Column(
                'full_name',
                ColumnType::text(),
                true,
                isGenerated: true,
                generationExpression: 'upper(first_name || last_name)',
            ),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users DROP full_name', $sqls[0]->toSql());
        static::assertSame(
            'ALTER TABLE public.users ADD COLUMN full_name pg_catalog.text GENERATED ALWAYS AS (upper(first_name || last_name)) STORED',
            $sqls[1]->toSql(),
        );
    }

    public function test_changes_identity_generation_type(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column(
                'id',
                ColumnType::integer(),
                false,
                isIdentity: true,
                identityGeneration: IdentityGeneration::ALWAYS,
            ),
            new Column(
                'id',
                ColumnType::integer(),
                false,
                isIdentity: true,
                identityGeneration: IdentityGeneration::BY_DEFAULT,
            ),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users DROP id', $sqls[0]->toSql());
        static::assertSame(
            'ALTER TABLE public.users ADD COLUMN id int NOT NULL GENERATED BY DEFAULT AS IDENTITY',
            $sqls[1]->toSql(),
        );
    }

    public function test_changes_type(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('col', ColumnType::text(), true),
            new Column('col', ColumnType::integer(), true),
        );

        $sqls = $diff->generate();

        static::assertCount(1, $sqls);
        static::assertSame('ALTER TABLE public.users ALTER COLUMN col TYPE int', $sqls[0]->toSql());
    }

    public function test_detects_default_change(): void
    {
        $diff = new ColumnDiff(
            'public.test_table',
            new Column(
                'col',
                ColumnType::text(),
                true,
                ColumnDefault::fromExpression("'old_default'", ColumnType::text()),
            ),
            new Column(
                'col',
                ColumnType::text(),
                true,
                ColumnDefault::fromExpression("'new_default'", ColumnType::text()),
            ),
        );

        static::assertTrue($diff->hasDefaultChanged());
        static::assertFalse($diff->hasTypeChanged());
        static::assertFalse($diff->hasNullableChanged());
        static::assertFalse($diff->hasNameChanged());
    }

    public function test_detects_generation_change(): void
    {
        $diff = new ColumnDiff(
            'public.test_table',
            new Column('col', ColumnType::text(), true, isGenerated: false),
            new Column('col', ColumnType::text(), true, isGenerated: true, generationExpression: 'upper(name)'),
        );

        static::assertTrue($diff->hasGenerationChanged());
    }

    public function test_detects_identity_change(): void
    {
        $diff = new ColumnDiff(
            'public.test_table',
            new Column('col', ColumnType::integer(), false, isIdentity: false),
            new Column(
                'col',
                ColumnType::integer(),
                false,
                isIdentity: true,
                identityGeneration: IdentityGeneration::ALWAYS,
            ),
        );

        static::assertTrue($diff->hasIdentityChanged());
    }

    public function test_detects_name_change(): void
    {
        $diff = new ColumnDiff(
            'public.test_table',
            new Column('old_name', ColumnType::text(), true),
            new Column('new_name', ColumnType::text(), true),
        );

        static::assertTrue($diff->hasNameChanged());
        static::assertFalse($diff->hasTypeChanged());
        static::assertFalse($diff->hasNullableChanged());
        static::assertFalse($diff->hasDefaultChanged());
    }

    public function test_detects_nullable_change(): void
    {
        $diff = new ColumnDiff(
            'public.test_table',
            new Column('col', ColumnType::text(), true),
            new Column('col', ColumnType::text(), false),
        );

        static::assertTrue($diff->hasNullableChanged());
        static::assertFalse($diff->hasTypeChanged());
    }

    public function test_detects_type_change(): void
    {
        $diff = new ColumnDiff(
            'public.test_table',
            new Column('col', ColumnType::integer(), true),
            new Column('col', ColumnType::text(), true),
        );

        static::assertTrue($diff->hasTypeChanged());
        static::assertFalse($diff->hasNullableChanged());
    }

    public function test_drops_default(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('col', ColumnType::text(), true, ColumnDefault::fromExpression("'42'", ColumnType::text())),
            new Column('col', ColumnType::text(), true, null),
        );

        $sqls = $diff->generate();

        static::assertCount(1, $sqls);
        static::assertSame('ALTER TABLE public.users ALTER COLUMN col DROP DEFAULT', $sqls[0]->toSql());
    }

    public function test_drops_not_null(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('col', ColumnType::text(), false),
            new Column('col', ColumnType::text(), true),
        );

        $sqls = $diff->generate();

        static::assertCount(1, $sqls);
        static::assertSame('ALTER TABLE public.users ALTER COLUMN col DROP NOT NULL', $sqls[0]->toSql());
    }

    public function test_generated_column_with_not_null(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('computed', ColumnType::text(), true),
            new Column('computed', ColumnType::text(), false, isGenerated: true, generationExpression: 'upper(name)'),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users DROP computed', $sqls[0]->toSql());
        static::assertSame(
            'ALTER TABLE public.users ADD COLUMN computed pg_catalog.text NOT NULL GENERATED ALWAYS AS (upper(name)) STORED',
            $sqls[1]->toSql(),
        );
    }

    public function test_type_change_reapplies_default_with_same_literal(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column(
                'amount',
                ColumnType::doublePrecision(),
                true,
                ColumnDefault::fromExpression("'0'", ColumnType::doublePrecision()),
            ),
            new Column(
                'amount',
                ColumnType::numeric(10, 3),
                true,
                ColumnDefault::fromExpression("'0'", ColumnType::numeric(10, 3)),
            ),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users ALTER COLUMN amount TYPE numeric(10, 3)', $sqls[0]->toSql());
        static::assertSame("ALTER TABLE public.users ALTER COLUMN amount SET DEFAULT '0'", $sqls[1]->toSql());
    }

    public function test_type_change_with_changed_default_emits_single_set_default(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column(
                'amount',
                ColumnType::doublePrecision(),
                true,
                ColumnDefault::fromExpression("'0'", ColumnType::doublePrecision()),
            ),
            new Column(
                'amount',
                ColumnType::numeric(10, 3),
                true,
                ColumnDefault::fromExpression("'1'", ColumnType::numeric(10, 3)),
            ),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users ALTER COLUMN amount TYPE numeric(10, 3)', $sqls[0]->toSql());
        static::assertSame("ALTER TABLE public.users ALTER COLUMN amount SET DEFAULT '1'", $sqls[1]->toSql());
    }

    public function test_type_change_with_no_default_emits_no_set_default(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('amount', ColumnType::doublePrecision(), true, null),
            new Column('amount', ColumnType::numeric(10, 3), true, null),
        );

        $sqls = $diff->generate();

        static::assertCount(1, $sqls);
        static::assertSame('ALTER TABLE public.users ALTER COLUMN amount TYPE numeric(10, 3)', $sqls[0]->toSql());
    }

    public function test_type_change_to_null_default_drops_default(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column(
                'amount',
                ColumnType::doublePrecision(),
                true,
                ColumnDefault::fromExpression("'0'", ColumnType::doublePrecision()),
            ),
            new Column('amount', ColumnType::numeric(10, 3), true, null),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users ALTER COLUMN amount TYPE numeric(10, 3)', $sqls[0]->toSql());
        static::assertSame('ALTER TABLE public.users ALTER COLUMN amount DROP DEFAULT', $sqls[1]->toSql());
    }

    public function test_type_change_with_generation_transition_keeps_drop_and_readd(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('total', ColumnType::doublePrecision(), true),
            new Column(
                'total',
                ColumnType::numeric(10, 3),
                true,
                isGenerated: true,
                generationExpression: 'price * qty',
            ),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users DROP total', $sqls[0]->toSql());
        static::assertSame(
            'ALTER TABLE public.users ADD COLUMN total numeric(10, 3) GENERATED ALWAYS AS (price * qty) STORED',
            $sqls[1]->toSql(),
        );
    }

    public function test_handles_multiple_changes_type_nullable_default(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('col', ColumnType::text(), true, null),
            new Column('col', ColumnType::integer(), false, ColumnDefault::fromExpression('0', ColumnType::integer())),
        );

        $sqls = $diff->generate();

        static::assertCount(3, $sqls);
        static::assertSame('ALTER TABLE public.users ALTER COLUMN col TYPE int', $sqls[0]->toSql());
        static::assertSame('ALTER TABLE public.users ALTER COLUMN col SET NOT NULL', $sqls[1]->toSql());
        static::assertSame('ALTER TABLE public.users ALTER COLUMN col SET DEFAULT 0', $sqls[2]->toSql());
    }

    public function test_handles_rename_and_type_change(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('old_name', ColumnType::text(), true),
            new Column('new_name', ColumnType::integer(), true),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users RENAME COLUMN old_name TO new_name', $sqls[0]->toSql());
        static::assertSame('ALTER TABLE public.users ALTER COLUMN new_name TYPE int', $sqls[1]->toSql());
    }

    public function test_handles_rename_with_generation_change(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('old_name', ColumnType::text(), true),
            new Column('new_name', ColumnType::text(), true, isGenerated: true, generationExpression: 'upper(name)'),
        );

        $sqls = $diff->generate();

        static::assertCount(3, $sqls);
        static::assertSame('ALTER TABLE public.users RENAME COLUMN old_name TO new_name', $sqls[0]->toSql());
        static::assertSame('ALTER TABLE public.users DROP new_name', $sqls[1]->toSql());
        static::assertSame(
            'ALTER TABLE public.users ADD COLUMN new_name pg_catalog.text GENERATED ALWAYS AS (upper(name)) STORED',
            $sqls[2]->toSql(),
        );
    }

    public function test_identity_with_default_and_not_null(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('id', ColumnType::integer(), true),
            new Column(
                'id',
                ColumnType::integer(),
                false,
                default: ColumnDefault::fromExpression('0', ColumnType::integer()),
                isIdentity: true,
                identityGeneration: IdentityGeneration::BY_DEFAULT,
            ),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users DROP id', $sqls[0]->toSql());
        static::assertSame(
            'ALTER TABLE public.users ADD COLUMN id int NOT NULL DEFAULT 0 GENERATED BY DEFAULT AS IDENTITY',
            $sqls[1]->toSql(),
        );
    }

    public function test_no_changes_when_identical(): void
    {
        $diff = new ColumnDiff(
            'public.test_table',
            new Column(
                'col',
                ColumnType::text(),
                true,
                ColumnDefault::fromExpression("'default_val'", ColumnType::text()),
            ),
            new Column(
                'col',
                ColumnType::text(),
                true,
                ColumnDefault::fromExpression("'default_val'", ColumnType::text()),
            ),
        );

        static::assertFalse($diff->hasNameChanged());
        static::assertFalse($diff->hasTypeChanged());
        static::assertFalse($diff->hasNullableChanged());
        static::assertFalse($diff->hasDefaultChanged());
        static::assertFalse($diff->hasIdentityChanged());
        static::assertFalse($diff->hasGenerationChanged());
    }

    public function test_removes_generation_from_column(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column(
                'full_name',
                ColumnType::text(),
                true,
                isGenerated: true,
                generationExpression: 'first_name || last_name',
            ),
            new Column('full_name', ColumnType::text(), true),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users DROP full_name', $sqls[0]->toSql());
        static::assertSame('ALTER TABLE public.users ADD COLUMN full_name pg_catalog.text', $sqls[1]->toSql());
    }

    public function test_removes_identity_from_column(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column(
                'id',
                ColumnType::integer(),
                false,
                isIdentity: true,
                identityGeneration: IdentityGeneration::ALWAYS,
            ),
            new Column('id', ColumnType::integer(), false),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users DROP id', $sqls[0]->toSql());
        static::assertSame('ALTER TABLE public.users ADD COLUMN id int NOT NULL', $sqls[1]->toSql());
    }

    public function test_renames_column(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('old_name', ColumnType::text(), true),
            new Column('new_name', ColumnType::text(), true),
        );

        $sqls = $diff->generate();

        static::assertCount(1, $sqls);
        static::assertSame('ALTER TABLE public.users RENAME COLUMN old_name TO new_name', $sqls[0]->toSql());
    }

    public function test_returns_empty_when_no_changes(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('col', ColumnType::text(), true),
            new Column('col', ColumnType::text(), true),
        );

        static::assertSame([], $diff->generate());
    }

    public function test_reversed_generation_change(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('full_name', ColumnType::text(), true, isGenerated: true, generationExpression: 'upper(name)'),
            new Column('full_name', ColumnType::text(), true),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users DROP full_name', $sqls[0]->toSql());
        static::assertSame('ALTER TABLE public.users ADD COLUMN full_name pg_catalog.text', $sqls[1]->toSql());
    }

    public function test_reversed_identity_change(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column(
                'id',
                ColumnType::integer(),
                false,
                isIdentity: true,
                identityGeneration: IdentityGeneration::ALWAYS,
            ),
            new Column('id', ColumnType::integer(), false),
        );

        $sqls = $diff->generate();

        static::assertCount(2, $sqls);
        static::assertSame('ALTER TABLE public.users DROP id', $sqls[0]->toSql());
        static::assertSame('ALTER TABLE public.users ADD COLUMN id int NOT NULL', $sqls[1]->toSql());
    }

    public function test_reversed_type_change(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('col', ColumnType::integer(), true),
            new Column('col', ColumnType::text(), true),
        );

        $sqls = $diff->generate();

        static::assertCount(1, $sqls);
        static::assertSame('ALTER TABLE public.users ALTER COLUMN col TYPE pg_catalog.text', $sqls[0]->toSql());
    }

    public function test_sets_default(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('col', ColumnType::text(), true, null),
            new Column('col', ColumnType::text(), true, ColumnDefault::fromExpression('42', ColumnType::text())),
        );

        $sqls = $diff->generate();

        static::assertCount(1, $sqls);
        static::assertSame('ALTER TABLE public.users ALTER COLUMN col SET DEFAULT 42', $sqls[0]->toSql());
    }

    public function test_sets_not_null(): void
    {
        $diff = new ColumnDiff(
            'public.users',
            new Column('col', ColumnType::text(), true),
            new Column('col', ColumnType::text(), false),
        );

        $sqls = $diff->generate();

        static::assertCount(1, $sqls);
        static::assertSame('ALTER TABLE public.users ALTER COLUMN col SET NOT NULL', $sqls[0]->toSql());
    }
}
