receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: basic
  otlp/aspire:
    endpoint: aspire:18889
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/aspire]
    metrics:
      receivers: [otlp]
      exporters: [debug, otlp/aspire]
    logs:
      receivers: [otlp]
      exporters: [debug, otlp/aspire]
