# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    examples_path: '../../../examples'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Flow\Website\:
        resource: '../src/Flow/Website/'
        exclude:
            - '../src/Flow/Website/Kernel.php'

    Flow\Website\Service\:
        resource: '../src/Flow/Website/Service/'

    Flow\Website\Factory\Github\ContributorsRequestFactory:
        arguments:
            $githubToken: '%env(GITHUB_TOKEN)%'

    Flow\Website\Service\Examples:
        arguments:
            $examplesPath: '%examples_path%'