# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    examples_path: '%kernel.project_dir%/../../examples'
    domain: '%env(DOMAIN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Flow\Website\:
        resource: '../src/Flow/Website/'
        exclude:
            - '../src/Flow/Website/Kernel.php'

    Flow\Website\Service\:
        resource: '../src/Flow/Website/Service/'

    Flow\Website\Factory\Github\ContributorsRequestFactory:
        arguments:
            $githubToken: '%env(GITHUB_TOKEN)%'

    Flow\Website\StaticSourceProvider\:
        resource: '../src/Flow/Website/StaticSourceProvider/'
        tags: ['static_content_generator.source_provider']

    Flow\Website\Service\Examples:
        arguments:
            $examplesPath: '%examples_path%'

    Flow\Website\Twig\:
        resource: '../src/Flow/Website/Twig/**/*Extension.php'
        tags: [twig.extension]