flow_telemetry:
  service:
    name: "flow-website"
    version: "1.0.0"
    attributes:
      deployment.environment: "%kernel.environment%"
  instrumentation:
    http_kernel:
      enabled: true
      exclude_routes:
        - '_wdt'
        - '_profiler'
        - '/_profiler.*/'
    console:
      enabled: true
      exclude_commands:
        - 'cache:clear'
        - 'debug:router'
    twig:
      enabled: true
      trace_templates: true
      trace_blocks: true
      trace_macros: true
      exclude_templates:
        - '/\@WebProfiler*/'
    http_client:
      enabled: true

  tracer_provider:
    sampler:
      type: always_on
    processor:
      type: batching
      batch_size: 512
      exporter:
        type: otlp
        otlp:
          transport:
            type: curl
            endpoint: "http://localhost:4318"
            timeout: 30
            serializer:
              type: json

  meter_provider:
    temporality: cumulative
    processor:
      type: batching
      exporter:
        type: otlp
        otlp:
          transport:
            type: curl
            endpoint: "http://localhost:4318"
            timeout: 30
            serializer:
              type: json

  logger_provider:
    processor:
      type: batching
      exporter:
        type: otlp
        otlp:
          transport:
            type: curl
            endpoint: "http://localhost:4318"
            timeout: 30
            serializer:
              type: json
