# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true
    router:
        default_uri: '%base_url%/'
    assets:
        base_urls:
            - '%base_url%/'

when@test:
    framework:
        test: true
