monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        telemetry:
            type: service
            id: Flow\Bridge\Monolog\Telemetry\TelemetryHandler

when@dev:
    monolog:
        handlers:
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            telemetry:
                type: service
                id: Flow\Bridge\Monolog\Telemetry\TelemetryHandler
