<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: opentelemetry/proto/profiles/v1development/profiles.proto

namespace Opentelemetry\Proto\Profiles\V1development;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ProfilesDictionary represents the profiles data shared across the
 * entire message being sent. The following applies to all fields in this
 * message:
 * - A dictionary is an array of dictionary items. Users of the dictionary
 *   compactly reference the items using the index within the array.
 * - A dictionary MUST have a zero value encoded as the first element. This
 *   allows for _index fields pointing into the dictionary to use a 0 pointer
 *   value to indicate 'null' / 'not set'. Unless otherwise defined, a 'zero
 *   value' message value is one with all default field values, so as to
 *   minimize wire encoded size.
 * - There SHOULD NOT be dupes in a dictionary. The identity of dictionary
 *   items is based on their value, recursively as needed. If a particular
 *   implementation does emit duplicated items, it MUST NOT attempt to give them
 *   meaning based on the index or order. A profile processor may remove
 *   duplicate items and this MUST NOT have any observable effects for
 *   consumers.
 * - There SHOULD NOT be orphaned (unreferenced) items in a dictionary. A
 *   profile processor may remove ("garbage-collect") orphaned items and this
 *   MUST NOT have any observable effects for consumers.
 *
 * Generated from protobuf message <code>opentelemetry.proto.profiles.v1development.ProfilesDictionary</code>
 */
class ProfilesDictionary extends \Google\Protobuf\Internal\Message
{
    /**
     * Mappings from address ranges to the image/binary/library mapped
     * into that address range referenced by locations via Location.mapping_index.
     * mapping_table[0] must always be zero value (Mapping{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Mapping mapping_table = 1;</code>
     */
    private $mapping_table;
    /**
     * Locations referenced by samples via Stack.location_indices.
     * location_table[0] must always be zero value (Location{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Location location_table = 2;</code>
     */
    private $location_table;
    /**
     * Functions referenced by locations via Line.function_index.
     * function_table[0] must always be zero value (Function{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Function function_table = 3;</code>
     */
    private $function_table;
    /**
     * Links referenced by samples via Sample.link_index.
     * link_table[0] must always be zero value (Link{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Link link_table = 4;</code>
     */
    private $link_table;
    /**
     * A common table for strings referenced by various messages.
     * string_table[0] must always be "" and present.
     *
     * Generated from protobuf field <code>repeated string string_table = 5;</code>
     */
    private $string_table;
    /**
     * A common table for attributes referenced by the Profile, Sample, Mapping
     * and Location messages below through attribute_indices field. Each entry is
     * a key/value pair with an optional unit. Since this is a dictionary table,
     * multiple entries with the same key may be present, unlike direct attribute
     * tables like Resource.attributes. The referencing attribute_indices fields,
     * though, do maintain the key uniqueness requirement.
     * It's recommended to use attributes for variables with bounded cardinality,
     * such as categorical variables
     * (https://en.wikipedia.org/wiki/Categorical_variable). Using an attribute of
     * a floating point type (e.g., CPU time) in a sample can quickly make every
     * attribute value unique, defeating the purpose of the dictionary and
     * impractically increasing the profile size.
     * Examples of attributes:
     *     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
     *     "abc.com/myattribute": true
     *     "allocation_size": 128 bytes
     * attribute_table[0] must always be zero value (KeyValueAndUnit{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.KeyValueAndUnit attribute_table = 6;</code>
     */
    private $attribute_table;
    /**
     * Stacks referenced by samples via Sample.stack_index.
     * stack_table[0] must always be zero value (Stack{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Stack stack_table = 7;</code>
     */
    private $stack_table;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opentelemetry\Proto\Profiles\V1development\Mapping[] $mapping_table
     *           Mappings from address ranges to the image/binary/library mapped
     *           into that address range referenced by locations via Location.mapping_index.
     *           mapping_table[0] must always be zero value (Mapping{}) and present.
     *     @type \Opentelemetry\Proto\Profiles\V1development\Location[] $location_table
     *           Locations referenced by samples via Stack.location_indices.
     *           location_table[0] must always be zero value (Location{}) and present.
     *     @type \Opentelemetry\Proto\Profiles\V1development\PBFunction[] $function_table
     *           Functions referenced by locations via Line.function_index.
     *           function_table[0] must always be zero value (Function{}) and present.
     *     @type \Opentelemetry\Proto\Profiles\V1development\Link[] $link_table
     *           Links referenced by samples via Sample.link_index.
     *           link_table[0] must always be zero value (Link{}) and present.
     *     @type string[] $string_table
     *           A common table for strings referenced by various messages.
     *           string_table[0] must always be "" and present.
     *     @type \Opentelemetry\Proto\Profiles\V1development\KeyValueAndUnit[] $attribute_table
     *           A common table for attributes referenced by the Profile, Sample, Mapping
     *           and Location messages below through attribute_indices field. Each entry is
     *           a key/value pair with an optional unit. Since this is a dictionary table,
     *           multiple entries with the same key may be present, unlike direct attribute
     *           tables like Resource.attributes. The referencing attribute_indices fields,
     *           though, do maintain the key uniqueness requirement.
     *           It's recommended to use attributes for variables with bounded cardinality,
     *           such as categorical variables
     *           (https://en.wikipedia.org/wiki/Categorical_variable). Using an attribute of
     *           a floating point type (e.g., CPU time) in a sample can quickly make every
     *           attribute value unique, defeating the purpose of the dictionary and
     *           impractically increasing the profile size.
     *           Examples of attributes:
     *               "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
     *               "abc.com/myattribute": true
     *               "allocation_size": 128 bytes
     *           attribute_table[0] must always be zero value (KeyValueAndUnit{}) and present.
     *     @type \Opentelemetry\Proto\Profiles\V1development\Stack[] $stack_table
     *           Stacks referenced by samples via Sample.stack_index.
     *           stack_table[0] must always be zero value (Stack{}) and present.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Opentelemetry\Proto\Profiles\V1Development\Profiles::initOnce();
        parent::__construct($data);
    }

    /**
     * Mappings from address ranges to the image/binary/library mapped
     * into that address range referenced by locations via Location.mapping_index.
     * mapping_table[0] must always be zero value (Mapping{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Mapping mapping_table = 1;</code>
     * @return RepeatedField<\Opentelemetry\Proto\Profiles\V1development\Mapping>
     */
    public function getMappingTable()
    {
        return $this->mapping_table;
    }

    /**
     * Mappings from address ranges to the image/binary/library mapped
     * into that address range referenced by locations via Location.mapping_index.
     * mapping_table[0] must always be zero value (Mapping{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Mapping mapping_table = 1;</code>
     * @param \Opentelemetry\Proto\Profiles\V1development\Mapping[] $var
     * @return $this
     */
    public function setMappingTable(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField(
            $var,
            \Google\Protobuf\Internal\GPBType::MESSAGE,
            \Opentelemetry\Proto\Profiles\V1development\Mapping::class,
        );
        $this->mapping_table = $arr;

        return $this;
    }

    /**
     * Locations referenced by samples via Stack.location_indices.
     * location_table[0] must always be zero value (Location{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Location location_table = 2;</code>
     * @return RepeatedField<\Opentelemetry\Proto\Profiles\V1development\Location>
     */
    public function getLocationTable()
    {
        return $this->location_table;
    }

    /**
     * Locations referenced by samples via Stack.location_indices.
     * location_table[0] must always be zero value (Location{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Location location_table = 2;</code>
     * @param \Opentelemetry\Proto\Profiles\V1development\Location[] $var
     * @return $this
     */
    public function setLocationTable(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField(
            $var,
            \Google\Protobuf\Internal\GPBType::MESSAGE,
            \Opentelemetry\Proto\Profiles\V1development\Location::class,
        );
        $this->location_table = $arr;

        return $this;
    }

    /**
     * Functions referenced by locations via Line.function_index.
     * function_table[0] must always be zero value (Function{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Function function_table = 3;</code>
     * @return RepeatedField<\Opentelemetry\Proto\Profiles\V1development\PBFunction>
     */
    public function getFunctionTable()
    {
        return $this->function_table;
    }

    /**
     * Functions referenced by locations via Line.function_index.
     * function_table[0] must always be zero value (Function{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Function function_table = 3;</code>
     * @param \Opentelemetry\Proto\Profiles\V1development\PBFunction[] $var
     * @return $this
     */
    public function setFunctionTable(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField(
            $var,
            \Google\Protobuf\Internal\GPBType::MESSAGE,
            \Opentelemetry\Proto\Profiles\V1development\PBFunction::class,
        );
        $this->function_table = $arr;

        return $this;
    }

    /**
     * Links referenced by samples via Sample.link_index.
     * link_table[0] must always be zero value (Link{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Link link_table = 4;</code>
     * @return RepeatedField<\Opentelemetry\Proto\Profiles\V1development\Link>
     */
    public function getLinkTable()
    {
        return $this->link_table;
    }

    /**
     * Links referenced by samples via Sample.link_index.
     * link_table[0] must always be zero value (Link{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Link link_table = 4;</code>
     * @param \Opentelemetry\Proto\Profiles\V1development\Link[] $var
     * @return $this
     */
    public function setLinkTable(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField(
            $var,
            \Google\Protobuf\Internal\GPBType::MESSAGE,
            \Opentelemetry\Proto\Profiles\V1development\Link::class,
        );
        $this->link_table = $arr;

        return $this;
    }

    /**
     * A common table for strings referenced by various messages.
     * string_table[0] must always be "" and present.
     *
     * Generated from protobuf field <code>repeated string string_table = 5;</code>
     * @return RepeatedField<string>
     */
    public function getStringTable()
    {
        return $this->string_table;
    }

    /**
     * A common table for strings referenced by various messages.
     * string_table[0] must always be "" and present.
     *
     * Generated from protobuf field <code>repeated string string_table = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setStringTable(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->string_table = $arr;

        return $this;
    }

    /**
     * A common table for attributes referenced by the Profile, Sample, Mapping
     * and Location messages below through attribute_indices field. Each entry is
     * a key/value pair with an optional unit. Since this is a dictionary table,
     * multiple entries with the same key may be present, unlike direct attribute
     * tables like Resource.attributes. The referencing attribute_indices fields,
     * though, do maintain the key uniqueness requirement.
     * It's recommended to use attributes for variables with bounded cardinality,
     * such as categorical variables
     * (https://en.wikipedia.org/wiki/Categorical_variable). Using an attribute of
     * a floating point type (e.g., CPU time) in a sample can quickly make every
     * attribute value unique, defeating the purpose of the dictionary and
     * impractically increasing the profile size.
     * Examples of attributes:
     *     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
     *     "abc.com/myattribute": true
     *     "allocation_size": 128 bytes
     * attribute_table[0] must always be zero value (KeyValueAndUnit{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.KeyValueAndUnit attribute_table = 6;</code>
     * @return RepeatedField<\Opentelemetry\Proto\Profiles\V1development\KeyValueAndUnit>
     */
    public function getAttributeTable()
    {
        return $this->attribute_table;
    }

    /**
     * A common table for attributes referenced by the Profile, Sample, Mapping
     * and Location messages below through attribute_indices field. Each entry is
     * a key/value pair with an optional unit. Since this is a dictionary table,
     * multiple entries with the same key may be present, unlike direct attribute
     * tables like Resource.attributes. The referencing attribute_indices fields,
     * though, do maintain the key uniqueness requirement.
     * It's recommended to use attributes for variables with bounded cardinality,
     * such as categorical variables
     * (https://en.wikipedia.org/wiki/Categorical_variable). Using an attribute of
     * a floating point type (e.g., CPU time) in a sample can quickly make every
     * attribute value unique, defeating the purpose of the dictionary and
     * impractically increasing the profile size.
     * Examples of attributes:
     *     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
     *     "abc.com/myattribute": true
     *     "allocation_size": 128 bytes
     * attribute_table[0] must always be zero value (KeyValueAndUnit{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.KeyValueAndUnit attribute_table = 6;</code>
     * @param \Opentelemetry\Proto\Profiles\V1development\KeyValueAndUnit[] $var
     * @return $this
     */
    public function setAttributeTable(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField(
            $var,
            \Google\Protobuf\Internal\GPBType::MESSAGE,
            \Opentelemetry\Proto\Profiles\V1development\KeyValueAndUnit::class,
        );
        $this->attribute_table = $arr;

        return $this;
    }

    /**
     * Stacks referenced by samples via Sample.stack_index.
     * stack_table[0] must always be zero value (Stack{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Stack stack_table = 7;</code>
     * @return RepeatedField<\Opentelemetry\Proto\Profiles\V1development\Stack>
     */
    public function getStackTable()
    {
        return $this->stack_table;
    }

    /**
     * Stacks referenced by samples via Sample.stack_index.
     * stack_table[0] must always be zero value (Stack{}) and present.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.profiles.v1development.Stack stack_table = 7;</code>
     * @param \Opentelemetry\Proto\Profiles\V1development\Stack[] $var
     * @return $this
     */
    public function setStackTable(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField(
            $var,
            \Google\Protobuf\Internal\GPBType::MESSAGE,
            \Opentelemetry\Proto\Profiles\V1development\Stack::class,
        );
        $this->stack_table = $arr;

        return $this;
    }
}
