<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: opentelemetry/proto/collector/trace/v1/trace_service.proto

namespace GPBMetadata\Opentelemetry\Proto\Collector\Trace\V1;

class TraceService
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        \GPBMetadata\Opentelemetry\Proto\Trace\V1\Trace::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD8\x05\x0A:opentelemetry/proto/collector/trace/v1/trace_service.proto\x12&opentelemetry.proto.collector.trace.v1\"`\x0A\x19ExportTraceServiceRequest\x12C\x0A\x0Eresource_spans\x18\x01 \x03(\x0B2+.opentelemetry.proto.trace.v1.ResourceSpans\"x\x0A\x1AExportTraceServiceResponse\x12Z\x0A\x0Fpartial_success\x18\x01 \x01(\x0B2A.opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess\"J\x0A\x19ExportTracePartialSuccess\x12\x16\x0A\x0Erejected_spans\x18\x01 \x01(\x03\x12\x15\x0A\x0Derror_message\x18\x02 \x01(\x092\xA2\x01\x0A\x0CTraceService\x12\x91\x01\x0A\x06Export\x12A.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest\x1AB.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse\"\x00B\x9C\x01\x0A)io.opentelemetry.proto.collector.trace.v1B\x11TraceServiceProtoP\x01Z1go.opentelemetry.io/proto/otlp/collector/trace/v1\xAA\x02&OpenTelemetry.Proto.Collector.Trace.V1b\x06proto3",
            true,
        );

        static::$is_initialized = true;
    }
}
