<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: opentelemetry/proto/trace/v1/trace.proto

namespace Opentelemetry\Proto\Trace\V1\Span;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Event is a time-stamped annotation of the span, consisting of user-supplied
 * text description and key-value pairs.
 *
 * Generated from protobuf message <code>opentelemetry.proto.trace.v1.Span.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * The time the event occurred.
     *
     * Generated from protobuf field <code>fixed64 time_unix_nano = 1;</code>
     */
    protected $time_unix_nano = 0;
    /**
     * The name of the event.
     * This field is semantically required to be set to non-empty string.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * A collection of attribute key/value pairs on the event.
     * Attribute keys MUST be unique (it is not allowed to have more than one
     * attribute with the same key).
     * The behavior of software that receives duplicated keys can be unpredictable.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.common.v1.KeyValue attributes = 3;</code>
     */
    private $attributes;
    /**
     * The number of dropped attributes. If the value is 0,
     * then no attributes were dropped.
     *
     * Generated from protobuf field <code>uint32 dropped_attributes_count = 4;</code>
     */
    protected $dropped_attributes_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $time_unix_nano
     *           The time the event occurred.
     *     @type string $name
     *           The name of the event.
     *           This field is semantically required to be set to non-empty string.
     *     @type \Opentelemetry\Proto\Common\V1\KeyValue[] $attributes
     *           A collection of attribute key/value pairs on the event.
     *           Attribute keys MUST be unique (it is not allowed to have more than one
     *           attribute with the same key).
     *           The behavior of software that receives duplicated keys can be unpredictable.
     *     @type int $dropped_attributes_count
     *           The number of dropped attributes. If the value is 0,
     *           then no attributes were dropped.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Opentelemetry\Proto\Trace\V1\Trace::initOnce();
        parent::__construct($data);
    }

    /**
     * The time the event occurred.
     *
     * Generated from protobuf field <code>fixed64 time_unix_nano = 1;</code>
     * @return int|string
     */
    public function getTimeUnixNano()
    {
        return $this->time_unix_nano;
    }

    /**
     * The time the event occurred.
     *
     * Generated from protobuf field <code>fixed64 time_unix_nano = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeUnixNano(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->time_unix_nano = $var;

        return $this;
    }

    /**
     * The name of the event.
     * This field is semantically required to be set to non-empty string.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the event.
     * This field is semantically required to be set to non-empty string.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * A collection of attribute key/value pairs on the event.
     * Attribute keys MUST be unique (it is not allowed to have more than one
     * attribute with the same key).
     * The behavior of software that receives duplicated keys can be unpredictable.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.common.v1.KeyValue attributes = 3;</code>
     * @return RepeatedField<\Opentelemetry\Proto\Common\V1\KeyValue>
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * A collection of attribute key/value pairs on the event.
     * Attribute keys MUST be unique (it is not allowed to have more than one
     * attribute with the same key).
     * The behavior of software that receives duplicated keys can be unpredictable.
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.common.v1.KeyValue attributes = 3;</code>
     * @param \Opentelemetry\Proto\Common\V1\KeyValue[] $var
     * @return $this
     */
    public function setAttributes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField(
            $var,
            \Google\Protobuf\Internal\GPBType::MESSAGE,
            \Opentelemetry\Proto\Common\V1\KeyValue::class,
        );
        $this->attributes = $arr;

        return $this;
    }

    /**
     * The number of dropped attributes. If the value is 0,
     * then no attributes were dropped.
     *
     * Generated from protobuf field <code>uint32 dropped_attributes_count = 4;</code>
     * @return int
     */
    public function getDroppedAttributesCount()
    {
        return $this->dropped_attributes_count;
    }

    /**
     * The number of dropped attributes. If the value is 0,
     * then no attributes were dropped.
     *
     * Generated from protobuf field <code>uint32 dropped_attributes_count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDroppedAttributesCount(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->dropped_attributes_count = $var;

        return $this;
    }
}
