<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.A_Expr</code>
 */
class A_Expr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.A_Expr_Kind kind = 1 [json_name = "kind"];</code>
     */
    protected $kind = 0;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node name = 2 [json_name = "name"];</code>
     */
    private $name;
    /**
     * Generated from protobuf field <code>.pg_query.Node lexpr = 3 [json_name = "lexpr"];</code>
     */
    protected $lexpr = null;
    /**
     * Generated from protobuf field <code>.pg_query.Node rexpr = 4 [json_name = "rexpr"];</code>
     */
    protected $rexpr = null;
    /**
     * Generated from protobuf field <code>int32 rexpr_list_start = 5 [json_name = "rexpr_list_start"];</code>
     */
    protected $rexpr_list_start = 0;
    /**
     * Generated from protobuf field <code>int32 rexpr_list_end = 6 [json_name = "rexpr_list_end"];</code>
     */
    protected $rexpr_list_end = 0;
    /**
     * Generated from protobuf field <code>int32 location = 7 [json_name = "location"];</code>
     */
    protected $location = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $kind
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $name
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $lexpr
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $rexpr
     *     @type int $rexpr_list_start
     *     @type int $rexpr_list_end
     *     @type int $location
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.A_Expr_Kind kind = 1 [json_name = "kind"];</code>
     * @return int one of the values in {@see \Flow\PostgreSql\Protobuf\AST\A_Expr_Kind}
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.pg_query.A_Expr_Kind kind = 1 [json_name = "kind"];</code>
     * @param int $var one of the values in {@see \Flow\PostgreSql\Protobuf\AST\A_Expr_Kind}
     * @return $this
     */
    public function setKind(int $var)
    {
        GPBUtil::checkEnum($var, \Flow\PostgreSql\Protobuf\AST\A_Expr_Kind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node name = 2 [json_name = "name"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node name = 2 [json_name = "name"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setName(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->name = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node lexpr = 3 [json_name = "lexpr"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getLexpr()
    {
        return $this->lexpr;
    }

    public function hasLexpr()
    {
        return isset($this->lexpr);
    }

    public function clearLexpr()
    {
        unset($this->lexpr);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node lexpr = 3 [json_name = "lexpr"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setLexpr(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->lexpr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node rexpr = 4 [json_name = "rexpr"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getRexpr()
    {
        return $this->rexpr;
    }

    public function hasRexpr()
    {
        return isset($this->rexpr);
    }

    public function clearRexpr()
    {
        unset($this->rexpr);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node rexpr = 4 [json_name = "rexpr"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setRexpr(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->rexpr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rexpr_list_start = 5 [json_name = "rexpr_list_start"];</code>
     * @return int
     */
    public function getRexprListStart()
    {
        return $this->rexpr_list_start;
    }

    /**
     * Generated from protobuf field <code>int32 rexpr_list_start = 5 [json_name = "rexpr_list_start"];</code>
     * @param int $var
     * @return $this
     */
    public function setRexprListStart(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->rexpr_list_start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rexpr_list_end = 6 [json_name = "rexpr_list_end"];</code>
     * @return int
     */
    public function getRexprListEnd()
    {
        return $this->rexpr_list_end;
    }

    /**
     * Generated from protobuf field <code>int32 rexpr_list_end = 6 [json_name = "rexpr_list_end"];</code>
     * @param int $var
     * @return $this
     */
    public function setRexprListEnd(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->rexpr_list_end = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 7 [json_name = "location"];</code>
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>int32 location = 7 [json_name = "location"];</code>
     * @param int $var
     * @return $this
     */
    public function setLocation(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

}

