<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.A_Indirection</code>.
 */
class A_Indirection extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 1 [json_name = "arg"];</code>.
     */
    protected $arg;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node indirection = 2 [json_name = "indirection"];</code>.
     */
    private $indirection;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var Node $arg
     * @var array<Node> $indirection
     *                  }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearArg(): void
    {
        $this->arg = null;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 1 [json_name = "arg"];</code>.
     *
     * @return null|Node
     */
    public function getArg()
    {
        return $this->arg;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node indirection = 2 [json_name = "indirection"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getIndirection()
    {
        return $this->indirection;
    }

    public function hasArg()
    {
        return isset($this->arg);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 1 [json_name = "arg"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setArg($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->arg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node indirection = 2 [json_name = "indirection"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setIndirection($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->indirection = $arr;

        return $this;
    }
}
