<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use UnexpectedValueException;

/**
 * Protobuf type <code>pg_query.AggStrategy</code>
 */
class AggStrategy
{
    /**
     * Generated from protobuf enum <code>AGG_STRATEGY_UNDEFINED = 0;</code>
     */
    const AGG_STRATEGY_UNDEFINED = 0;
    /**
     * Generated from protobuf enum <code>AGG_PLAIN = 1;</code>
     */
    const AGG_PLAIN = 1;
    /**
     * Generated from protobuf enum <code>AGG_SORTED = 2;</code>
     */
    const AGG_SORTED = 2;
    /**
     * Generated from protobuf enum <code>AGG_HASHED = 3;</code>
     */
    const AGG_HASHED = 3;
    /**
     * Generated from protobuf enum <code>AGG_MIXED = 4;</code>
     */
    const AGG_MIXED = 4;

    private static $valueToName = [
        self::AGG_STRATEGY_UNDEFINED => 'AGG_STRATEGY_UNDEFINED',
        self::AGG_PLAIN => 'AGG_PLAIN',
        self::AGG_SORTED => 'AGG_SORTED',
        self::AGG_HASHED => 'AGG_HASHED',
        self::AGG_MIXED => 'AGG_MIXED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

