<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.AlterOwnerStmt</code>
 */
class AlterOwnerStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.ObjectType object_type = 1 [json_name = "objectType"];</code>
     */
    protected $object_type = 0;
    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 2 [json_name = "relation"];</code>
     */
    protected $relation = null;
    /**
     * Generated from protobuf field <code>.pg_query.Node object = 3 [json_name = "object"];</code>
     */
    protected $object = null;
    /**
     * Generated from protobuf field <code>.pg_query.RoleSpec newowner = 4 [json_name = "newowner"];</code>
     */
    protected $newowner = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $object_type
     *     @type \Flow\PostgreSql\Protobuf\AST\RangeVar $relation
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $object
     *     @type \Flow\PostgreSql\Protobuf\AST\RoleSpec $newowner
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.ObjectType object_type = 1 [json_name = "objectType"];</code>
     * @return int one of the values in {@see \Flow\PostgreSql\Protobuf\AST\ObjectType}
     */
    public function getObjectType()
    {
        return $this->object_type;
    }

    /**
     * Generated from protobuf field <code>.pg_query.ObjectType object_type = 1 [json_name = "objectType"];</code>
     * @param int $var one of the values in {@see \Flow\PostgreSql\Protobuf\AST\ObjectType}
     * @return $this
     */
    public function setObjectType(int $var)
    {
        GPBUtil::checkEnum($var, \Flow\PostgreSql\Protobuf\AST\ObjectType::class);
        $this->object_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 2 [json_name = "relation"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\RangeVar|null
     */
    public function getRelation()
    {
        return $this->relation;
    }

    public function hasRelation()
    {
        return isset($this->relation);
    }

    public function clearRelation()
    {
        unset($this->relation);
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 2 [json_name = "relation"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\RangeVar $var
     * @return $this
     */
    public function setRelation(\Flow\PostgreSql\Protobuf\AST\RangeVar|null $var)
    {
        $this->relation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node object = 3 [json_name = "object"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getObject()
    {
        return $this->object;
    }

    public function hasObject()
    {
        return isset($this->object);
    }

    public function clearObject()
    {
        unset($this->object);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node object = 3 [json_name = "object"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setObject(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->object = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RoleSpec newowner = 4 [json_name = "newowner"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\RoleSpec|null
     */
    public function getNewowner()
    {
        return $this->newowner;
    }

    public function hasNewowner()
    {
        return isset($this->newowner);
    }

    public function clearNewowner()
    {
        unset($this->newowner);
    }

    /**
     * Generated from protobuf field <code>.pg_query.RoleSpec newowner = 4 [json_name = "newowner"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\RoleSpec $var
     * @return $this
     */
    public function setNewowner(\Flow\PostgreSql\Protobuf\AST\RoleSpec|null $var)
    {
        $this->newowner = $var;

        return $this;
    }

}

