<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.AlterTSConfigurationStmt</code>
 */
class AlterTSConfigurationStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.AlterTSConfigType kind = 1 [json_name = "kind"];</code>
     */
    protected $kind = 0;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node cfgname = 2 [json_name = "cfgname"];</code>
     */
    private $cfgname;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node tokentype = 3 [json_name = "tokentype"];</code>
     */
    private $tokentype;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node dicts = 4 [json_name = "dicts"];</code>
     */
    private $dicts;
    /**
     * Generated from protobuf field <code>bool override = 5 [json_name = "override"];</code>
     */
    protected $override = false;
    /**
     * Generated from protobuf field <code>bool replace = 6 [json_name = "replace"];</code>
     */
    protected $replace = false;
    /**
     * Generated from protobuf field <code>bool missing_ok = 7 [json_name = "missing_ok"];</code>
     */
    protected $missing_ok = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $kind
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $cfgname
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $tokentype
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $dicts
     *     @type bool $override
     *     @type bool $replace
     *     @type bool $missing_ok
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.AlterTSConfigType kind = 1 [json_name = "kind"];</code>
     * @return int one of the values in {@see \Flow\PostgreSql\Protobuf\AST\AlterTSConfigType}
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.pg_query.AlterTSConfigType kind = 1 [json_name = "kind"];</code>
     * @param int $var one of the values in {@see \Flow\PostgreSql\Protobuf\AST\AlterTSConfigType}
     * @return $this
     */
    public function setKind(int $var)
    {
        GPBUtil::checkEnum($var, \Flow\PostgreSql\Protobuf\AST\AlterTSConfigType::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node cfgname = 2 [json_name = "cfgname"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getCfgname()
    {
        return $this->cfgname;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node cfgname = 2 [json_name = "cfgname"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setCfgname(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->cfgname = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node tokentype = 3 [json_name = "tokentype"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getTokentype()
    {
        return $this->tokentype;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node tokentype = 3 [json_name = "tokentype"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setTokentype(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->tokentype = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node dicts = 4 [json_name = "dicts"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getDicts()
    {
        return $this->dicts;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node dicts = 4 [json_name = "dicts"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setDicts(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->dicts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool override = 5 [json_name = "override"];</code>
     * @return bool
     */
    public function getOverride()
    {
        return $this->override;
    }

    /**
     * Generated from protobuf field <code>bool override = 5 [json_name = "override"];</code>
     * @param bool $var
     * @return $this
     */
    public function setOverride(bool $var)
    {
        $this->override = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool replace = 6 [json_name = "replace"];</code>
     * @return bool
     */
    public function getReplace()
    {
        return $this->replace;
    }

    /**
     * Generated from protobuf field <code>bool replace = 6 [json_name = "replace"];</code>
     * @param bool $var
     * @return $this
     */
    public function setReplace(bool $var)
    {
        $this->replace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool missing_ok = 7 [json_name = "missing_ok"];</code>
     * @return bool
     */
    public function getMissingOk()
    {
        return $this->missing_ok;
    }

    /**
     * Generated from protobuf field <code>bool missing_ok = 7 [json_name = "missing_ok"];</code>
     * @param bool $var
     * @return $this
     */
    public function setMissingOk(bool $var)
    {
        $this->missing_ok = $var;

        return $this;
    }

}

