<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.AlterTSConfigurationStmt</code>.
 */
class AlterTSConfigurationStmt extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.AlterTSConfigType kind = 1 [json_name = "kind"];</code>.
     */
    protected $kind = 0;

    /**
     * Generated from protobuf field <code>bool missing_ok = 7 [json_name = "missing_ok"];</code>.
     */
    protected $missing_ok = false;

    /**
     * Generated from protobuf field <code>bool override = 5 [json_name = "override"];</code>.
     */
    protected $override = false;

    /**
     * Generated from protobuf field <code>bool replace = 6 [json_name = "replace"];</code>.
     */
    protected $replace = false;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node cfgname = 2 [json_name = "cfgname"];</code>.
     */
    private $cfgname;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node dicts = 4 [json_name = "dicts"];</code>.
     */
    private $dicts;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node tokentype = 3 [json_name = "tokentype"];</code>.
     */
    private $tokentype;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $kind
     * @var array<Node> $cfgname
     * @var array<Node> $tokentype
     * @var array<Node> $dicts
     * @var bool $override
     * @var bool $replace
     * @var bool $missing_ok
     *           }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node cfgname = 2 [json_name = "cfgname"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getCfgname()
    {
        return $this->cfgname;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node dicts = 4 [json_name = "dicts"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getDicts()
    {
        return $this->dicts;
    }

    /**
     * Generated from protobuf field <code>.pg_query.AlterTSConfigType kind = 1 [json_name = "kind"];</code>.
     *
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>bool missing_ok = 7 [json_name = "missing_ok"];</code>.
     *
     * @return bool
     */
    public function getMissingOk()
    {
        return $this->missing_ok;
    }

    /**
     * Generated from protobuf field <code>bool override = 5 [json_name = "override"];</code>.
     *
     * @return bool
     */
    public function getOverride()
    {
        return $this->override;
    }

    /**
     * Generated from protobuf field <code>bool replace = 6 [json_name = "replace"];</code>.
     *
     * @return bool
     */
    public function getReplace()
    {
        return $this->replace;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node tokentype = 3 [json_name = "tokentype"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getTokentype()
    {
        return $this->tokentype;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node cfgname = 2 [json_name = "cfgname"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setCfgname($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->cfgname = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node dicts = 4 [json_name = "dicts"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setDicts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->dicts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.AlterTSConfigType kind = 1 [json_name = "kind"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, AlterTSConfigType::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool missing_ok = 7 [json_name = "missing_ok"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setMissingOk($var)
    {
        GPBUtil::checkBool($var);
        $this->missing_ok = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool override = 5 [json_name = "override"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setOverride($var)
    {
        GPBUtil::checkBool($var);
        $this->override = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool replace = 6 [json_name = "replace"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setReplace($var)
    {
        GPBUtil::checkBool($var);
        $this->replace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node tokentype = 3 [json_name = "tokentype"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setTokentype($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->tokentype = $arr;

        return $this;
    }
}
