<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>pg_query.AlterRoleSetStmt</code>.
 */
class AlterRoleSetStmt extends Message
{
    /**
     * Generated from protobuf field <code>string database = 2 [json_name = "database"];</code>.
     */
    protected $database = '';

    /**
     * Generated from protobuf field <code>.pg_query.RoleSpec role = 1 [json_name = "role"];</code>.
     */
    protected $role;

    /**
     * Generated from protobuf field <code>.pg_query.VariableSetStmt setstmt = 3 [json_name = "setstmt"];</code>.
     */
    protected $setstmt;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var RoleSpec $role
     * @var string $database
     * @var VariableSetStmt $setstmt
     *                      }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearRole(): void
    {
        $this->role = null;
    }

    public function clearSetstmt(): void
    {
        $this->setstmt = null;
    }

    /**
     * Generated from protobuf field <code>string database = 2 [json_name = "database"];</code>.
     *
     * @return string
     */
    public function getDatabase()
    {
        return $this->database;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RoleSpec role = 1 [json_name = "role"];</code>.
     *
     * @return null|RoleSpec
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>.pg_query.VariableSetStmt setstmt = 3 [json_name = "setstmt"];</code>.
     *
     * @return null|VariableSetStmt
     */
    public function getSetstmt()
    {
        return $this->setstmt;
    }

    public function hasRole()
    {
        return isset($this->role);
    }

    public function hasSetstmt()
    {
        return isset($this->setstmt);
    }

    /**
     * Generated from protobuf field <code>string database = 2 [json_name = "database"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setDatabase($var)
    {
        GPBUtil::checkString($var, true);
        $this->database = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RoleSpec role = 1 [json_name = "role"];</code>.
     *
     * @param RoleSpec $var
     *
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkMessage($var, RoleSpec::class);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.VariableSetStmt setstmt = 3 [json_name = "setstmt"];</code>.
     *
     * @param VariableSetStmt $var
     *
     * @return $this
     */
    public function setSetstmt($var)
    {
        GPBUtil::checkMessage($var, VariableSetStmt::class);
        $this->setstmt = $var;

        return $this;
    }
}
