<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.AlterTableSpaceOptionsStmt</code>
 */
class AlterTableSpaceOptionsStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tablespacename = 1 [json_name = "tablespacename"];</code>
     */
    protected $tablespacename = '';
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
     */
    private $options;
    /**
     * Generated from protobuf field <code>bool is_reset = 3 [json_name = "isReset"];</code>
     */
    protected $is_reset = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tablespacename
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $options
     *     @type bool $is_reset
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tablespacename = 1 [json_name = "tablespacename"];</code>
     * @return string
     */
    public function getTablespacename()
    {
        return $this->tablespacename;
    }

    /**
     * Generated from protobuf field <code>string tablespacename = 1 [json_name = "tablespacename"];</code>
     * @param string $var
     * @return $this
     */
    public function setTablespacename(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->tablespacename = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 2 [json_name = "options"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setOptions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->options = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_reset = 3 [json_name = "isReset"];</code>
     * @return bool
     */
    public function getIsReset()
    {
        return $this->is_reset;
    }

    /**
     * Generated from protobuf field <code>bool is_reset = 3 [json_name = "isReset"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsReset(bool $var)
    {
        $this->is_reset = $var;

        return $this;
    }

}

