<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>pg_query.AlterDatabaseRefreshCollStmt</code>.
 */
class AlterDatabaseRefreshCollStmt extends Message
{
    /**
     * Generated from protobuf field <code>string dbname = 1 [json_name = "dbname"];</code>.
     */
    protected $dbname = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var string $dbname
     *             }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string dbname = 1 [json_name = "dbname"];</code>.
     *
     * @return string
     */
    public function getDbname()
    {
        return $this->dbname;
    }

    /**
     * Generated from protobuf field <code>string dbname = 1 [json_name = "dbname"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setDbname($var)
    {
        GPBUtil::checkString($var, true);
        $this->dbname = $var;

        return $this;
    }
}
