<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use UnexpectedValueException;

/**
 * Protobuf type <code>pg_query.AlterTSConfigType</code>
 */
class AlterTSConfigType
{
    /**
     * Generated from protobuf enum <code>ALTER_TSCONFIG_TYPE_UNDEFINED = 0;</code>
     */
    const ALTER_TSCONFIG_TYPE_UNDEFINED = 0;
    /**
     * Generated from protobuf enum <code>ALTER_TSCONFIG_ADD_MAPPING = 1;</code>
     */
    const ALTER_TSCONFIG_ADD_MAPPING = 1;
    /**
     * Generated from protobuf enum <code>ALTER_TSCONFIG_ALTER_MAPPING_FOR_TOKEN = 2;</code>
     */
    const ALTER_TSCONFIG_ALTER_MAPPING_FOR_TOKEN = 2;
    /**
     * Generated from protobuf enum <code>ALTER_TSCONFIG_REPLACE_DICT = 3;</code>
     */
    const ALTER_TSCONFIG_REPLACE_DICT = 3;
    /**
     * Generated from protobuf enum <code>ALTER_TSCONFIG_REPLACE_DICT_FOR_TOKEN = 4;</code>
     */
    const ALTER_TSCONFIG_REPLACE_DICT_FOR_TOKEN = 4;
    /**
     * Generated from protobuf enum <code>ALTER_TSCONFIG_DROP_MAPPING = 5;</code>
     */
    const ALTER_TSCONFIG_DROP_MAPPING = 5;

    private static $valueToName = [
        self::ALTER_TSCONFIG_TYPE_UNDEFINED => 'ALTER_TSCONFIG_TYPE_UNDEFINED',
        self::ALTER_TSCONFIG_ADD_MAPPING => 'ALTER_TSCONFIG_ADD_MAPPING',
        self::ALTER_TSCONFIG_ALTER_MAPPING_FOR_TOKEN => 'ALTER_TSCONFIG_ALTER_MAPPING_FOR_TOKEN',
        self::ALTER_TSCONFIG_REPLACE_DICT => 'ALTER_TSCONFIG_REPLACE_DICT',
        self::ALTER_TSCONFIG_REPLACE_DICT_FOR_TOKEN => 'ALTER_TSCONFIG_REPLACE_DICT_FOR_TOKEN',
        self::ALTER_TSCONFIG_DROP_MAPPING => 'ALTER_TSCONFIG_DROP_MAPPING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

