<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.AlterSystemStmt</code>
 */
class AlterSystemStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.VariableSetStmt setstmt = 1 [json_name = "setstmt"];</code>
     */
    protected $setstmt = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\VariableSetStmt $setstmt
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.VariableSetStmt setstmt = 1 [json_name = "setstmt"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\VariableSetStmt|null
     */
    public function getSetstmt()
    {
        return $this->setstmt;
    }

    public function hasSetstmt()
    {
        return isset($this->setstmt);
    }

    public function clearSetstmt()
    {
        unset($this->setstmt);
    }

    /**
     * Generated from protobuf field <code>.pg_query.VariableSetStmt setstmt = 1 [json_name = "setstmt"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\VariableSetStmt $var
     * @return $this
     */
    public function setSetstmt(\Flow\PostgreSql\Protobuf\AST\VariableSetStmt|null $var)
    {
        $this->setstmt = $var;

        return $this;
    }

}

