<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.ATAlterConstraint</code>
 */
class ATAlterConstraint extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string conname = 1 [json_name = "conname"];</code>
     */
    protected $conname = '';
    /**
     * Generated from protobuf field <code>bool alter_enforceability = 2 [json_name = "alterEnforceability"];</code>
     */
    protected $alter_enforceability = false;
    /**
     * Generated from protobuf field <code>bool is_enforced = 3 [json_name = "is_enforced"];</code>
     */
    protected $is_enforced = false;
    /**
     * Generated from protobuf field <code>bool alter_deferrability = 4 [json_name = "alterDeferrability"];</code>
     */
    protected $alter_deferrability = false;
    /**
     * Generated from protobuf field <code>bool deferrable = 5 [json_name = "deferrable"];</code>
     */
    protected $deferrable = false;
    /**
     * Generated from protobuf field <code>bool initdeferred = 6 [json_name = "initdeferred"];</code>
     */
    protected $initdeferred = false;
    /**
     * Generated from protobuf field <code>bool alter_inheritability = 7 [json_name = "alterInheritability"];</code>
     */
    protected $alter_inheritability = false;
    /**
     * Generated from protobuf field <code>bool noinherit = 8 [json_name = "noinherit"];</code>
     */
    protected $noinherit = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $conname
     *     @type bool $alter_enforceability
     *     @type bool $is_enforced
     *     @type bool $alter_deferrability
     *     @type bool $deferrable
     *     @type bool $initdeferred
     *     @type bool $alter_inheritability
     *     @type bool $noinherit
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string conname = 1 [json_name = "conname"];</code>
     * @return string
     */
    public function getConname()
    {
        return $this->conname;
    }

    /**
     * Generated from protobuf field <code>string conname = 1 [json_name = "conname"];</code>
     * @param string $var
     * @return $this
     */
    public function setConname(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->conname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool alter_enforceability = 2 [json_name = "alterEnforceability"];</code>
     * @return bool
     */
    public function getAlterEnforceability()
    {
        return $this->alter_enforceability;
    }

    /**
     * Generated from protobuf field <code>bool alter_enforceability = 2 [json_name = "alterEnforceability"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAlterEnforceability(bool $var)
    {
        $this->alter_enforceability = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_enforced = 3 [json_name = "is_enforced"];</code>
     * @return bool
     */
    public function getIsEnforced()
    {
        return $this->is_enforced;
    }

    /**
     * Generated from protobuf field <code>bool is_enforced = 3 [json_name = "is_enforced"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEnforced(bool $var)
    {
        $this->is_enforced = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool alter_deferrability = 4 [json_name = "alterDeferrability"];</code>
     * @return bool
     */
    public function getAlterDeferrability()
    {
        return $this->alter_deferrability;
    }

    /**
     * Generated from protobuf field <code>bool alter_deferrability = 4 [json_name = "alterDeferrability"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAlterDeferrability(bool $var)
    {
        $this->alter_deferrability = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool deferrable = 5 [json_name = "deferrable"];</code>
     * @return bool
     */
    public function getDeferrable()
    {
        return $this->deferrable;
    }

    /**
     * Generated from protobuf field <code>bool deferrable = 5 [json_name = "deferrable"];</code>
     * @param bool $var
     * @return $this
     */
    public function setDeferrable(bool $var)
    {
        $this->deferrable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool initdeferred = 6 [json_name = "initdeferred"];</code>
     * @return bool
     */
    public function getInitdeferred()
    {
        return $this->initdeferred;
    }

    /**
     * Generated from protobuf field <code>bool initdeferred = 6 [json_name = "initdeferred"];</code>
     * @param bool $var
     * @return $this
     */
    public function setInitdeferred(bool $var)
    {
        $this->initdeferred = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool alter_inheritability = 7 [json_name = "alterInheritability"];</code>
     * @return bool
     */
    public function getAlterInheritability()
    {
        return $this->alter_inheritability;
    }

    /**
     * Generated from protobuf field <code>bool alter_inheritability = 7 [json_name = "alterInheritability"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAlterInheritability(bool $var)
    {
        $this->alter_inheritability = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool noinherit = 8 [json_name = "noinherit"];</code>
     * @return bool
     */
    public function getNoinherit()
    {
        return $this->noinherit;
    }

    /**
     * Generated from protobuf field <code>bool noinherit = 8 [json_name = "noinherit"];</code>
     * @param bool $var
     * @return $this
     */
    public function setNoinherit(bool $var)
    {
        $this->noinherit = $var;

        return $this;
    }

}

