<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use UnexpectedValueException;

/**
 * Protobuf type <code>pg_query.BoolTestType</code>
 */
class BoolTestType
{
    /**
     * Generated from protobuf enum <code>BOOL_TEST_TYPE_UNDEFINED = 0;</code>
     */
    const BOOL_TEST_TYPE_UNDEFINED = 0;
    /**
     * Generated from protobuf enum <code>IS_TRUE = 1;</code>
     */
    const IS_TRUE = 1;
    /**
     * Generated from protobuf enum <code>IS_NOT_TRUE = 2;</code>
     */
    const IS_NOT_TRUE = 2;
    /**
     * Generated from protobuf enum <code>IS_FALSE = 3;</code>
     */
    const IS_FALSE = 3;
    /**
     * Generated from protobuf enum <code>IS_NOT_FALSE = 4;</code>
     */
    const IS_NOT_FALSE = 4;
    /**
     * Generated from protobuf enum <code>IS_UNKNOWN = 5;</code>
     */
    const IS_UNKNOWN = 5;
    /**
     * Generated from protobuf enum <code>IS_NOT_UNKNOWN = 6;</code>
     */
    const IS_NOT_UNKNOWN = 6;

    private static $valueToName = [
        self::BOOL_TEST_TYPE_UNDEFINED => 'BOOL_TEST_TYPE_UNDEFINED',
        self::IS_TRUE => 'IS_TRUE',
        self::IS_NOT_TRUE => 'IS_NOT_TRUE',
        self::IS_FALSE => 'IS_FALSE',
        self::IS_NOT_FALSE => 'IS_NOT_FALSE',
        self::IS_UNKNOWN => 'IS_UNKNOWN',
        self::IS_NOT_UNKNOWN => 'IS_NOT_UNKNOWN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

