<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CallContext</code>
 */
class CallContext extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool atomic = 1 [json_name = "atomic"];</code>
     */
    protected $atomic = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $atomic
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool atomic = 1 [json_name = "atomic"];</code>
     * @return bool
     */
    public function getAtomic()
    {
        return $this->atomic;
    }

    /**
     * Generated from protobuf field <code>bool atomic = 1 [json_name = "atomic"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAtomic(bool $var)
    {
        $this->atomic = $var;

        return $this;
    }

}

