<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CallStmt</code>
 */
class CallStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.FuncCall funccall = 1 [json_name = "funccall"];</code>
     */
    protected $funccall = null;
    /**
     * Generated from protobuf field <code>.pg_query.FuncExpr funcexpr = 2 [json_name = "funcexpr"];</code>
     */
    protected $funcexpr = null;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node outargs = 3 [json_name = "outargs"];</code>
     */
    private $outargs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\FuncCall $funccall
     *     @type \Flow\PostgreSql\Protobuf\AST\FuncExpr $funcexpr
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $outargs
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.FuncCall funccall = 1 [json_name = "funccall"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\FuncCall|null
     */
    public function getFunccall()
    {
        return $this->funccall;
    }

    public function hasFunccall()
    {
        return isset($this->funccall);
    }

    public function clearFunccall()
    {
        unset($this->funccall);
    }

    /**
     * Generated from protobuf field <code>.pg_query.FuncCall funccall = 1 [json_name = "funccall"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\FuncCall $var
     * @return $this
     */
    public function setFunccall(\Flow\PostgreSql\Protobuf\AST\FuncCall|null $var)
    {
        $this->funccall = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.FuncExpr funcexpr = 2 [json_name = "funcexpr"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\FuncExpr|null
     */
    public function getFuncexpr()
    {
        return $this->funcexpr;
    }

    public function hasFuncexpr()
    {
        return isset($this->funcexpr);
    }

    public function clearFuncexpr()
    {
        unset($this->funcexpr);
    }

    /**
     * Generated from protobuf field <code>.pg_query.FuncExpr funcexpr = 2 [json_name = "funcexpr"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\FuncExpr $var
     * @return $this
     */
    public function setFuncexpr(\Flow\PostgreSql\Protobuf\AST\FuncExpr|null $var)
    {
        $this->funcexpr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node outargs = 3 [json_name = "outargs"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getOutargs()
    {
        return $this->outargs;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node outargs = 3 [json_name = "outargs"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setOutargs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->outargs = $arr;

        return $this;
    }

}

