<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CaseWhen</code>
 */
class CaseWhen extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
     */
    protected $xpr = null;
    /**
     * Generated from protobuf field <code>.pg_query.Node expr = 2 [json_name = "expr"];</code>
     */
    protected $expr = null;
    /**
     * Generated from protobuf field <code>.pg_query.Node result = 3 [json_name = "result"];</code>
     */
    protected $result = null;
    /**
     * Generated from protobuf field <code>int32 location = 4 [json_name = "location"];</code>
     */
    protected $location = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $xpr
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $expr
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $result
     *     @type int $location
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getXpr()
    {
        return $this->xpr;
    }

    public function hasXpr()
    {
        return isset($this->xpr);
    }

    public function clearXpr()
    {
        unset($this->xpr);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setXpr(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->xpr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node expr = 2 [json_name = "expr"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getExpr()
    {
        return $this->expr;
    }

    public function hasExpr()
    {
        return isset($this->expr);
    }

    public function clearExpr()
    {
        unset($this->expr);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node expr = 2 [json_name = "expr"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setExpr(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->expr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node result = 3 [json_name = "result"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getResult()
    {
        return $this->result;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node result = 3 [json_name = "result"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setResult(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 4 [json_name = "location"];</code>
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>int32 location = 4 [json_name = "location"];</code>
     * @param int $var
     * @return $this
     */
    public function setLocation(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

}

