<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CaseExpr</code>.
 */
class CaseExpr extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 4 [json_name = "arg"];</code>.
     */
    protected $arg;

    /**
     * Generated from protobuf field <code>uint32 casecollid = 3 [json_name = "casecollid"];</code>.
     */
    protected $casecollid = 0;

    /**
     * Generated from protobuf field <code>uint32 casetype = 2 [json_name = "casetype"];</code>.
     */
    protected $casetype = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Node defresult = 6 [json_name = "defresult"];</code>.
     */
    protected $defresult;

    /**
     * Generated from protobuf field <code>int32 location = 7 [json_name = "location"];</code>.
     */
    protected $location = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     */
    protected $xpr;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 5 [json_name = "args"];</code>.
     */
    private $args;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var Node $xpr
     * @var int $casetype
     * @var int $casecollid
     * @var Node $arg
     * @var array<Node> $args
     * @var Node $defresult
     * @var int $location
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearArg(): void
    {
        $this->arg = null;
    }

    public function clearDefresult(): void
    {
        $this->defresult = null;
    }

    public function clearXpr(): void
    {
        $this->xpr = null;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 4 [json_name = "arg"];</code>.
     *
     * @return null|Node
     */
    public function getArg()
    {
        return $this->arg;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 5 [json_name = "args"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Generated from protobuf field <code>uint32 casecollid = 3 [json_name = "casecollid"];</code>.
     *
     * @return int
     */
    public function getCasecollid()
    {
        return $this->casecollid;
    }

    /**
     * Generated from protobuf field <code>uint32 casetype = 2 [json_name = "casetype"];</code>.
     *
     * @return int
     */
    public function getCasetype()
    {
        return $this->casetype;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node defresult = 6 [json_name = "defresult"];</code>.
     *
     * @return null|Node
     */
    public function getDefresult()
    {
        return $this->defresult;
    }

    /**
     * Generated from protobuf field <code>int32 location = 7 [json_name = "location"];</code>.
     *
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @return null|Node
     */
    public function getXpr()
    {
        return $this->xpr;
    }

    public function hasArg()
    {
        return isset($this->arg);
    }

    public function hasDefresult()
    {
        return isset($this->defresult);
    }

    public function hasXpr()
    {
        return isset($this->xpr);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 4 [json_name = "arg"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setArg($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->arg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 5 [json_name = "args"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->args = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 casecollid = 3 [json_name = "casecollid"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setCasecollid($var)
    {
        GPBUtil::checkUint32($var);
        $this->casecollid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 casetype = 2 [json_name = "casetype"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setCasetype($var)
    {
        GPBUtil::checkUint32($var);
        $this->casetype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node defresult = 6 [json_name = "defresult"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setDefresult($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->defresult = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 7 [json_name = "location"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setXpr($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->xpr = $var;

        return $this;
    }
}
