<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CollateExpr</code>
 */
class CollateExpr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
     */
    protected $xpr = null;
    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 2 [json_name = "arg"];</code>
     */
    protected $arg = null;
    /**
     * Generated from protobuf field <code>uint32 coll_oid = 3 [json_name = "collOid"];</code>
     */
    protected $coll_oid = 0;
    /**
     * Generated from protobuf field <code>int32 location = 4 [json_name = "location"];</code>
     */
    protected $location = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $xpr
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $arg
     *     @type int $coll_oid
     *     @type int $location
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getXpr()
    {
        return $this->xpr;
    }

    public function hasXpr()
    {
        return isset($this->xpr);
    }

    public function clearXpr()
    {
        unset($this->xpr);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setXpr(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->xpr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 2 [json_name = "arg"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getArg()
    {
        return $this->arg;
    }

    public function hasArg()
    {
        return isset($this->arg);
    }

    public function clearArg()
    {
        unset($this->arg);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 2 [json_name = "arg"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setArg(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->arg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 coll_oid = 3 [json_name = "collOid"];</code>
     * @return int
     */
    public function getCollOid()
    {
        return $this->coll_oid;
    }

    /**
     * Generated from protobuf field <code>uint32 coll_oid = 3 [json_name = "collOid"];</code>
     * @param int $var
     * @return $this
     */
    public function setCollOid(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->coll_oid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 4 [json_name = "location"];</code>
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>int32 location = 4 [json_name = "location"];</code>
     * @param int $var
     * @return $this
     */
    public function setLocation(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

}

