<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CompositeTypeStmt</code>
 */
class CompositeTypeStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.RangeVar typevar = 1 [json_name = "typevar"];</code>
     */
    protected $typevar = null;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node coldeflist = 2 [json_name = "coldeflist"];</code>
     */
    private $coldeflist;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\RangeVar $typevar
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $coldeflist
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar typevar = 1 [json_name = "typevar"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\RangeVar|null
     */
    public function getTypevar()
    {
        return $this->typevar;
    }

    public function hasTypevar()
    {
        return isset($this->typevar);
    }

    public function clearTypevar()
    {
        unset($this->typevar);
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar typevar = 1 [json_name = "typevar"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\RangeVar $var
     * @return $this
     */
    public function setTypevar(\Flow\PostgreSql\Protobuf\AST\RangeVar|null $var)
    {
        $this->typevar = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node coldeflist = 2 [json_name = "coldeflist"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getColdeflist()
    {
        return $this->coldeflist;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node coldeflist = 2 [json_name = "coldeflist"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setColdeflist(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->coldeflist = $arr;

        return $this;
    }

}

