<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CreateEventTrigStmt</code>.
 */
class CreateEventTrigStmt extends Message
{
    /**
     * Generated from protobuf field <code>string eventname = 2 [json_name = "eventname"];</code>.
     */
    protected $eventname = '';

    /**
     * Generated from protobuf field <code>string trigname = 1 [json_name = "trigname"];</code>.
     */
    protected $trigname = '';

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node funcname = 4 [json_name = "funcname"];</code>.
     */
    private $funcname;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node whenclause = 3 [json_name = "whenclause"];</code>.
     */
    private $whenclause;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var string $trigname
     * @var string $eventname
     * @var array<Node> $whenclause
     * @var array<Node> $funcname
     *                  }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string eventname = 2 [json_name = "eventname"];</code>.
     *
     * @return string
     */
    public function getEventname()
    {
        return $this->eventname;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node funcname = 4 [json_name = "funcname"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getFuncname()
    {
        return $this->funcname;
    }

    /**
     * Generated from protobuf field <code>string trigname = 1 [json_name = "trigname"];</code>.
     *
     * @return string
     */
    public function getTrigname()
    {
        return $this->trigname;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node whenclause = 3 [json_name = "whenclause"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getWhenclause()
    {
        return $this->whenclause;
    }

    /**
     * Generated from protobuf field <code>string eventname = 2 [json_name = "eventname"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setEventname($var)
    {
        GPBUtil::checkString($var, true);
        $this->eventname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node funcname = 4 [json_name = "funcname"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setFuncname($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->funcname = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trigname = 1 [json_name = "trigname"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setTrigname($var)
    {
        GPBUtil::checkString($var, true);
        $this->trigname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node whenclause = 3 [json_name = "whenclause"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setWhenclause($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->whenclause = $arr;

        return $this;
    }
}
