<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CreateStatsStmt</code>
 */
class CreateStatsStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node defnames = 1 [json_name = "defnames"];</code>
     */
    private $defnames;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node stat_types = 2 [json_name = "stat_types"];</code>
     */
    private $stat_types;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node exprs = 3 [json_name = "exprs"];</code>
     */
    private $exprs;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node relations = 4 [json_name = "relations"];</code>
     */
    private $relations;
    /**
     * Generated from protobuf field <code>string stxcomment = 5 [json_name = "stxcomment"];</code>
     */
    protected $stxcomment = '';
    /**
     * Generated from protobuf field <code>bool transformed = 6 [json_name = "transformed"];</code>
     */
    protected $transformed = false;
    /**
     * Generated from protobuf field <code>bool if_not_exists = 7 [json_name = "if_not_exists"];</code>
     */
    protected $if_not_exists = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $defnames
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $stat_types
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $exprs
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $relations
     *     @type string $stxcomment
     *     @type bool $transformed
     *     @type bool $if_not_exists
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node defnames = 1 [json_name = "defnames"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getDefnames()
    {
        return $this->defnames;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node defnames = 1 [json_name = "defnames"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setDefnames(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->defnames = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node stat_types = 2 [json_name = "stat_types"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getStatTypes()
    {
        return $this->stat_types;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node stat_types = 2 [json_name = "stat_types"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setStatTypes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->stat_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node exprs = 3 [json_name = "exprs"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getExprs()
    {
        return $this->exprs;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node exprs = 3 [json_name = "exprs"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setExprs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->exprs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node relations = 4 [json_name = "relations"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getRelations()
    {
        return $this->relations;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node relations = 4 [json_name = "relations"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setRelations(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->relations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stxcomment = 5 [json_name = "stxcomment"];</code>
     * @return string
     */
    public function getStxcomment()
    {
        return $this->stxcomment;
    }

    /**
     * Generated from protobuf field <code>string stxcomment = 5 [json_name = "stxcomment"];</code>
     * @param string $var
     * @return $this
     */
    public function setStxcomment(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->stxcomment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool transformed = 6 [json_name = "transformed"];</code>
     * @return bool
     */
    public function getTransformed()
    {
        return $this->transformed;
    }

    /**
     * Generated from protobuf field <code>bool transformed = 6 [json_name = "transformed"];</code>
     * @param bool $var
     * @return $this
     */
    public function setTransformed(bool $var)
    {
        $this->transformed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool if_not_exists = 7 [json_name = "if_not_exists"];</code>
     * @return bool
     */
    public function getIfNotExists()
    {
        return $this->if_not_exists;
    }

    /**
     * Generated from protobuf field <code>bool if_not_exists = 7 [json_name = "if_not_exists"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIfNotExists(bool $var)
    {
        $this->if_not_exists = $var;

        return $this;
    }

}

