<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CreateTrigStmt</code>.
 */
class CreateTrigStmt extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.RangeVar constrrel = 15 [json_name = "constrrel"];</code>.
     */
    protected $constrrel;

    /**
     * Generated from protobuf field <code>bool deferrable = 13 [json_name = "deferrable"];</code>.
     */
    protected $deferrable = false;

    /**
     * Generated from protobuf field <code>int32 events = 9 [json_name = "events"];</code>.
     */
    protected $events = 0;

    /**
     * Generated from protobuf field <code>bool initdeferred = 14 [json_name = "initdeferred"];</code>.
     */
    protected $initdeferred = false;

    /**
     * Generated from protobuf field <code>bool isconstraint = 2 [json_name = "isconstraint"];</code>.
     */
    protected $isconstraint = false;

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 4 [json_name = "relation"];</code>.
     */
    protected $relation;

    /**
     * Generated from protobuf field <code>bool replace = 1 [json_name = "replace"];</code>.
     */
    protected $replace = false;

    /**
     * Generated from protobuf field <code>bool row = 7 [json_name = "row"];</code>.
     */
    protected $row = false;

    /**
     * Generated from protobuf field <code>int32 timing = 8 [json_name = "timing"];</code>.
     */
    protected $timing = 0;

    /**
     * Generated from protobuf field <code>string trigname = 3 [json_name = "trigname"];</code>.
     */
    protected $trigname = '';

    /**
     * Generated from protobuf field <code>.pg_query.Node when_clause = 11 [json_name = "whenClause"];</code>.
     */
    protected $when_clause;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 6 [json_name = "args"];</code>.
     */
    private $args;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node columns = 10 [json_name = "columns"];</code>.
     */
    private $columns;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node funcname = 5 [json_name = "funcname"];</code>.
     */
    private $funcname;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node transition_rels = 12 [json_name = "transitionRels"];</code>.
     */
    private $transition_rels;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var bool $replace
     * @var bool $isconstraint
     * @var string $trigname
     * @var RangeVar $relation
     * @var array<Node> $funcname
     * @var array<Node> $args
     * @var bool $row
     * @var int $timing
     * @var int $events
     * @var array<Node> $columns
     * @var Node $when_clause
     * @var array<Node> $transition_rels
     * @var bool $deferrable
     * @var bool $initdeferred
     * @var RangeVar $constrrel
     *               }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearConstrrel() : void
    {
        $this->constrrel = null;
    }

    public function clearRelation() : void
    {
        $this->relation = null;
    }

    public function clearWhenClause() : void
    {
        $this->when_clause = null;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 6 [json_name = "args"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node columns = 10 [json_name = "columns"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar constrrel = 15 [json_name = "constrrel"];</code>.
     *
     * @return null|RangeVar
     */
    public function getConstrrel()
    {
        return $this->constrrel;
    }

    /**
     * Generated from protobuf field <code>bool deferrable = 13 [json_name = "deferrable"];</code>.
     *
     * @return bool
     */
    public function getDeferrable()
    {
        return $this->deferrable;
    }

    /**
     * Generated from protobuf field <code>int32 events = 9 [json_name = "events"];</code>.
     *
     * @return int
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node funcname = 5 [json_name = "funcname"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getFuncname()
    {
        return $this->funcname;
    }

    /**
     * Generated from protobuf field <code>bool initdeferred = 14 [json_name = "initdeferred"];</code>.
     *
     * @return bool
     */
    public function getInitdeferred()
    {
        return $this->initdeferred;
    }

    /**
     * Generated from protobuf field <code>bool isconstraint = 2 [json_name = "isconstraint"];</code>.
     *
     * @return bool
     */
    public function getIsconstraint()
    {
        return $this->isconstraint;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 4 [json_name = "relation"];</code>.
     *
     * @return null|RangeVar
     */
    public function getRelation()
    {
        return $this->relation;
    }

    /**
     * Generated from protobuf field <code>bool replace = 1 [json_name = "replace"];</code>.
     *
     * @return bool
     */
    public function getReplace()
    {
        return $this->replace;
    }

    /**
     * Generated from protobuf field <code>bool row = 7 [json_name = "row"];</code>.
     *
     * @return bool
     */
    public function getRow()
    {
        return $this->row;
    }

    /**
     * Generated from protobuf field <code>int32 timing = 8 [json_name = "timing"];</code>.
     *
     * @return int
     */
    public function getTiming()
    {
        return $this->timing;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node transition_rels = 12 [json_name = "transitionRels"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getTransitionRels()
    {
        return $this->transition_rels;
    }

    /**
     * Generated from protobuf field <code>string trigname = 3 [json_name = "trigname"];</code>.
     *
     * @return string
     */
    public function getTrigname()
    {
        return $this->trigname;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node when_clause = 11 [json_name = "whenClause"];</code>.
     *
     * @return null|Node
     */
    public function getWhenClause()
    {
        return $this->when_clause;
    }

    public function hasConstrrel()
    {
        return isset($this->constrrel);
    }

    public function hasRelation()
    {
        return isset($this->relation);
    }

    public function hasWhenClause()
    {
        return isset($this->when_clause);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 6 [json_name = "args"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->args = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node columns = 10 [json_name = "columns"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setColumns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->columns = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar constrrel = 15 [json_name = "constrrel"];</code>.
     *
     * @param RangeVar $var
     *
     * @return $this
     */
    public function setConstrrel($var)
    {
        GPBUtil::checkMessage($var, RangeVar::class);
        $this->constrrel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool deferrable = 13 [json_name = "deferrable"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setDeferrable($var)
    {
        GPBUtil::checkBool($var);
        $this->deferrable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 events = 9 [json_name = "events"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setEvents($var)
    {
        GPBUtil::checkInt32($var);
        $this->events = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node funcname = 5 [json_name = "funcname"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setFuncname($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->funcname = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool initdeferred = 14 [json_name = "initdeferred"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setInitdeferred($var)
    {
        GPBUtil::checkBool($var);
        $this->initdeferred = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isconstraint = 2 [json_name = "isconstraint"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setIsconstraint($var)
    {
        GPBUtil::checkBool($var);
        $this->isconstraint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 4 [json_name = "relation"];</code>.
     *
     * @param RangeVar $var
     *
     * @return $this
     */
    public function setRelation($var)
    {
        GPBUtil::checkMessage($var, RangeVar::class);
        $this->relation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool replace = 1 [json_name = "replace"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setReplace($var)
    {
        GPBUtil::checkBool($var);
        $this->replace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool row = 7 [json_name = "row"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setRow($var)
    {
        GPBUtil::checkBool($var);
        $this->row = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 timing = 8 [json_name = "timing"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setTiming($var)
    {
        GPBUtil::checkInt32($var);
        $this->timing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node transition_rels = 12 [json_name = "transitionRels"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setTransitionRels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->transition_rels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trigname = 3 [json_name = "trigname"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setTrigname($var)
    {
        GPBUtil::checkString($var, true);
        $this->trigname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node when_clause = 11 [json_name = "whenClause"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setWhenClause($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->when_clause = $var;

        return $this;
    }
}
