<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CreateOpClassStmt</code>
 */
class CreateOpClassStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node opclassname = 1 [json_name = "opclassname"];</code>
     */
    private $opclassname;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node opfamilyname = 2 [json_name = "opfamilyname"];</code>
     */
    private $opfamilyname;
    /**
     * Generated from protobuf field <code>string amname = 3 [json_name = "amname"];</code>
     */
    protected $amname = '';
    /**
     * Generated from protobuf field <code>.pg_query.TypeName datatype = 4 [json_name = "datatype"];</code>
     */
    protected $datatype = null;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node items = 5 [json_name = "items"];</code>
     */
    private $items;
    /**
     * Generated from protobuf field <code>bool is_default = 6 [json_name = "isDefault"];</code>
     */
    protected $is_default = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $opclassname
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $opfamilyname
     *     @type string $amname
     *     @type \Flow\PostgreSql\Protobuf\AST\TypeName $datatype
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $items
     *     @type bool $is_default
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node opclassname = 1 [json_name = "opclassname"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getOpclassname()
    {
        return $this->opclassname;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node opclassname = 1 [json_name = "opclassname"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setOpclassname(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->opclassname = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node opfamilyname = 2 [json_name = "opfamilyname"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getOpfamilyname()
    {
        return $this->opfamilyname;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node opfamilyname = 2 [json_name = "opfamilyname"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setOpfamilyname(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->opfamilyname = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string amname = 3 [json_name = "amname"];</code>
     * @return string
     */
    public function getAmname()
    {
        return $this->amname;
    }

    /**
     * Generated from protobuf field <code>string amname = 3 [json_name = "amname"];</code>
     * @param string $var
     * @return $this
     */
    public function setAmname(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->amname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.TypeName datatype = 4 [json_name = "datatype"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\TypeName|null
     */
    public function getDatatype()
    {
        return $this->datatype;
    }

    public function hasDatatype()
    {
        return isset($this->datatype);
    }

    public function clearDatatype()
    {
        unset($this->datatype);
    }

    /**
     * Generated from protobuf field <code>.pg_query.TypeName datatype = 4 [json_name = "datatype"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\TypeName $var
     * @return $this
     */
    public function setDatatype(\Flow\PostgreSql\Protobuf\AST\TypeName|null $var)
    {
        $this->datatype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node items = 5 [json_name = "items"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node items = 5 [json_name = "items"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setItems(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_default = 6 [json_name = "isDefault"];</code>
     * @return bool
     */
    public function getIsDefault()
    {
        return $this->is_default;
    }

    /**
     * Generated from protobuf field <code>bool is_default = 6 [json_name = "isDefault"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDefault(bool $var)
    {
        $this->is_default = $var;

        return $this;
    }

}

