<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CreateRoleStmt</code>
 */
class CreateRoleStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.RoleStmtType stmt_type = 1 [json_name = "stmt_type"];</code>
     */
    protected $stmt_type = 0;
    /**
     * Generated from protobuf field <code>string role = 2 [json_name = "role"];</code>
     */
    protected $role = '';
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 3 [json_name = "options"];</code>
     */
    private $options;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $stmt_type
     *     @type string $role
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $options
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.RoleStmtType stmt_type = 1 [json_name = "stmt_type"];</code>
     * @return int one of the values in {@see \Flow\PostgreSql\Protobuf\AST\RoleStmtType}
     */
    public function getStmtType()
    {
        return $this->stmt_type;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RoleStmtType stmt_type = 1 [json_name = "stmt_type"];</code>
     * @param int $var one of the values in {@see \Flow\PostgreSql\Protobuf\AST\RoleStmtType}
     * @return $this
     */
    public function setStmtType(int $var)
    {
        GPBUtil::checkEnum($var, \Flow\PostgreSql\Protobuf\AST\RoleStmtType::class);
        $this->stmt_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string role = 2 [json_name = "role"];</code>
     * @return string
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>string role = 2 [json_name = "role"];</code>
     * @param string $var
     * @return $this
     */
    public function setRole(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 3 [json_name = "options"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 3 [json_name = "options"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setOptions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->options = $arr;

        return $this;
    }

}

