<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CreateFdwStmt</code>
 */
class CreateFdwStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string fdwname = 1 [json_name = "fdwname"];</code>
     */
    protected $fdwname = '';
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node func_options = 2 [json_name = "func_options"];</code>
     */
    private $func_options;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 3 [json_name = "options"];</code>
     */
    private $options;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $fdwname
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $func_options
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $options
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string fdwname = 1 [json_name = "fdwname"];</code>
     * @return string
     */
    public function getFdwname()
    {
        return $this->fdwname;
    }

    /**
     * Generated from protobuf field <code>string fdwname = 1 [json_name = "fdwname"];</code>
     * @param string $var
     * @return $this
     */
    public function setFdwname(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->fdwname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node func_options = 2 [json_name = "func_options"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getFuncOptions()
    {
        return $this->func_options;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node func_options = 2 [json_name = "func_options"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setFuncOptions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->func_options = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 3 [json_name = "options"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 3 [json_name = "options"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setOptions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->options = $arr;

        return $this;
    }

}

