<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.CreateExtensionStmt</code>.
 */
class CreateExtensionStmt extends Message
{
    /**
     * Generated from protobuf field <code>string extname = 1 [json_name = "extname"];</code>.
     */
    protected $extname = '';

    /**
     * Generated from protobuf field <code>bool if_not_exists = 2 [json_name = "if_not_exists"];</code>.
     */
    protected $if_not_exists = false;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 3 [json_name = "options"];</code>.
     */
    private $options;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var string $extname
     * @var bool $if_not_exists
     * @var array<Node> $options
     *                  }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string extname = 1 [json_name = "extname"];</code>.
     *
     * @return string
     */
    public function getExtname()
    {
        return $this->extname;
    }

    /**
     * Generated from protobuf field <code>bool if_not_exists = 2 [json_name = "if_not_exists"];</code>.
     *
     * @return bool
     */
    public function getIfNotExists()
    {
        return $this->if_not_exists;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 3 [json_name = "options"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>string extname = 1 [json_name = "extname"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setExtname($var)
    {
        GPBUtil::checkString($var, true);
        $this->extname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool if_not_exists = 2 [json_name = "if_not_exists"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setIfNotExists($var)
    {
        GPBUtil::checkBool($var);
        $this->if_not_exists = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 3 [json_name = "options"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->options = $arr;

        return $this;
    }
}
