<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.DeclareCursorStmt</code>
 */
class DeclareCursorStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string portalname = 1 [json_name = "portalname"];</code>
     */
    protected $portalname = '';
    /**
     * Generated from protobuf field <code>int32 options = 2 [json_name = "options"];</code>
     */
    protected $options = 0;
    /**
     * Generated from protobuf field <code>.pg_query.Node query = 3 [json_name = "query"];</code>
     */
    protected $query = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $portalname
     *     @type int $options
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $query
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string portalname = 1 [json_name = "portalname"];</code>
     * @return string
     */
    public function getPortalname()
    {
        return $this->portalname;
    }

    /**
     * Generated from protobuf field <code>string portalname = 1 [json_name = "portalname"];</code>
     * @param string $var
     * @return $this
     */
    public function setPortalname(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->portalname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 options = 2 [json_name = "options"];</code>
     * @return int
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>int32 options = 2 [json_name = "options"];</code>
     * @param int $var
     * @return $this
     */
    public function setOptions(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node query = 3 [json_name = "query"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getQuery()
    {
        return $this->query;
    }

    public function hasQuery()
    {
        return isset($this->query);
    }

    public function clearQuery()
    {
        unset($this->query);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node query = 3 [json_name = "query"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setQuery(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->query = $var;

        return $this;
    }

}

