<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.DropTableSpaceStmt</code>
 */
class DropTableSpaceStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tablespacename = 1 [json_name = "tablespacename"];</code>
     */
    protected $tablespacename = '';
    /**
     * Generated from protobuf field <code>bool missing_ok = 2 [json_name = "missing_ok"];</code>
     */
    protected $missing_ok = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tablespacename
     *     @type bool $missing_ok
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tablespacename = 1 [json_name = "tablespacename"];</code>
     * @return string
     */
    public function getTablespacename()
    {
        return $this->tablespacename;
    }

    /**
     * Generated from protobuf field <code>string tablespacename = 1 [json_name = "tablespacename"];</code>
     * @param string $var
     * @return $this
     */
    public function setTablespacename(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->tablespacename = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool missing_ok = 2 [json_name = "missing_ok"];</code>
     * @return bool
     */
    public function getMissingOk()
    {
        return $this->missing_ok;
    }

    /**
     * Generated from protobuf field <code>bool missing_ok = 2 [json_name = "missing_ok"];</code>
     * @param bool $var
     * @return $this
     */
    public function setMissingOk(bool $var)
    {
        $this->missing_ok = $var;

        return $this;
    }

}

