<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>pg_query.FieldSelect</code>.
 */
class FieldSelect extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 2 [json_name = "arg"];</code>.
     */
    protected $arg;

    /**
     * Generated from protobuf field <code>int32 fieldnum = 3 [json_name = "fieldnum"];</code>.
     */
    protected $fieldnum = 0;

    /**
     * Generated from protobuf field <code>uint32 resultcollid = 6 [json_name = "resultcollid"];</code>.
     */
    protected $resultcollid = 0;

    /**
     * Generated from protobuf field <code>uint32 resulttype = 4 [json_name = "resulttype"];</code>.
     */
    protected $resulttype = 0;

    /**
     * Generated from protobuf field <code>int32 resulttypmod = 5 [json_name = "resulttypmod"];</code>.
     */
    protected $resulttypmod = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     */
    protected $xpr;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var Node $xpr
     * @var Node $arg
     * @var int $fieldnum
     * @var int $resulttype
     * @var int $resulttypmod
     * @var int $resultcollid
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearArg(): void
    {
        $this->arg = null;
    }

    public function clearXpr(): void
    {
        $this->xpr = null;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 2 [json_name = "arg"];</code>.
     *
     * @return null|Node
     */
    public function getArg()
    {
        return $this->arg;
    }

    /**
     * Generated from protobuf field <code>int32 fieldnum = 3 [json_name = "fieldnum"];</code>.
     *
     * @return int
     */
    public function getFieldnum()
    {
        return $this->fieldnum;
    }

    /**
     * Generated from protobuf field <code>uint32 resultcollid = 6 [json_name = "resultcollid"];</code>.
     *
     * @return int
     */
    public function getResultcollid()
    {
        return $this->resultcollid;
    }

    /**
     * Generated from protobuf field <code>uint32 resulttype = 4 [json_name = "resulttype"];</code>.
     *
     * @return int
     */
    public function getResulttype()
    {
        return $this->resulttype;
    }

    /**
     * Generated from protobuf field <code>int32 resulttypmod = 5 [json_name = "resulttypmod"];</code>.
     *
     * @return int
     */
    public function getResulttypmod()
    {
        return $this->resulttypmod;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @return null|Node
     */
    public function getXpr()
    {
        return $this->xpr;
    }

    public function hasArg()
    {
        return isset($this->arg);
    }

    public function hasXpr()
    {
        return isset($this->xpr);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 2 [json_name = "arg"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setArg($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->arg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 fieldnum = 3 [json_name = "fieldnum"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setFieldnum($var)
    {
        GPBUtil::checkInt32($var);
        $this->fieldnum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 resultcollid = 6 [json_name = "resultcollid"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setResultcollid($var)
    {
        GPBUtil::checkUint32($var);
        $this->resultcollid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 resulttype = 4 [json_name = "resulttype"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setResulttype($var)
    {
        GPBUtil::checkUint32($var);
        $this->resulttype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 resulttypmod = 5 [json_name = "resulttypmod"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setResulttypmod($var)
    {
        GPBUtil::checkInt32($var);
        $this->resulttypmod = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setXpr($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->xpr = $var;

        return $this;
    }
}
