<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.FromExpr</code>
 */
class FromExpr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node fromlist = 1 [json_name = "fromlist"];</code>
     */
    private $fromlist;
    /**
     * Generated from protobuf field <code>.pg_query.Node quals = 2 [json_name = "quals"];</code>
     */
    protected $quals = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $fromlist
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $quals
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node fromlist = 1 [json_name = "fromlist"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getFromlist()
    {
        return $this->fromlist;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node fromlist = 1 [json_name = "fromlist"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setFromlist(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->fromlist = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node quals = 2 [json_name = "quals"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getQuals()
    {
        return $this->quals;
    }

    public function hasQuals()
    {
        return isset($this->quals);
    }

    public function clearQuals()
    {
        unset($this->quals);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node quals = 2 [json_name = "quals"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setQuals(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->quals = $var;

        return $this;
    }

}

