<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.FuncCall</code>
 */
class FuncCall extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    private $funcname;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    private $args;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    private $agg_order;
    /**
     * Generated from protobuf field <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
     */
    protected $agg_filter = null;
    /**
     * Generated from protobuf field <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
     */
    protected $over = null;
    /**
     * Generated from protobuf field <code>bool agg_within_group = 6 [json_name = "agg_within_group"];</code>
     */
    protected $agg_within_group = false;
    /**
     * Generated from protobuf field <code>bool agg_star = 7 [json_name = "agg_star"];</code>
     */
    protected $agg_star = false;
    /**
     * Generated from protobuf field <code>bool agg_distinct = 8 [json_name = "agg_distinct"];</code>
     */
    protected $agg_distinct = false;
    /**
     * Generated from protobuf field <code>bool func_variadic = 9 [json_name = "func_variadic"];</code>
     */
    protected $func_variadic = false;
    /**
     * Generated from protobuf field <code>.pg_query.CoercionForm funcformat = 10 [json_name = "funcformat"];</code>
     */
    protected $funcformat = 0;
    /**
     * Generated from protobuf field <code>int32 location = 11 [json_name = "location"];</code>
     */
    protected $location = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $funcname
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $args
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $agg_order
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $agg_filter
     *     @type \Flow\PostgreSql\Protobuf\AST\WindowDef $over
     *     @type bool $agg_within_group
     *     @type bool $agg_star
     *     @type bool $agg_distinct
     *     @type bool $func_variadic
     *     @type int $funcformat
     *     @type int $location
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getFuncname()
    {
        return $this->funcname;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setFuncname(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->funcname = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setArgs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->args = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getAggOrder()
    {
        return $this->agg_order;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setAggOrder(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->agg_order = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getAggFilter()
    {
        return $this->agg_filter;
    }

    public function hasAggFilter()
    {
        return isset($this->agg_filter);
    }

    public function clearAggFilter()
    {
        unset($this->agg_filter);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setAggFilter(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->agg_filter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\WindowDef|null
     */
    public function getOver()
    {
        return $this->over;
    }

    public function hasOver()
    {
        return isset($this->over);
    }

    public function clearOver()
    {
        unset($this->over);
    }

    /**
     * Generated from protobuf field <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\WindowDef $var
     * @return $this
     */
    public function setOver(\Flow\PostgreSql\Protobuf\AST\WindowDef|null $var)
    {
        $this->over = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool agg_within_group = 6 [json_name = "agg_within_group"];</code>
     * @return bool
     */
    public function getAggWithinGroup()
    {
        return $this->agg_within_group;
    }

    /**
     * Generated from protobuf field <code>bool agg_within_group = 6 [json_name = "agg_within_group"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAggWithinGroup(bool $var)
    {
        $this->agg_within_group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool agg_star = 7 [json_name = "agg_star"];</code>
     * @return bool
     */
    public function getAggStar()
    {
        return $this->agg_star;
    }

    /**
     * Generated from protobuf field <code>bool agg_star = 7 [json_name = "agg_star"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAggStar(bool $var)
    {
        $this->agg_star = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool agg_distinct = 8 [json_name = "agg_distinct"];</code>
     * @return bool
     */
    public function getAggDistinct()
    {
        return $this->agg_distinct;
    }

    /**
     * Generated from protobuf field <code>bool agg_distinct = 8 [json_name = "agg_distinct"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAggDistinct(bool $var)
    {
        $this->agg_distinct = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool func_variadic = 9 [json_name = "func_variadic"];</code>
     * @return bool
     */
    public function getFuncVariadic()
    {
        return $this->func_variadic;
    }

    /**
     * Generated from protobuf field <code>bool func_variadic = 9 [json_name = "func_variadic"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFuncVariadic(bool $var)
    {
        $this->func_variadic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.CoercionForm funcformat = 10 [json_name = "funcformat"];</code>
     * @return int one of the values in {@see \Flow\PostgreSql\Protobuf\AST\CoercionForm}
     */
    public function getFuncformat()
    {
        return $this->funcformat;
    }

    /**
     * Generated from protobuf field <code>.pg_query.CoercionForm funcformat = 10 [json_name = "funcformat"];</code>
     * @param int $var one of the values in {@see \Flow\PostgreSql\Protobuf\AST\CoercionForm}
     * @return $this
     */
    public function setFuncformat(int $var)
    {
        GPBUtil::checkEnum($var, \Flow\PostgreSql\Protobuf\AST\CoercionForm::class);
        $this->funcformat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 11 [json_name = "location"];</code>
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>int32 location = 11 [json_name = "location"];</code>
     * @param int $var
     * @return $this
     */
    public function setLocation(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

}

