<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.Integer</code>
 */
class Integer extends \Google\Protobuf\Internal\Message
{
    /**
     * machine integer 
     *
     * Generated from protobuf field <code>int32 ival = 1;</code>
     */
    protected $ival = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ival
     *           machine integer 
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * machine integer 
     *
     * Generated from protobuf field <code>int32 ival = 1;</code>
     * @return int
     */
    public function getIval()
    {
        return $this->ival;
    }

    /**
     * machine integer 
     *
     * Generated from protobuf field <code>int32 ival = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIval(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->ival = $var;

        return $this;
    }

}

