<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.JoinExpr</code>.
 */
class JoinExpr extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Alias alias = 8 [json_name = "alias"];</code>.
     */
    protected $alias;

    /**
     * Generated from protobuf field <code>bool is_natural = 2 [json_name = "isNatural"];</code>.
     */
    protected $is_natural = false;

    /**
     * Generated from protobuf field <code>.pg_query.Alias join_using_alias = 6 [json_name = "join_using_alias"];</code>.
     */
    protected $join_using_alias;

    /**
     * Generated from protobuf field <code>.pg_query.JoinType jointype = 1 [json_name = "jointype"];</code>.
     */
    protected $jointype = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Node larg = 3 [json_name = "larg"];</code>.
     */
    protected $larg;

    /**
     * Generated from protobuf field <code>.pg_query.Node quals = 7 [json_name = "quals"];</code>.
     */
    protected $quals;

    /**
     * Generated from protobuf field <code>.pg_query.Node rarg = 4 [json_name = "rarg"];</code>.
     */
    protected $rarg;

    /**
     * Generated from protobuf field <code>int32 rtindex = 9 [json_name = "rtindex"];</code>.
     */
    protected $rtindex = 0;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node using_clause = 5 [json_name = "usingClause"];</code>.
     */
    private $using_clause;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $jointype
     * @var bool $is_natural
     * @var Node $larg
     * @var Node $rarg
     * @var array<Node> $using_clause
     * @var Alias $join_using_alias
     * @var Node $quals
     * @var Alias $alias
     * @var int $rtindex
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearAlias(): void
    {
        $this->alias = null;
    }

    public function clearJoinUsingAlias(): void
    {
        $this->join_using_alias = null;
    }

    public function clearLarg(): void
    {
        $this->larg = null;
    }

    public function clearQuals(): void
    {
        $this->quals = null;
    }

    public function clearRarg(): void
    {
        $this->rarg = null;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Alias alias = 8 [json_name = "alias"];</code>.
     *
     * @return null|Alias
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Generated from protobuf field <code>bool is_natural = 2 [json_name = "isNatural"];</code>.
     *
     * @return bool
     */
    public function getIsNatural()
    {
        return $this->is_natural;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JoinType jointype = 1 [json_name = "jointype"];</code>.
     *
     * @return int
     */
    public function getJointype()
    {
        return $this->jointype;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Alias join_using_alias = 6 [json_name = "join_using_alias"];</code>.
     *
     * @return null|Alias
     */
    public function getJoinUsingAlias()
    {
        return $this->join_using_alias;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node larg = 3 [json_name = "larg"];</code>.
     *
     * @return null|Node
     */
    public function getLarg()
    {
        return $this->larg;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node quals = 7 [json_name = "quals"];</code>.
     *
     * @return null|Node
     */
    public function getQuals()
    {
        return $this->quals;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node rarg = 4 [json_name = "rarg"];</code>.
     *
     * @return null|Node
     */
    public function getRarg()
    {
        return $this->rarg;
    }

    /**
     * Generated from protobuf field <code>int32 rtindex = 9 [json_name = "rtindex"];</code>.
     *
     * @return int
     */
    public function getRtindex()
    {
        return $this->rtindex;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node using_clause = 5 [json_name = "usingClause"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getUsingClause()
    {
        return $this->using_clause;
    }

    public function hasAlias()
    {
        return isset($this->alias);
    }

    public function hasJoinUsingAlias()
    {
        return isset($this->join_using_alias);
    }

    public function hasLarg()
    {
        return isset($this->larg);
    }

    public function hasQuals()
    {
        return isset($this->quals);
    }

    public function hasRarg()
    {
        return isset($this->rarg);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Alias alias = 8 [json_name = "alias"];</code>.
     *
     * @param Alias $var
     *
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkMessage($var, Alias::class);
        $this->alias = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_natural = 2 [json_name = "isNatural"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setIsNatural($var)
    {
        GPBUtil::checkBool($var);
        $this->is_natural = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JoinType jointype = 1 [json_name = "jointype"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setJointype($var)
    {
        GPBUtil::checkEnum($var, JoinType::class);
        $this->jointype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Alias join_using_alias = 6 [json_name = "join_using_alias"];</code>.
     *
     * @param Alias $var
     *
     * @return $this
     */
    public function setJoinUsingAlias($var)
    {
        GPBUtil::checkMessage($var, Alias::class);
        $this->join_using_alias = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node larg = 3 [json_name = "larg"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setLarg($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->larg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node quals = 7 [json_name = "quals"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setQuals($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->quals = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node rarg = 4 [json_name = "rarg"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setRarg($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->rarg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rtindex = 9 [json_name = "rtindex"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setRtindex($var)
    {
        GPBUtil::checkInt32($var);
        $this->rtindex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node using_clause = 5 [json_name = "usingClause"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setUsingClause($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->using_clause = $arr;

        return $this;
    }
}
