<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use UnexpectedValueException;

/**
 * Protobuf type <code>pg_query.JsonBehaviorType</code>
 */
class JsonBehaviorType
{
    /**
     * Generated from protobuf enum <code>JSON_BEHAVIOR_TYPE_UNDEFINED = 0;</code>
     */
    const JSON_BEHAVIOR_TYPE_UNDEFINED = 0;
    /**
     * Generated from protobuf enum <code>JSON_BEHAVIOR_NULL = 1;</code>
     */
    const JSON_BEHAVIOR_NULL = 1;
    /**
     * Generated from protobuf enum <code>JSON_BEHAVIOR_ERROR = 2;</code>
     */
    const JSON_BEHAVIOR_ERROR = 2;
    /**
     * Generated from protobuf enum <code>JSON_BEHAVIOR_EMPTY = 3;</code>
     */
    const JSON_BEHAVIOR_EMPTY = 3;
    /**
     * Generated from protobuf enum <code>JSON_BEHAVIOR_TRUE = 4;</code>
     */
    const JSON_BEHAVIOR_TRUE = 4;
    /**
     * Generated from protobuf enum <code>JSON_BEHAVIOR_FALSE = 5;</code>
     */
    const JSON_BEHAVIOR_FALSE = 5;
    /**
     * Generated from protobuf enum <code>JSON_BEHAVIOR_UNKNOWN = 6;</code>
     */
    const JSON_BEHAVIOR_UNKNOWN = 6;
    /**
     * Generated from protobuf enum <code>JSON_BEHAVIOR_EMPTY_ARRAY = 7;</code>
     */
    const JSON_BEHAVIOR_EMPTY_ARRAY = 7;
    /**
     * Generated from protobuf enum <code>JSON_BEHAVIOR_EMPTY_OBJECT = 8;</code>
     */
    const JSON_BEHAVIOR_EMPTY_OBJECT = 8;
    /**
     * Generated from protobuf enum <code>JSON_BEHAVIOR_DEFAULT = 9;</code>
     */
    const JSON_BEHAVIOR_DEFAULT = 9;

    private static $valueToName = [
        self::JSON_BEHAVIOR_TYPE_UNDEFINED => 'JSON_BEHAVIOR_TYPE_UNDEFINED',
        self::JSON_BEHAVIOR_NULL => 'JSON_BEHAVIOR_NULL',
        self::JSON_BEHAVIOR_ERROR => 'JSON_BEHAVIOR_ERROR',
        self::JSON_BEHAVIOR_EMPTY => 'JSON_BEHAVIOR_EMPTY',
        self::JSON_BEHAVIOR_TRUE => 'JSON_BEHAVIOR_TRUE',
        self::JSON_BEHAVIOR_FALSE => 'JSON_BEHAVIOR_FALSE',
        self::JSON_BEHAVIOR_UNKNOWN => 'JSON_BEHAVIOR_UNKNOWN',
        self::JSON_BEHAVIOR_EMPTY_ARRAY => 'JSON_BEHAVIOR_EMPTY_ARRAY',
        self::JSON_BEHAVIOR_EMPTY_OBJECT => 'JSON_BEHAVIOR_EMPTY_OBJECT',
        self::JSON_BEHAVIOR_DEFAULT => 'JSON_BEHAVIOR_DEFAULT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

