<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.JsonTable</code>.
 */
class JsonTable extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>.
     */
    protected $alias;

    /**
     * Generated from protobuf field <code>.pg_query.JsonValueExpr context_item = 1 [json_name = "context_item"];</code>.
     */
    protected $context_item;

    /**
     * Generated from protobuf field <code>bool lateral = 7 [json_name = "lateral"];</code>.
     */
    protected $lateral = false;

    /**
     * Generated from protobuf field <code>int32 location = 8 [json_name = "location"];</code>.
     */
    protected $location = 0;

    /**
     * Generated from protobuf field <code>.pg_query.JsonBehavior on_error = 5 [json_name = "on_error"];</code>.
     */
    protected $on_error;

    /**
     * Generated from protobuf field <code>.pg_query.JsonTablePathSpec pathspec = 2 [json_name = "pathspec"];</code>.
     */
    protected $pathspec;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node columns = 4 [json_name = "columns"];</code>.
     */
    private $columns;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node passing = 3 [json_name = "passing"];</code>.
     */
    private $passing;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var JsonValueExpr $context_item
     * @var JsonTablePathSpec $pathspec
     * @var array<Node> $passing
     * @var array<Node> $columns
     * @var JsonBehavior $on_error
     * @var Alias $alias
     * @var bool $lateral
     * @var int $location
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearAlias(): void
    {
        $this->alias = null;
    }

    public function clearContextItem(): void
    {
        $this->context_item = null;
    }

    public function clearOnError(): void
    {
        $this->on_error = null;
    }

    public function clearPathspec(): void
    {
        $this->pathspec = null;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>.
     *
     * @return null|Alias
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node columns = 4 [json_name = "columns"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonValueExpr context_item = 1 [json_name = "context_item"];</code>.
     *
     * @return null|JsonValueExpr
     */
    public function getContextItem()
    {
        return $this->context_item;
    }

    /**
     * Generated from protobuf field <code>bool lateral = 7 [json_name = "lateral"];</code>.
     *
     * @return bool
     */
    public function getLateral()
    {
        return $this->lateral;
    }

    /**
     * Generated from protobuf field <code>int32 location = 8 [json_name = "location"];</code>.
     *
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonBehavior on_error = 5 [json_name = "on_error"];</code>.
     *
     * @return null|JsonBehavior
     */
    public function getOnError()
    {
        return $this->on_error;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node passing = 3 [json_name = "passing"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getPassing()
    {
        return $this->passing;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonTablePathSpec pathspec = 2 [json_name = "pathspec"];</code>.
     *
     * @return null|JsonTablePathSpec
     */
    public function getPathspec()
    {
        return $this->pathspec;
    }

    public function hasAlias()
    {
        return isset($this->alias);
    }

    public function hasContextItem()
    {
        return isset($this->context_item);
    }

    public function hasOnError()
    {
        return isset($this->on_error);
    }

    public function hasPathspec()
    {
        return isset($this->pathspec);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>.
     *
     * @param Alias $var
     *
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkMessage($var, Alias::class);
        $this->alias = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node columns = 4 [json_name = "columns"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setColumns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->columns = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonValueExpr context_item = 1 [json_name = "context_item"];</code>.
     *
     * @param JsonValueExpr $var
     *
     * @return $this
     */
    public function setContextItem($var)
    {
        GPBUtil::checkMessage($var, JsonValueExpr::class);
        $this->context_item = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool lateral = 7 [json_name = "lateral"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setLateral($var)
    {
        GPBUtil::checkBool($var);
        $this->lateral = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 8 [json_name = "location"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonBehavior on_error = 5 [json_name = "on_error"];</code>.
     *
     * @param JsonBehavior $var
     *
     * @return $this
     */
    public function setOnError($var)
    {
        GPBUtil::checkMessage($var, JsonBehavior::class);
        $this->on_error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node passing = 3 [json_name = "passing"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setPassing($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->passing = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonTablePathSpec pathspec = 2 [json_name = "pathspec"];</code>.
     *
     * @param JsonTablePathSpec $var
     *
     * @return $this
     */
    public function setPathspec($var)
    {
        GPBUtil::checkMessage($var, JsonTablePathSpec::class);
        $this->pathspec = $var;

        return $this;
    }
}
