<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.JsonFuncExpr</code>.
 */
class JsonFuncExpr extends Message
{
    /**
     * Generated from protobuf field <code>string column_name = 2 [json_name = "column_name"];</code>.
     */
    protected $column_name = '';

    /**
     * Generated from protobuf field <code>.pg_query.JsonValueExpr context_item = 3 [json_name = "context_item"];</code>.
     */
    protected $context_item;

    /**
     * Generated from protobuf field <code>int32 location = 11 [json_name = "location"];</code>.
     */
    protected $location = 0;

    /**
     * Generated from protobuf field <code>.pg_query.JsonBehavior on_empty = 7 [json_name = "on_empty"];</code>.
     */
    protected $on_empty;

    /**
     * Generated from protobuf field <code>.pg_query.JsonBehavior on_error = 8 [json_name = "on_error"];</code>.
     */
    protected $on_error;

    /**
     * Generated from protobuf field <code>.pg_query.JsonExprOp op = 1 [json_name = "op"];</code>.
     */
    protected $op = 0;

    /**
     * Generated from protobuf field <code>.pg_query.JsonOutput output = 6 [json_name = "output"];</code>.
     */
    protected $output;

    /**
     * Generated from protobuf field <code>.pg_query.Node pathspec = 4 [json_name = "pathspec"];</code>.
     */
    protected $pathspec;

    /**
     * Generated from protobuf field <code>.pg_query.JsonQuotes quotes = 10 [json_name = "quotes"];</code>.
     */
    protected $quotes = 0;

    /**
     * Generated from protobuf field <code>.pg_query.JsonWrapper wrapper = 9 [json_name = "wrapper"];</code>.
     */
    protected $wrapper = 0;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node passing = 5 [json_name = "passing"];</code>.
     */
    private $passing;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $op
     * @var string $column_name
     * @var JsonValueExpr $context_item
     * @var Node $pathspec
     * @var array<Node> $passing
     * @var JsonOutput $output
     * @var JsonBehavior $on_empty
     * @var JsonBehavior $on_error
     * @var int $wrapper
     * @var int $quotes
     * @var int $location
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearContextItem() : void
    {
        $this->context_item = null;
    }

    public function clearOnEmpty() : void
    {
        $this->on_empty = null;
    }

    public function clearOnError() : void
    {
        $this->on_error = null;
    }

    public function clearOutput() : void
    {
        $this->output = null;
    }

    public function clearPathspec() : void
    {
        $this->pathspec = null;
    }

    /**
     * Generated from protobuf field <code>string column_name = 2 [json_name = "column_name"];</code>.
     *
     * @return string
     */
    public function getColumnName()
    {
        return $this->column_name;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonValueExpr context_item = 3 [json_name = "context_item"];</code>.
     *
     * @return null|JsonValueExpr
     */
    public function getContextItem()
    {
        return $this->context_item;
    }

    /**
     * Generated from protobuf field <code>int32 location = 11 [json_name = "location"];</code>.
     *
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonBehavior on_empty = 7 [json_name = "on_empty"];</code>.
     *
     * @return null|JsonBehavior
     */
    public function getOnEmpty()
    {
        return $this->on_empty;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonBehavior on_error = 8 [json_name = "on_error"];</code>.
     *
     * @return null|JsonBehavior
     */
    public function getOnError()
    {
        return $this->on_error;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonExprOp op = 1 [json_name = "op"];</code>.
     *
     * @return int
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonOutput output = 6 [json_name = "output"];</code>.
     *
     * @return null|JsonOutput
     */
    public function getOutput()
    {
        return $this->output;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node passing = 5 [json_name = "passing"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getPassing()
    {
        return $this->passing;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node pathspec = 4 [json_name = "pathspec"];</code>.
     *
     * @return null|Node
     */
    public function getPathspec()
    {
        return $this->pathspec;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonQuotes quotes = 10 [json_name = "quotes"];</code>.
     *
     * @return int
     */
    public function getQuotes()
    {
        return $this->quotes;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonWrapper wrapper = 9 [json_name = "wrapper"];</code>.
     *
     * @return int
     */
    public function getWrapper()
    {
        return $this->wrapper;
    }

    public function hasContextItem()
    {
        return isset($this->context_item);
    }

    public function hasOnEmpty()
    {
        return isset($this->on_empty);
    }

    public function hasOnError()
    {
        return isset($this->on_error);
    }

    public function hasOutput()
    {
        return isset($this->output);
    }

    public function hasPathspec()
    {
        return isset($this->pathspec);
    }

    /**
     * Generated from protobuf field <code>string column_name = 2 [json_name = "column_name"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setColumnName($var)
    {
        GPBUtil::checkString($var, true);
        $this->column_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonValueExpr context_item = 3 [json_name = "context_item"];</code>.
     *
     * @param JsonValueExpr $var
     *
     * @return $this
     */
    public function setContextItem($var)
    {
        GPBUtil::checkMessage($var, JsonValueExpr::class);
        $this->context_item = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 11 [json_name = "location"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonBehavior on_empty = 7 [json_name = "on_empty"];</code>.
     *
     * @param JsonBehavior $var
     *
     * @return $this
     */
    public function setOnEmpty($var)
    {
        GPBUtil::checkMessage($var, JsonBehavior::class);
        $this->on_empty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonBehavior on_error = 8 [json_name = "on_error"];</code>.
     *
     * @param JsonBehavior $var
     *
     * @return $this
     */
    public function setOnError($var)
    {
        GPBUtil::checkMessage($var, JsonBehavior::class);
        $this->on_error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonExprOp op = 1 [json_name = "op"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkEnum($var, JsonExprOp::class);
        $this->op = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonOutput output = 6 [json_name = "output"];</code>.
     *
     * @param JsonOutput $var
     *
     * @return $this
     */
    public function setOutput($var)
    {
        GPBUtil::checkMessage($var, JsonOutput::class);
        $this->output = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node passing = 5 [json_name = "passing"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setPassing($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->passing = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node pathspec = 4 [json_name = "pathspec"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setPathspec($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->pathspec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonQuotes quotes = 10 [json_name = "quotes"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setQuotes($var)
    {
        GPBUtil::checkEnum($var, JsonQuotes::class);
        $this->quotes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonWrapper wrapper = 9 [json_name = "wrapper"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setWrapper($var)
    {
        GPBUtil::checkEnum($var, JsonWrapper::class);
        $this->wrapper = $var;

        return $this;
    }
}
