<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

/**
 * Protobuf type <code>pg_query.JsonValueType</code>.
 */
class JsonValueType
{
    /**
     * Generated from protobuf enum <code>JS_TYPE_ANY = 1;</code>.
     */
    public const JS_TYPE_ANY = 1;

    /**
     * Generated from protobuf enum <code>JS_TYPE_ARRAY = 3;</code>.
     */
    public const JS_TYPE_ARRAY = 3;

    /**
     * Generated from protobuf enum <code>JS_TYPE_OBJECT = 2;</code>.
     */
    public const JS_TYPE_OBJECT = 2;

    /**
     * Generated from protobuf enum <code>JS_TYPE_SCALAR = 4;</code>.
     */
    public const JS_TYPE_SCALAR = 4;

    /**
     * Generated from protobuf enum <code>JSON_VALUE_TYPE_UNDEFINED = 0;</code>.
     */
    public const JSON_VALUE_TYPE_UNDEFINED = 0;

    private static $valueToName = [
        self::JSON_VALUE_TYPE_UNDEFINED => 'JSON_VALUE_TYPE_UNDEFINED',
        self::JS_TYPE_ANY => 'JS_TYPE_ANY',
        self::JS_TYPE_OBJECT => 'JS_TYPE_OBJECT',
        self::JS_TYPE_ARRAY => 'JS_TYPE_ARRAY',
        self::JS_TYPE_SCALAR => 'JS_TYPE_SCALAR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value,
            ));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string) $name);

        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name,
            ));
        }

        return constant($const);
    }
}
