<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.JsonTableSiblingJoin</code>
 */
class JsonTableSiblingJoin extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Node plan = 1 [json_name = "plan"];</code>
     */
    protected $plan = null;
    /**
     * Generated from protobuf field <code>.pg_query.Node lplan = 2 [json_name = "lplan"];</code>
     */
    protected $lplan = null;
    /**
     * Generated from protobuf field <code>.pg_query.Node rplan = 3 [json_name = "rplan"];</code>
     */
    protected $rplan = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $plan
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $lplan
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $rplan
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node plan = 1 [json_name = "plan"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getPlan()
    {
        return $this->plan;
    }

    public function hasPlan()
    {
        return isset($this->plan);
    }

    public function clearPlan()
    {
        unset($this->plan);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node plan = 1 [json_name = "plan"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setPlan(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->plan = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node lplan = 2 [json_name = "lplan"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getLplan()
    {
        return $this->lplan;
    }

    public function hasLplan()
    {
        return isset($this->lplan);
    }

    public function clearLplan()
    {
        unset($this->lplan);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node lplan = 2 [json_name = "lplan"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setLplan(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->lplan = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node rplan = 3 [json_name = "rplan"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getRplan()
    {
        return $this->rplan;
    }

    public function hasRplan()
    {
        return isset($this->rplan);
    }

    public function clearRplan()
    {
        unset($this->rplan);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node rplan = 3 [json_name = "rplan"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setRplan(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->rplan = $var;

        return $this;
    }

}

