<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.JsonParseExpr</code>
 */
class JsonParseExpr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.JsonValueExpr expr = 1 [json_name = "expr"];</code>
     */
    protected $expr = null;
    /**
     * Generated from protobuf field <code>.pg_query.JsonOutput output = 2 [json_name = "output"];</code>
     */
    protected $output = null;
    /**
     * Generated from protobuf field <code>bool unique_keys = 3 [json_name = "unique_keys"];</code>
     */
    protected $unique_keys = false;
    /**
     * Generated from protobuf field <code>int32 location = 4 [json_name = "location"];</code>
     */
    protected $location = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\JsonValueExpr $expr
     *     @type \Flow\PostgreSql\Protobuf\AST\JsonOutput $output
     *     @type bool $unique_keys
     *     @type int $location
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonValueExpr expr = 1 [json_name = "expr"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\JsonValueExpr|null
     */
    public function getExpr()
    {
        return $this->expr;
    }

    public function hasExpr()
    {
        return isset($this->expr);
    }

    public function clearExpr()
    {
        unset($this->expr);
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonValueExpr expr = 1 [json_name = "expr"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\JsonValueExpr $var
     * @return $this
     */
    public function setExpr(\Flow\PostgreSql\Protobuf\AST\JsonValueExpr|null $var)
    {
        $this->expr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonOutput output = 2 [json_name = "output"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\JsonOutput|null
     */
    public function getOutput()
    {
        return $this->output;
    }

    public function hasOutput()
    {
        return isset($this->output);
    }

    public function clearOutput()
    {
        unset($this->output);
    }

    /**
     * Generated from protobuf field <code>.pg_query.JsonOutput output = 2 [json_name = "output"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\JsonOutput $var
     * @return $this
     */
    public function setOutput(\Flow\PostgreSql\Protobuf\AST\JsonOutput|null $var)
    {
        $this->output = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool unique_keys = 3 [json_name = "unique_keys"];</code>
     * @return bool
     */
    public function getUniqueKeys()
    {
        return $this->unique_keys;
    }

    /**
     * Generated from protobuf field <code>bool unique_keys = 3 [json_name = "unique_keys"];</code>
     * @param bool $var
     * @return $this
     */
    public function setUniqueKeys(bool $var)
    {
        $this->unique_keys = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 4 [json_name = "location"];</code>
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>int32 location = 4 [json_name = "location"];</code>
     * @param int $var
     * @return $this
     */
    public function setLocation(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

}

