<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>pg_query.LoadStmt</code>.
 */
class LoadStmt extends Message
{
    /**
     * Generated from protobuf field <code>string filename = 1 [json_name = "filename"];</code>.
     */
    protected $filename = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var string $filename
     *             }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string filename = 1 [json_name = "filename"];</code>.
     *
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Generated from protobuf field <code>string filename = 1 [json_name = "filename"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setFilename($var)
    {
        GPBUtil::checkString($var, true);
        $this->filename = $var;

        return $this;
    }
}
