<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use UnexpectedValueException;

/**
 * Protobuf type <code>pg_query.LockTupleMode</code>
 */
class LockTupleMode
{
    /**
     * Generated from protobuf enum <code>LOCK_TUPLE_MODE_UNDEFINED = 0;</code>
     */
    const LOCK_TUPLE_MODE_UNDEFINED = 0;
    /**
     * Generated from protobuf enum <code>LockTupleKeyShare = 1;</code>
     */
    const LockTupleKeyShare = 1;
    /**
     * Generated from protobuf enum <code>LockTupleShare = 2;</code>
     */
    const LockTupleShare = 2;
    /**
     * Generated from protobuf enum <code>LockTupleNoKeyExclusive = 3;</code>
     */
    const LockTupleNoKeyExclusive = 3;
    /**
     * Generated from protobuf enum <code>LockTupleExclusive = 4;</code>
     */
    const LockTupleExclusive = 4;

    private static $valueToName = [
        self::LOCK_TUPLE_MODE_UNDEFINED => 'LOCK_TUPLE_MODE_UNDEFINED',
        self::LockTupleKeyShare => 'LockTupleKeyShare',
        self::LockTupleShare => 'LockTupleShare',
        self::LockTupleNoKeyExclusive => 'LockTupleNoKeyExclusive',
        self::LockTupleExclusive => 'LockTupleExclusive',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

