<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.MergeStmt</code>.
 */
class MergeStmt extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Node join_condition = 3 [json_name = "joinCondition"];</code>.
     */
    protected $join_condition;

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 1 [json_name = "relation"];</code>.
     */
    protected $relation;

    /**
     * Generated from protobuf field <code>.pg_query.Node source_relation = 2 [json_name = "sourceRelation"];</code>.
     */
    protected $source_relation;

    /**
     * Generated from protobuf field <code>.pg_query.WithClause with_clause = 6 [json_name = "withClause"];</code>.
     */
    protected $with_clause;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node merge_when_clauses = 4 [json_name = "mergeWhenClauses"];</code>.
     */
    private $merge_when_clauses;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node returning_list = 5 [json_name = "returningList"];</code>.
     */
    private $returning_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var RangeVar $relation
     * @var Node $source_relation
     * @var Node $join_condition
     * @var array<Node> $merge_when_clauses
     * @var array<Node> $returning_list
     * @var WithClause $with_clause
     *                 }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearJoinCondition(): void
    {
        $this->join_condition = null;
    }

    public function clearRelation(): void
    {
        $this->relation = null;
    }

    public function clearSourceRelation(): void
    {
        $this->source_relation = null;
    }

    public function clearWithClause(): void
    {
        $this->with_clause = null;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node join_condition = 3 [json_name = "joinCondition"];</code>.
     *
     * @return null|Node
     */
    public function getJoinCondition()
    {
        return $this->join_condition;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node merge_when_clauses = 4 [json_name = "mergeWhenClauses"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getMergeWhenClauses()
    {
        return $this->merge_when_clauses;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 1 [json_name = "relation"];</code>.
     *
     * @return null|RangeVar
     */
    public function getRelation()
    {
        return $this->relation;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node returning_list = 5 [json_name = "returningList"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getReturningList()
    {
        return $this->returning_list;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node source_relation = 2 [json_name = "sourceRelation"];</code>.
     *
     * @return null|Node
     */
    public function getSourceRelation()
    {
        return $this->source_relation;
    }

    /**
     * Generated from protobuf field <code>.pg_query.WithClause with_clause = 6 [json_name = "withClause"];</code>.
     *
     * @return null|WithClause
     */
    public function getWithClause()
    {
        return $this->with_clause;
    }

    public function hasJoinCondition()
    {
        return isset($this->join_condition);
    }

    public function hasRelation()
    {
        return isset($this->relation);
    }

    public function hasSourceRelation()
    {
        return isset($this->source_relation);
    }

    public function hasWithClause()
    {
        return isset($this->with_clause);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node join_condition = 3 [json_name = "joinCondition"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setJoinCondition($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->join_condition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node merge_when_clauses = 4 [json_name = "mergeWhenClauses"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setMergeWhenClauses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->merge_when_clauses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 1 [json_name = "relation"];</code>.
     *
     * @param RangeVar $var
     *
     * @return $this
     */
    public function setRelation($var)
    {
        GPBUtil::checkMessage($var, RangeVar::class);
        $this->relation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node returning_list = 5 [json_name = "returningList"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setReturningList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->returning_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node source_relation = 2 [json_name = "sourceRelation"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setSourceRelation($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->source_relation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.WithClause with_clause = 6 [json_name = "withClause"];</code>.
     *
     * @param WithClause $var
     *
     * @return $this
     */
    public function setWithClause($var)
    {
        GPBUtil::checkMessage($var, WithClause::class);
        $this->with_clause = $var;

        return $this;
    }
}
