<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.MergeWhenClause</code>.
 */
class MergeWhenClause extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.CmdType command_type = 2 [json_name = "commandType"];</code>.
     */
    protected $command_type = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Node condition = 4 [json_name = "condition"];</code>.
     */
    protected $condition;

    /**
     * Generated from protobuf field <code>.pg_query.MergeMatchKind match_kind = 1 [json_name = "matchKind"];</code>.
     */
    protected $match_kind = 0;

    /**
     * Generated from protobuf field <code>.pg_query.OverridingKind override = 3 [json_name = "override"];</code>.
     */
    protected $override = 0;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node target_list = 5 [json_name = "targetList"];</code>.
     */
    private $target_list;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node values = 6 [json_name = "values"];</code>.
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $match_kind
     * @var int $command_type
     * @var int $override
     * @var Node $condition
     * @var array<Node> $target_list
     * @var array<Node> $values
     *                  }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearCondition(): void
    {
        $this->condition = null;
    }

    /**
     * Generated from protobuf field <code>.pg_query.CmdType command_type = 2 [json_name = "commandType"];</code>.
     *
     * @return int
     */
    public function getCommandType()
    {
        return $this->command_type;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node condition = 4 [json_name = "condition"];</code>.
     *
     * @return null|Node
     */
    public function getCondition()
    {
        return $this->condition;
    }

    /**
     * Generated from protobuf field <code>.pg_query.MergeMatchKind match_kind = 1 [json_name = "matchKind"];</code>.
     *
     * @return int
     */
    public function getMatchKind()
    {
        return $this->match_kind;
    }

    /**
     * Generated from protobuf field <code>.pg_query.OverridingKind override = 3 [json_name = "override"];</code>.
     *
     * @return int
     */
    public function getOverride()
    {
        return $this->override;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node target_list = 5 [json_name = "targetList"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getTargetList()
    {
        return $this->target_list;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node values = 6 [json_name = "values"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getValues()
    {
        return $this->values;
    }

    public function hasCondition()
    {
        return isset($this->condition);
    }

    /**
     * Generated from protobuf field <code>.pg_query.CmdType command_type = 2 [json_name = "commandType"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setCommandType($var)
    {
        GPBUtil::checkEnum($var, CmdType::class);
        $this->command_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node condition = 4 [json_name = "condition"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setCondition($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->condition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.MergeMatchKind match_kind = 1 [json_name = "matchKind"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setMatchKind($var)
    {
        GPBUtil::checkEnum($var, MergeMatchKind::class);
        $this->match_kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.OverridingKind override = 3 [json_name = "override"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setOverride($var)
    {
        GPBUtil::checkEnum($var, OverridingKind::class);
        $this->override = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node target_list = 5 [json_name = "targetList"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setTargetList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->target_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node values = 6 [json_name = "values"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->values = $arr;

        return $this;
    }
}
