<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.MergeWhenClause</code>
 */
class MergeWhenClause extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.MergeMatchKind match_kind = 1 [json_name = "matchKind"];</code>
     */
    protected $match_kind = 0;
    /**
     * Generated from protobuf field <code>.pg_query.CmdType command_type = 2 [json_name = "commandType"];</code>
     */
    protected $command_type = 0;
    /**
     * Generated from protobuf field <code>.pg_query.OverridingKind override = 3 [json_name = "override"];</code>
     */
    protected $override = 0;
    /**
     * Generated from protobuf field <code>.pg_query.Node condition = 4 [json_name = "condition"];</code>
     */
    protected $condition = null;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node target_list = 5 [json_name = "targetList"];</code>
     */
    private $target_list;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node values = 6 [json_name = "values"];</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $match_kind
     *     @type int $command_type
     *     @type int $override
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $condition
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $target_list
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $values
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.MergeMatchKind match_kind = 1 [json_name = "matchKind"];</code>
     * @return int one of the values in {@see \Flow\PostgreSql\Protobuf\AST\MergeMatchKind}
     */
    public function getMatchKind()
    {
        return $this->match_kind;
    }

    /**
     * Generated from protobuf field <code>.pg_query.MergeMatchKind match_kind = 1 [json_name = "matchKind"];</code>
     * @param int $var one of the values in {@see \Flow\PostgreSql\Protobuf\AST\MergeMatchKind}
     * @return $this
     */
    public function setMatchKind(int $var)
    {
        GPBUtil::checkEnum($var, \Flow\PostgreSql\Protobuf\AST\MergeMatchKind::class);
        $this->match_kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.CmdType command_type = 2 [json_name = "commandType"];</code>
     * @return int one of the values in {@see \Flow\PostgreSql\Protobuf\AST\CmdType}
     */
    public function getCommandType()
    {
        return $this->command_type;
    }

    /**
     * Generated from protobuf field <code>.pg_query.CmdType command_type = 2 [json_name = "commandType"];</code>
     * @param int $var one of the values in {@see \Flow\PostgreSql\Protobuf\AST\CmdType}
     * @return $this
     */
    public function setCommandType(int $var)
    {
        GPBUtil::checkEnum($var, \Flow\PostgreSql\Protobuf\AST\CmdType::class);
        $this->command_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.OverridingKind override = 3 [json_name = "override"];</code>
     * @return int one of the values in {@see \Flow\PostgreSql\Protobuf\AST\OverridingKind}
     */
    public function getOverride()
    {
        return $this->override;
    }

    /**
     * Generated from protobuf field <code>.pg_query.OverridingKind override = 3 [json_name = "override"];</code>
     * @param int $var one of the values in {@see \Flow\PostgreSql\Protobuf\AST\OverridingKind}
     * @return $this
     */
    public function setOverride(int $var)
    {
        GPBUtil::checkEnum($var, \Flow\PostgreSql\Protobuf\AST\OverridingKind::class);
        $this->override = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node condition = 4 [json_name = "condition"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getCondition()
    {
        return $this->condition;
    }

    public function hasCondition()
    {
        return isset($this->condition);
    }

    public function clearCondition()
    {
        unset($this->condition);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node condition = 4 [json_name = "condition"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setCondition(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->condition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node target_list = 5 [json_name = "targetList"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getTargetList()
    {
        return $this->target_list;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node target_list = 5 [json_name = "targetList"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setTargetList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->target_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node values = 6 [json_name = "values"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node values = 6 [json_name = "values"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setValues(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->values = $arr;

        return $this;
    }

}

