<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.MinMaxExpr</code>.
 */
class MinMaxExpr extends Message
{
    /**
     * Generated from protobuf field <code>uint32 inputcollid = 4 [json_name = "inputcollid"];</code>.
     */
    protected $inputcollid = 0;

    /**
     * Generated from protobuf field <code>int32 location = 7 [json_name = "location"];</code>.
     */
    protected $location = 0;

    /**
     * Generated from protobuf field <code>uint32 minmaxcollid = 3 [json_name = "minmaxcollid"];</code>.
     */
    protected $minmaxcollid = 0;

    /**
     * Generated from protobuf field <code>uint32 minmaxtype = 2 [json_name = "minmaxtype"];</code>.
     */
    protected $minmaxtype = 0;

    /**
     * Generated from protobuf field <code>.pg_query.MinMaxOp op = 5 [json_name = "op"];</code>.
     */
    protected $op = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     */
    protected $xpr;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 6 [json_name = "args"];</code>.
     */
    private $args;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var Node $xpr
     * @var int $minmaxtype
     * @var int $minmaxcollid
     * @var int $inputcollid
     * @var int $op
     * @var array<Node> $args
     * @var int $location
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearXpr(): void
    {
        $this->xpr = null;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 6 [json_name = "args"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Generated from protobuf field <code>uint32 inputcollid = 4 [json_name = "inputcollid"];</code>.
     *
     * @return int
     */
    public function getInputcollid()
    {
        return $this->inputcollid;
    }

    /**
     * Generated from protobuf field <code>int32 location = 7 [json_name = "location"];</code>.
     *
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>uint32 minmaxcollid = 3 [json_name = "minmaxcollid"];</code>.
     *
     * @return int
     */
    public function getMinmaxcollid()
    {
        return $this->minmaxcollid;
    }

    /**
     * Generated from protobuf field <code>uint32 minmaxtype = 2 [json_name = "minmaxtype"];</code>.
     *
     * @return int
     */
    public function getMinmaxtype()
    {
        return $this->minmaxtype;
    }

    /**
     * Generated from protobuf field <code>.pg_query.MinMaxOp op = 5 [json_name = "op"];</code>.
     *
     * @return int
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @return null|Node
     */
    public function getXpr()
    {
        return $this->xpr;
    }

    public function hasXpr()
    {
        return isset($this->xpr);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 6 [json_name = "args"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->args = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 inputcollid = 4 [json_name = "inputcollid"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setInputcollid($var)
    {
        GPBUtil::checkUint32($var);
        $this->inputcollid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 7 [json_name = "location"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 minmaxcollid = 3 [json_name = "minmaxcollid"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setMinmaxcollid($var)
    {
        GPBUtil::checkUint32($var);
        $this->minmaxcollid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 minmaxtype = 2 [json_name = "minmaxtype"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setMinmaxtype($var)
    {
        GPBUtil::checkUint32($var);
        $this->minmaxtype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.MinMaxOp op = 5 [json_name = "op"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkEnum($var, MinMaxOp::class);
        $this->op = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setXpr($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->xpr = $var;

        return $this;
    }
}
