<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.NullTest</code>
 */
class NullTest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
     */
    protected $xpr = null;
    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 2 [json_name = "arg"];</code>
     */
    protected $arg = null;
    /**
     * Generated from protobuf field <code>.pg_query.NullTestType nulltesttype = 3 [json_name = "nulltesttype"];</code>
     */
    protected $nulltesttype = 0;
    /**
     * Generated from protobuf field <code>bool argisrow = 4 [json_name = "argisrow"];</code>
     */
    protected $argisrow = false;
    /**
     * Generated from protobuf field <code>int32 location = 5 [json_name = "location"];</code>
     */
    protected $location = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $xpr
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $arg
     *     @type int $nulltesttype
     *     @type bool $argisrow
     *     @type int $location
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getXpr()
    {
        return $this->xpr;
    }

    public function hasXpr()
    {
        return isset($this->xpr);
    }

    public function clearXpr()
    {
        unset($this->xpr);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setXpr(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->xpr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 2 [json_name = "arg"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getArg()
    {
        return $this->arg;
    }

    public function hasArg()
    {
        return isset($this->arg);
    }

    public function clearArg()
    {
        unset($this->arg);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node arg = 2 [json_name = "arg"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setArg(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->arg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.NullTestType nulltesttype = 3 [json_name = "nulltesttype"];</code>
     * @return int one of the values in {@see \Flow\PostgreSql\Protobuf\AST\NullTestType}
     */
    public function getNulltesttype()
    {
        return $this->nulltesttype;
    }

    /**
     * Generated from protobuf field <code>.pg_query.NullTestType nulltesttype = 3 [json_name = "nulltesttype"];</code>
     * @param int $var one of the values in {@see \Flow\PostgreSql\Protobuf\AST\NullTestType}
     * @return $this
     */
    public function setNulltesttype(int $var)
    {
        GPBUtil::checkEnum($var, \Flow\PostgreSql\Protobuf\AST\NullTestType::class);
        $this->nulltesttype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool argisrow = 4 [json_name = "argisrow"];</code>
     * @return bool
     */
    public function getArgisrow()
    {
        return $this->argisrow;
    }

    /**
     * Generated from protobuf field <code>bool argisrow = 4 [json_name = "argisrow"];</code>
     * @param bool $var
     * @return $this
     */
    public function setArgisrow(bool $var)
    {
        $this->argisrow = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 5 [json_name = "location"];</code>
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>int32 location = 5 [json_name = "location"];</code>
     * @param int $var
     * @return $this
     */
    public function setLocation(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

}

