<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.OnConflictClause</code>.
 */
class OnConflictClause extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.OnConflictAction action = 1 [json_name = "action"];</code>.
     */
    protected $action = 0;

    /**
     * Generated from protobuf field <code>.pg_query.InferClause infer = 2 [json_name = "infer"];</code>.
     */
    protected $infer;

    /**
     * Generated from protobuf field <code>int32 location = 5 [json_name = "location"];</code>.
     */
    protected $location = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Node where_clause = 4 [json_name = "whereClause"];</code>.
     */
    protected $where_clause;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node target_list = 3 [json_name = "targetList"];</code>.
     */
    private $target_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $action
     * @var InferClause $infer
     * @var array<Node> $target_list
     * @var Node $where_clause
     * @var int $location
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearInfer() : void
    {
        $this->infer = null;
    }

    public function clearWhereClause() : void
    {
        $this->where_clause = null;
    }

    /**
     * Generated from protobuf field <code>.pg_query.OnConflictAction action = 1 [json_name = "action"];</code>.
     *
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>.pg_query.InferClause infer = 2 [json_name = "infer"];</code>.
     *
     * @return null|InferClause
     */
    public function getInfer()
    {
        return $this->infer;
    }

    /**
     * Generated from protobuf field <code>int32 location = 5 [json_name = "location"];</code>.
     *
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node target_list = 3 [json_name = "targetList"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getTargetList()
    {
        return $this->target_list;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node where_clause = 4 [json_name = "whereClause"];</code>.
     *
     * @return null|Node
     */
    public function getWhereClause()
    {
        return $this->where_clause;
    }

    public function hasInfer()
    {
        return isset($this->infer);
    }

    public function hasWhereClause()
    {
        return isset($this->where_clause);
    }

    /**
     * Generated from protobuf field <code>.pg_query.OnConflictAction action = 1 [json_name = "action"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, OnConflictAction::class);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.InferClause infer = 2 [json_name = "infer"];</code>.
     *
     * @param InferClause $var
     *
     * @return $this
     */
    public function setInfer($var)
    {
        GPBUtil::checkMessage($var, InferClause::class);
        $this->infer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 5 [json_name = "location"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node target_list = 3 [json_name = "targetList"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setTargetList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->target_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node where_clause = 4 [json_name = "whereClause"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setWhereClause($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->where_clause = $var;

        return $this;
    }
}
