<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

/**
 * Protobuf type <code>pg_query.OnCommitAction</code>.
 */
class OnCommitAction
{
    /**
     * Generated from protobuf enum <code>ON_COMMIT_ACTION_UNDEFINED = 0;</code>.
     */
    public const ON_COMMIT_ACTION_UNDEFINED = 0;

    /**
     * Generated from protobuf enum <code>ONCOMMIT_DELETE_ROWS = 3;</code>.
     */
    public const ONCOMMIT_DELETE_ROWS = 3;

    /**
     * Generated from protobuf enum <code>ONCOMMIT_DROP = 4;</code>.
     */
    public const ONCOMMIT_DROP = 4;

    /**
     * Generated from protobuf enum <code>ONCOMMIT_NOOP = 1;</code>.
     */
    public const ONCOMMIT_NOOP = 1;

    /**
     * Generated from protobuf enum <code>ONCOMMIT_PRESERVE_ROWS = 2;</code>.
     */
    public const ONCOMMIT_PRESERVE_ROWS = 2;

    private static $valueToName = [
        self::ON_COMMIT_ACTION_UNDEFINED => 'ON_COMMIT_ACTION_UNDEFINED',
        self::ONCOMMIT_NOOP => 'ONCOMMIT_NOOP',
        self::ONCOMMIT_PRESERVE_ROWS => 'ONCOMMIT_PRESERVE_ROWS',
        self::ONCOMMIT_DELETE_ROWS => 'ONCOMMIT_DELETE_ROWS',
        self::ONCOMMIT_DROP => 'ONCOMMIT_DROP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value,
            ));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string) $name);

        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name,
            ));
        }

        return constant($const);
    }
}
