<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>pg_query.Param</code>.
 */
class Param extends Message
{
    /**
     * Generated from protobuf field <code>int32 location = 7 [json_name = "location"];</code>.
     */
    protected $location = 0;

    /**
     * Generated from protobuf field <code>uint32 paramcollid = 6 [json_name = "paramcollid"];</code>.
     */
    protected $paramcollid = 0;

    /**
     * Generated from protobuf field <code>int32 paramid = 3 [json_name = "paramid"];</code>.
     */
    protected $paramid = 0;

    /**
     * Generated from protobuf field <code>.pg_query.ParamKind paramkind = 2 [json_name = "paramkind"];</code>.
     */
    protected $paramkind = 0;

    /**
     * Generated from protobuf field <code>uint32 paramtype = 4 [json_name = "paramtype"];</code>.
     */
    protected $paramtype = 0;

    /**
     * Generated from protobuf field <code>int32 paramtypmod = 5 [json_name = "paramtypmod"];</code>.
     */
    protected $paramtypmod = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     */
    protected $xpr;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var Node $xpr
     * @var int $paramkind
     * @var int $paramid
     * @var int $paramtype
     * @var int $paramtypmod
     * @var int $paramcollid
     * @var int $location
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearXpr(): void
    {
        $this->xpr = null;
    }

    /**
     * Generated from protobuf field <code>int32 location = 7 [json_name = "location"];</code>.
     *
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>uint32 paramcollid = 6 [json_name = "paramcollid"];</code>.
     *
     * @return int
     */
    public function getParamcollid()
    {
        return $this->paramcollid;
    }

    /**
     * Generated from protobuf field <code>int32 paramid = 3 [json_name = "paramid"];</code>.
     *
     * @return int
     */
    public function getParamid()
    {
        return $this->paramid;
    }

    /**
     * Generated from protobuf field <code>.pg_query.ParamKind paramkind = 2 [json_name = "paramkind"];</code>.
     *
     * @return int
     */
    public function getParamkind()
    {
        return $this->paramkind;
    }

    /**
     * Generated from protobuf field <code>uint32 paramtype = 4 [json_name = "paramtype"];</code>.
     *
     * @return int
     */
    public function getParamtype()
    {
        return $this->paramtype;
    }

    /**
     * Generated from protobuf field <code>int32 paramtypmod = 5 [json_name = "paramtypmod"];</code>.
     *
     * @return int
     */
    public function getParamtypmod()
    {
        return $this->paramtypmod;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @return null|Node
     */
    public function getXpr()
    {
        return $this->xpr;
    }

    public function hasXpr()
    {
        return isset($this->xpr);
    }

    /**
     * Generated from protobuf field <code>int32 location = 7 [json_name = "location"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 paramcollid = 6 [json_name = "paramcollid"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setParamcollid($var)
    {
        GPBUtil::checkUint32($var);
        $this->paramcollid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 paramid = 3 [json_name = "paramid"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setParamid($var)
    {
        GPBUtil::checkInt32($var);
        $this->paramid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.ParamKind paramkind = 2 [json_name = "paramkind"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setParamkind($var)
    {
        GPBUtil::checkEnum($var, ParamKind::class);
        $this->paramkind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 paramtype = 4 [json_name = "paramtype"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setParamtype($var)
    {
        GPBUtil::checkUint32($var);
        $this->paramtype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 paramtypmod = 5 [json_name = "paramtypmod"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setParamtypmod($var)
    {
        GPBUtil::checkInt32($var);
        $this->paramtypmod = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setXpr($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->xpr = $var;

        return $this;
    }
}
