<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBUtil, Message};

/**
 * Generated from protobuf message <code>pg_query.PartitionRangeDatum</code>.
 */
class PartitionRangeDatum extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.PartitionRangeDatumKind kind = 1 [json_name = "kind"];</code>.
     */
    protected $kind = 0;

    /**
     * Generated from protobuf field <code>int32 location = 3 [json_name = "location"];</code>.
     */
    protected $location = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Node value = 2 [json_name = "value"];</code>.
     */
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $kind
     * @var Node $value
     * @var int $location
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearValue() : void
    {
        $this->value = null;
    }

    /**
     * Generated from protobuf field <code>.pg_query.PartitionRangeDatumKind kind = 1 [json_name = "kind"];</code>.
     *
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>int32 location = 3 [json_name = "location"];</code>.
     *
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node value = 2 [json_name = "value"];</code>.
     *
     * @return null|Node
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    /**
     * Generated from protobuf field <code>.pg_query.PartitionRangeDatumKind kind = 1 [json_name = "kind"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, PartitionRangeDatumKind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 3 [json_name = "location"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node value = 2 [json_name = "value"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->value = $var;

        return $this;
    }
}
