<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

/**
 * Protobuf type <code>pg_query.PartitionRangeDatumKind</code>.
 */
class PartitionRangeDatumKind
{
    /**
     * Generated from protobuf enum <code>PARTITION_RANGE_DATUM_KIND_UNDEFINED = 0;</code>.
     */
    public const PARTITION_RANGE_DATUM_KIND_UNDEFINED = 0;

    /**
     * Generated from protobuf enum <code>PARTITION_RANGE_DATUM_MAXVALUE = 3;</code>.
     */
    public const PARTITION_RANGE_DATUM_MAXVALUE = 3;

    /**
     * Generated from protobuf enum <code>PARTITION_RANGE_DATUM_MINVALUE = 1;</code>.
     */
    public const PARTITION_RANGE_DATUM_MINVALUE = 1;

    /**
     * Generated from protobuf enum <code>PARTITION_RANGE_DATUM_VALUE = 2;</code>.
     */
    public const PARTITION_RANGE_DATUM_VALUE = 2;

    private static $valueToName = [
        self::PARTITION_RANGE_DATUM_KIND_UNDEFINED => 'PARTITION_RANGE_DATUM_KIND_UNDEFINED',
        self::PARTITION_RANGE_DATUM_MINVALUE => 'PARTITION_RANGE_DATUM_MINVALUE',
        self::PARTITION_RANGE_DATUM_VALUE => 'PARTITION_RANGE_DATUM_VALUE',
        self::PARTITION_RANGE_DATUM_MAXVALUE => 'PARTITION_RANGE_DATUM_MAXVALUE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value
            ));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string) $name);

        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name
            ));
        }

        return constant($const);
    }
}
