<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.PartitionBoundSpec</code>
 */
class PartitionBoundSpec extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string strategy = 1 [json_name = "strategy"];</code>
     */
    protected $strategy = '';
    /**
     * Generated from protobuf field <code>bool is_default = 2 [json_name = "is_default"];</code>
     */
    protected $is_default = false;
    /**
     * Generated from protobuf field <code>int32 modulus = 3 [json_name = "modulus"];</code>
     */
    protected $modulus = 0;
    /**
     * Generated from protobuf field <code>int32 remainder = 4 [json_name = "remainder"];</code>
     */
    protected $remainder = 0;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node listdatums = 5 [json_name = "listdatums"];</code>
     */
    private $listdatums;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node lowerdatums = 6 [json_name = "lowerdatums"];</code>
     */
    private $lowerdatums;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node upperdatums = 7 [json_name = "upperdatums"];</code>
     */
    private $upperdatums;
    /**
     * Generated from protobuf field <code>int32 location = 8 [json_name = "location"];</code>
     */
    protected $location = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $strategy
     *     @type bool $is_default
     *     @type int $modulus
     *     @type int $remainder
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $listdatums
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $lowerdatums
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $upperdatums
     *     @type int $location
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string strategy = 1 [json_name = "strategy"];</code>
     * @return string
     */
    public function getStrategy()
    {
        return $this->strategy;
    }

    /**
     * Generated from protobuf field <code>string strategy = 1 [json_name = "strategy"];</code>
     * @param string $var
     * @return $this
     */
    public function setStrategy(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->strategy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_default = 2 [json_name = "is_default"];</code>
     * @return bool
     */
    public function getIsDefault()
    {
        return $this->is_default;
    }

    /**
     * Generated from protobuf field <code>bool is_default = 2 [json_name = "is_default"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDefault(bool $var)
    {
        $this->is_default = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 modulus = 3 [json_name = "modulus"];</code>
     * @return int
     */
    public function getModulus()
    {
        return $this->modulus;
    }

    /**
     * Generated from protobuf field <code>int32 modulus = 3 [json_name = "modulus"];</code>
     * @param int $var
     * @return $this
     */
    public function setModulus(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->modulus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 remainder = 4 [json_name = "remainder"];</code>
     * @return int
     */
    public function getRemainder()
    {
        return $this->remainder;
    }

    /**
     * Generated from protobuf field <code>int32 remainder = 4 [json_name = "remainder"];</code>
     * @param int $var
     * @return $this
     */
    public function setRemainder(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->remainder = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node listdatums = 5 [json_name = "listdatums"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getListdatums()
    {
        return $this->listdatums;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node listdatums = 5 [json_name = "listdatums"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setListdatums(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->listdatums = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node lowerdatums = 6 [json_name = "lowerdatums"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getLowerdatums()
    {
        return $this->lowerdatums;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node lowerdatums = 6 [json_name = "lowerdatums"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setLowerdatums(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->lowerdatums = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node upperdatums = 7 [json_name = "upperdatums"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getUpperdatums()
    {
        return $this->upperdatums;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node upperdatums = 7 [json_name = "upperdatums"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setUpperdatums(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->upperdatums = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 8 [json_name = "location"];</code>
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>int32 location = 8 [json_name = "location"];</code>
     * @param int $var
     * @return $this
     */
    public function setLocation(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

}

