<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.Float</code>
 */
class PBFloat extends \Google\Protobuf\Internal\Message
{
    /**
     * string 
     *
     * Generated from protobuf field <code>string fval = 1;</code>
     */
    protected $fval = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $fval
     *           string 
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * string 
     *
     * Generated from protobuf field <code>string fval = 1;</code>
     * @return string
     */
    public function getFval()
    {
        return $this->fval;
    }

    /**
     * string 
     *
     * Generated from protobuf field <code>string fval = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFval(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->fval = $var;

        return $this;
    }

}

