<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.PrepareStmt</code>
 */
class PrepareStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node argtypes = 2 [json_name = "argtypes"];</code>
     */
    private $argtypes;
    /**
     * Generated from protobuf field <code>.pg_query.Node query = 3 [json_name = "query"];</code>
     */
    protected $query = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $argtypes
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $query
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node argtypes = 2 [json_name = "argtypes"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getArgtypes()
    {
        return $this->argtypes;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node argtypes = 2 [json_name = "argtypes"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setArgtypes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->argtypes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node query = 3 [json_name = "query"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getQuery()
    {
        return $this->query;
    }

    public function hasQuery()
    {
        return isset($this->query);
    }

    public function clearQuery()
    {
        unset($this->query);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node query = 3 [json_name = "query"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setQuery(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->query = $var;

        return $this;
    }

}

