<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use UnexpectedValueException;

/**
 * Protobuf type <code>pg_query.PublicationObjSpecType</code>
 */
class PublicationObjSpecType
{
    /**
     * Generated from protobuf enum <code>PUBLICATION_OBJ_SPEC_TYPE_UNDEFINED = 0;</code>
     */
    const PUBLICATION_OBJ_SPEC_TYPE_UNDEFINED = 0;
    /**
     * Generated from protobuf enum <code>PUBLICATIONOBJ_TABLE = 1;</code>
     */
    const PUBLICATIONOBJ_TABLE = 1;
    /**
     * Generated from protobuf enum <code>PUBLICATIONOBJ_TABLES_IN_SCHEMA = 2;</code>
     */
    const PUBLICATIONOBJ_TABLES_IN_SCHEMA = 2;
    /**
     * Generated from protobuf enum <code>PUBLICATIONOBJ_TABLES_IN_CUR_SCHEMA = 3;</code>
     */
    const PUBLICATIONOBJ_TABLES_IN_CUR_SCHEMA = 3;
    /**
     * Generated from protobuf enum <code>PUBLICATIONOBJ_CONTINUATION = 4;</code>
     */
    const PUBLICATIONOBJ_CONTINUATION = 4;

    private static $valueToName = [
        self::PUBLICATION_OBJ_SPEC_TYPE_UNDEFINED => 'PUBLICATION_OBJ_SPEC_TYPE_UNDEFINED',
        self::PUBLICATIONOBJ_TABLE => 'PUBLICATIONOBJ_TABLE',
        self::PUBLICATIONOBJ_TABLES_IN_SCHEMA => 'PUBLICATIONOBJ_TABLES_IN_SCHEMA',
        self::PUBLICATIONOBJ_TABLES_IN_CUR_SCHEMA => 'PUBLICATIONOBJ_TABLES_IN_CUR_SCHEMA',
        self::PUBLICATIONOBJ_CONTINUATION => 'PUBLICATIONOBJ_CONTINUATION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

