<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.RangeFunction</code>.
 */
class RangeFunction extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Alias alias = 5 [json_name = "alias"];</code>.
     */
    protected $alias;

    /**
     * Generated from protobuf field <code>bool is_rowsfrom = 3 [json_name = "is_rowsfrom"];</code>.
     */
    protected $is_rowsfrom = false;

    /**
     * Generated from protobuf field <code>bool lateral = 1 [json_name = "lateral"];</code>.
     */
    protected $lateral = false;

    /**
     * Generated from protobuf field <code>bool ordinality = 2 [json_name = "ordinality"];</code>.
     */
    protected $ordinality = false;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node coldeflist = 6 [json_name = "coldeflist"];</code>.
     */
    private $coldeflist;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node functions = 4 [json_name = "functions"];</code>.
     */
    private $functions;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var bool $lateral
     * @var bool $ordinality
     * @var bool $is_rowsfrom
     * @var array<Node> $functions
     * @var Alias $alias
     * @var array<Node> $coldeflist
     *                  }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearAlias() : void
    {
        $this->alias = null;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Alias alias = 5 [json_name = "alias"];</code>.
     *
     * @return null|Alias
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node coldeflist = 6 [json_name = "coldeflist"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getColdeflist()
    {
        return $this->coldeflist;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node functions = 4 [json_name = "functions"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getFunctions()
    {
        return $this->functions;
    }

    /**
     * Generated from protobuf field <code>bool is_rowsfrom = 3 [json_name = "is_rowsfrom"];</code>.
     *
     * @return bool
     */
    public function getIsRowsfrom()
    {
        return $this->is_rowsfrom;
    }

    /**
     * Generated from protobuf field <code>bool lateral = 1 [json_name = "lateral"];</code>.
     *
     * @return bool
     */
    public function getLateral()
    {
        return $this->lateral;
    }

    /**
     * Generated from protobuf field <code>bool ordinality = 2 [json_name = "ordinality"];</code>.
     *
     * @return bool
     */
    public function getOrdinality()
    {
        return $this->ordinality;
    }

    public function hasAlias()
    {
        return isset($this->alias);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Alias alias = 5 [json_name = "alias"];</code>.
     *
     * @param Alias $var
     *
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkMessage($var, Alias::class);
        $this->alias = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node coldeflist = 6 [json_name = "coldeflist"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setColdeflist($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->coldeflist = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node functions = 4 [json_name = "functions"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setFunctions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->functions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_rowsfrom = 3 [json_name = "is_rowsfrom"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setIsRowsfrom($var)
    {
        GPBUtil::checkBool($var);
        $this->is_rowsfrom = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool lateral = 1 [json_name = "lateral"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setLateral($var)
    {
        GPBUtil::checkBool($var);
        $this->lateral = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ordinality = 2 [json_name = "ordinality"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setOrdinality($var)
    {
        GPBUtil::checkBool($var);
        $this->ordinality = $var;

        return $this;
    }
}
