<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>pg_query.RoleSpec</code>.
 */
class RoleSpec extends Message
{
    /**
     * Generated from protobuf field <code>int32 location = 3 [json_name = "location"];</code>.
     */
    protected $location = 0;

    /**
     * Generated from protobuf field <code>string rolename = 2 [json_name = "rolename"];</code>.
     */
    protected $rolename = '';

    /**
     * Generated from protobuf field <code>.pg_query.RoleSpecType roletype = 1 [json_name = "roletype"];</code>.
     */
    protected $roletype = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $roletype
     * @var string $rolename
     * @var int $location
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 location = 3 [json_name = "location"];</code>.
     *
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>string rolename = 2 [json_name = "rolename"];</code>.
     *
     * @return string
     */
    public function getRolename()
    {
        return $this->rolename;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RoleSpecType roletype = 1 [json_name = "roletype"];</code>.
     *
     * @return int
     */
    public function getRoletype()
    {
        return $this->roletype;
    }

    /**
     * Generated from protobuf field <code>int32 location = 3 [json_name = "location"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rolename = 2 [json_name = "rolename"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setRolename($var)
    {
        GPBUtil::checkString($var, true);
        $this->rolename = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RoleSpecType roletype = 1 [json_name = "roletype"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setRoletype($var)
    {
        GPBUtil::checkEnum($var, RoleSpecType::class);
        $this->roletype = $var;

        return $this;
    }
}
