<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use UnexpectedValueException;

/**
 * Protobuf type <code>pg_query.RoleStmtType</code>
 */
class RoleStmtType
{
    /**
     * Generated from protobuf enum <code>ROLE_STMT_TYPE_UNDEFINED = 0;</code>
     */
    const ROLE_STMT_TYPE_UNDEFINED = 0;
    /**
     * Generated from protobuf enum <code>ROLESTMT_ROLE = 1;</code>
     */
    const ROLESTMT_ROLE = 1;
    /**
     * Generated from protobuf enum <code>ROLESTMT_USER = 2;</code>
     */
    const ROLESTMT_USER = 2;
    /**
     * Generated from protobuf enum <code>ROLESTMT_GROUP = 3;</code>
     */
    const ROLESTMT_GROUP = 3;

    private static $valueToName = [
        self::ROLE_STMT_TYPE_UNDEFINED => 'ROLE_STMT_TYPE_UNDEFINED',
        self::ROLESTMT_ROLE => 'ROLESTMT_ROLE',
        self::ROLESTMT_USER => 'ROLESTMT_USER',
        self::ROLESTMT_GROUP => 'ROLESTMT_GROUP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

