<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.RowExpr</code>.
 */
class RowExpr extends Message
{
    /**
     * Generated from protobuf field <code>int32 location = 6 [json_name = "location"];</code>.
     */
    protected $location = 0;

    /**
     * Generated from protobuf field <code>.pg_query.CoercionForm row_format = 4 [json_name = "row_format"];</code>.
     */
    protected $row_format = 0;

    /**
     * Generated from protobuf field <code>uint32 row_typeid = 3 [json_name = "row_typeid"];</code>.
     */
    protected $row_typeid = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     */
    protected $xpr;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>.
     */
    private $args;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node colnames = 5 [json_name = "colnames"];</code>.
     */
    private $colnames;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var Node $xpr
     * @var array<Node> $args
     * @var int $row_typeid
     * @var int $row_format
     * @var array<Node> $colnames
     * @var int $location
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearXpr() : void
    {
        $this->xpr = null;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node colnames = 5 [json_name = "colnames"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getColnames()
    {
        return $this->colnames;
    }

    /**
     * Generated from protobuf field <code>int32 location = 6 [json_name = "location"];</code>.
     *
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>.pg_query.CoercionForm row_format = 4 [json_name = "row_format"];</code>.
     *
     * @return int
     */
    public function getRowFormat()
    {
        return $this->row_format;
    }

    /**
     * Generated from protobuf field <code>uint32 row_typeid = 3 [json_name = "row_typeid"];</code>.
     *
     * @return int
     */
    public function getRowTypeid()
    {
        return $this->row_typeid;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @return null|Node
     */
    public function getXpr()
    {
        return $this->xpr;
    }

    public function hasXpr()
    {
        return isset($this->xpr);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->args = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node colnames = 5 [json_name = "colnames"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setColnames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->colnames = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 6 [json_name = "location"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.CoercionForm row_format = 4 [json_name = "row_format"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setRowFormat($var)
    {
        GPBUtil::checkEnum($var, CoercionForm::class);
        $this->row_format = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 row_typeid = 3 [json_name = "row_typeid"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setRowTypeid($var)
    {
        GPBUtil::checkUint32($var);
        $this->row_typeid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setXpr($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->xpr = $var;

        return $this;
    }
}
