<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.RowMarkClause</code>
 */
class RowMarkClause extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 rti = 1 [json_name = "rti"];</code>
     */
    protected $rti = 0;
    /**
     * Generated from protobuf field <code>.pg_query.LockClauseStrength strength = 2 [json_name = "strength"];</code>
     */
    protected $strength = 0;
    /**
     * Generated from protobuf field <code>.pg_query.LockWaitPolicy wait_policy = 3 [json_name = "waitPolicy"];</code>
     */
    protected $wait_policy = 0;
    /**
     * Generated from protobuf field <code>bool pushed_down = 4 [json_name = "pushedDown"];</code>
     */
    protected $pushed_down = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $rti
     *     @type int $strength
     *     @type int $wait_policy
     *     @type bool $pushed_down
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 rti = 1 [json_name = "rti"];</code>
     * @return int
     */
    public function getRti()
    {
        return $this->rti;
    }

    /**
     * Generated from protobuf field <code>uint32 rti = 1 [json_name = "rti"];</code>
     * @param int $var
     * @return $this
     */
    public function setRti(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->rti = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.LockClauseStrength strength = 2 [json_name = "strength"];</code>
     * @return int one of the values in {@see \Flow\PostgreSql\Protobuf\AST\LockClauseStrength}
     */
    public function getStrength()
    {
        return $this->strength;
    }

    /**
     * Generated from protobuf field <code>.pg_query.LockClauseStrength strength = 2 [json_name = "strength"];</code>
     * @param int $var one of the values in {@see \Flow\PostgreSql\Protobuf\AST\LockClauseStrength}
     * @return $this
     */
    public function setStrength(int $var)
    {
        GPBUtil::checkEnum($var, \Flow\PostgreSql\Protobuf\AST\LockClauseStrength::class);
        $this->strength = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.LockWaitPolicy wait_policy = 3 [json_name = "waitPolicy"];</code>
     * @return int one of the values in {@see \Flow\PostgreSql\Protobuf\AST\LockWaitPolicy}
     */
    public function getWaitPolicy()
    {
        return $this->wait_policy;
    }

    /**
     * Generated from protobuf field <code>.pg_query.LockWaitPolicy wait_policy = 3 [json_name = "waitPolicy"];</code>
     * @param int $var one of the values in {@see \Flow\PostgreSql\Protobuf\AST\LockWaitPolicy}
     * @return $this
     */
    public function setWaitPolicy(int $var)
    {
        GPBUtil::checkEnum($var, \Flow\PostgreSql\Protobuf\AST\LockWaitPolicy::class);
        $this->wait_policy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool pushed_down = 4 [json_name = "pushedDown"];</code>
     * @return bool
     */
    public function getPushedDown()
    {
        return $this->pushed_down;
    }

    /**
     * Generated from protobuf field <code>bool pushed_down = 4 [json_name = "pushedDown"];</code>
     * @param bool $var
     * @return $this
     */
    public function setPushedDown(bool $var)
    {
        $this->pushed_down = $var;

        return $this;
    }

}

