<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.RTEPermissionInfo</code>.
 */
class RTEPermissionInfo extends Message
{
    /**
     * Generated from protobuf field <code>uint32 check_as_user = 4 [json_name = "checkAsUser"];</code>.
     */
    protected $check_as_user = 0;

    /**
     * Generated from protobuf field <code>bool inh = 2 [json_name = "inh"];</code>.
     */
    protected $inh = false;

    /**
     * Generated from protobuf field <code>uint32 relid = 1 [json_name = "relid"];</code>.
     */
    protected $relid = 0;

    /**
     * Generated from protobuf field <code>uint64 required_perms = 3 [json_name = "requiredPerms"];</code>.
     */
    protected $required_perms = 0;

    /**
     * Generated from protobuf field <code>repeated uint64 inserted_cols = 6 [json_name = "insertedCols"];</code>.
     */
    private $inserted_cols;

    /**
     * Generated from protobuf field <code>repeated uint64 selected_cols = 5 [json_name = "selectedCols"];</code>.
     */
    private $selected_cols;

    /**
     * Generated from protobuf field <code>repeated uint64 updated_cols = 7 [json_name = "updatedCols"];</code>.
     */
    private $updated_cols;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $relid
     * @var bool $inh
     * @var int|string $required_perms
     * @var int $check_as_user
     * @var array<int>|array<string> $selected_cols
     * @var array<int>|array<string> $inserted_cols
     * @var array<int>|array<string> $updated_cols
     *                               }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 check_as_user = 4 [json_name = "checkAsUser"];</code>.
     *
     * @return int
     */
    public function getCheckAsUser()
    {
        return $this->check_as_user;
    }

    /**
     * Generated from protobuf field <code>bool inh = 2 [json_name = "inh"];</code>.
     *
     * @return bool
     */
    public function getInh()
    {
        return $this->inh;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 inserted_cols = 6 [json_name = "insertedCols"];</code>.
     *
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getInsertedCols()
    {
        return $this->inserted_cols;
    }

    /**
     * Generated from protobuf field <code>uint32 relid = 1 [json_name = "relid"];</code>.
     *
     * @return int
     */
    public function getRelid()
    {
        return $this->relid;
    }

    /**
     * Generated from protobuf field <code>uint64 required_perms = 3 [json_name = "requiredPerms"];</code>.
     *
     * @return int|string
     */
    public function getRequiredPerms()
    {
        return $this->required_perms;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 selected_cols = 5 [json_name = "selectedCols"];</code>.
     *
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getSelectedCols()
    {
        return $this->selected_cols;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 updated_cols = 7 [json_name = "updatedCols"];</code>.
     *
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getUpdatedCols()
    {
        return $this->updated_cols;
    }

    /**
     * Generated from protobuf field <code>uint32 check_as_user = 4 [json_name = "checkAsUser"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setCheckAsUser($var)
    {
        GPBUtil::checkUint32($var);
        $this->check_as_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool inh = 2 [json_name = "inh"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setInh($var)
    {
        GPBUtil::checkBool($var);
        $this->inh = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 inserted_cols = 6 [json_name = "insertedCols"];</code>.
     *
     * @param array<int>|array<string> $var
     *
     * @return $this
     */
    public function setInsertedCols($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT64);
        $this->inserted_cols = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 relid = 1 [json_name = "relid"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setRelid($var)
    {
        GPBUtil::checkUint32($var);
        $this->relid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 required_perms = 3 [json_name = "requiredPerms"];</code>.
     *
     * @param int|string $var
     *
     * @return $this
     */
    public function setRequiredPerms($var)
    {
        GPBUtil::checkUint64($var);
        $this->required_perms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 selected_cols = 5 [json_name = "selectedCols"];</code>.
     *
     * @param array<int>|array<string> $var
     *
     * @return $this
     */
    public function setSelectedCols($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT64);
        $this->selected_cols = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 updated_cols = 7 [json_name = "updatedCols"];</code>.
     *
     * @param array<int>|array<string> $var
     *
     * @return $this
     */
    public function setUpdatedCols($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::UINT64);
        $this->updated_cols = $arr;

        return $this;
    }
}
