<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.RuleStmt</code>
 */
class RuleStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 1 [json_name = "relation"];</code>
     */
    protected $relation = null;
    /**
     * Generated from protobuf field <code>string rulename = 2 [json_name = "rulename"];</code>
     */
    protected $rulename = '';
    /**
     * Generated from protobuf field <code>.pg_query.Node where_clause = 3 [json_name = "whereClause"];</code>
     */
    protected $where_clause = null;
    /**
     * Generated from protobuf field <code>.pg_query.CmdType event = 4 [json_name = "event"];</code>
     */
    protected $event = 0;
    /**
     * Generated from protobuf field <code>bool instead = 5 [json_name = "instead"];</code>
     */
    protected $instead = false;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node actions = 6 [json_name = "actions"];</code>
     */
    private $actions;
    /**
     * Generated from protobuf field <code>bool replace = 7 [json_name = "replace"];</code>
     */
    protected $replace = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\RangeVar $relation
     *     @type string $rulename
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $where_clause
     *     @type int $event
     *     @type bool $instead
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $actions
     *     @type bool $replace
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 1 [json_name = "relation"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\RangeVar|null
     */
    public function getRelation()
    {
        return $this->relation;
    }

    public function hasRelation()
    {
        return isset($this->relation);
    }

    public function clearRelation()
    {
        unset($this->relation);
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 1 [json_name = "relation"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\RangeVar $var
     * @return $this
     */
    public function setRelation(\Flow\PostgreSql\Protobuf\AST\RangeVar|null $var)
    {
        $this->relation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rulename = 2 [json_name = "rulename"];</code>
     * @return string
     */
    public function getRulename()
    {
        return $this->rulename;
    }

    /**
     * Generated from protobuf field <code>string rulename = 2 [json_name = "rulename"];</code>
     * @param string $var
     * @return $this
     */
    public function setRulename(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->rulename = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node where_clause = 3 [json_name = "whereClause"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getWhereClause()
    {
        return $this->where_clause;
    }

    public function hasWhereClause()
    {
        return isset($this->where_clause);
    }

    public function clearWhereClause()
    {
        unset($this->where_clause);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node where_clause = 3 [json_name = "whereClause"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setWhereClause(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->where_clause = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.CmdType event = 4 [json_name = "event"];</code>
     * @return int one of the values in {@see \Flow\PostgreSql\Protobuf\AST\CmdType}
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>.pg_query.CmdType event = 4 [json_name = "event"];</code>
     * @param int $var one of the values in {@see \Flow\PostgreSql\Protobuf\AST\CmdType}
     * @return $this
     */
    public function setEvent(int $var)
    {
        GPBUtil::checkEnum($var, \Flow\PostgreSql\Protobuf\AST\CmdType::class);
        $this->event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool instead = 5 [json_name = "instead"];</code>
     * @return bool
     */
    public function getInstead()
    {
        return $this->instead;
    }

    /**
     * Generated from protobuf field <code>bool instead = 5 [json_name = "instead"];</code>
     * @param bool $var
     * @return $this
     */
    public function setInstead(bool $var)
    {
        $this->instead = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node actions = 6 [json_name = "actions"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getActions()
    {
        return $this->actions;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node actions = 6 [json_name = "actions"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setActions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->actions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool replace = 7 [json_name = "replace"];</code>
     * @return bool
     */
    public function getReplace()
    {
        return $this->replace;
    }

    /**
     * Generated from protobuf field <code>bool replace = 7 [json_name = "replace"];</code>
     * @param bool $var
     * @return $this
     */
    public function setReplace(bool $var)
    {
        $this->replace = $var;

        return $this;
    }

}

