<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.RuleStmt</code>.
 */
class RuleStmt extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.CmdType event = 4 [json_name = "event"];</code>.
     */
    protected $event = 0;

    /**
     * Generated from protobuf field <code>bool instead = 5 [json_name = "instead"];</code>.
     */
    protected $instead = false;

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 1 [json_name = "relation"];</code>.
     */
    protected $relation;

    /**
     * Generated from protobuf field <code>bool replace = 7 [json_name = "replace"];</code>.
     */
    protected $replace = false;

    /**
     * Generated from protobuf field <code>string rulename = 2 [json_name = "rulename"];</code>.
     */
    protected $rulename = '';

    /**
     * Generated from protobuf field <code>.pg_query.Node where_clause = 3 [json_name = "whereClause"];</code>.
     */
    protected $where_clause;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node actions = 6 [json_name = "actions"];</code>.
     */
    private $actions;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var RangeVar $relation
     * @var string $rulename
     * @var Node $where_clause
     * @var int $event
     * @var bool $instead
     * @var array<Node> $actions
     * @var bool $replace
     *           }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearRelation() : void
    {
        $this->relation = null;
    }

    public function clearWhereClause() : void
    {
        $this->where_clause = null;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node actions = 6 [json_name = "actions"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getActions()
    {
        return $this->actions;
    }

    /**
     * Generated from protobuf field <code>.pg_query.CmdType event = 4 [json_name = "event"];</code>.
     *
     * @return int
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>bool instead = 5 [json_name = "instead"];</code>.
     *
     * @return bool
     */
    public function getInstead()
    {
        return $this->instead;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 1 [json_name = "relation"];</code>.
     *
     * @return null|RangeVar
     */
    public function getRelation()
    {
        return $this->relation;
    }

    /**
     * Generated from protobuf field <code>bool replace = 7 [json_name = "replace"];</code>.
     *
     * @return bool
     */
    public function getReplace()
    {
        return $this->replace;
    }

    /**
     * Generated from protobuf field <code>string rulename = 2 [json_name = "rulename"];</code>.
     *
     * @return string
     */
    public function getRulename()
    {
        return $this->rulename;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node where_clause = 3 [json_name = "whereClause"];</code>.
     *
     * @return null|Node
     */
    public function getWhereClause()
    {
        return $this->where_clause;
    }

    public function hasRelation()
    {
        return isset($this->relation);
    }

    public function hasWhereClause()
    {
        return isset($this->where_clause);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node actions = 6 [json_name = "actions"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setActions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->actions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.CmdType event = 4 [json_name = "event"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkEnum($var, CmdType::class);
        $this->event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool instead = 5 [json_name = "instead"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setInstead($var)
    {
        GPBUtil::checkBool($var);
        $this->instead = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar relation = 1 [json_name = "relation"];</code>.
     *
     * @param RangeVar $var
     *
     * @return $this
     */
    public function setRelation($var)
    {
        GPBUtil::checkMessage($var, RangeVar::class);
        $this->relation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool replace = 7 [json_name = "replace"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setReplace($var)
    {
        GPBUtil::checkBool($var);
        $this->replace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rulename = 2 [json_name = "rulename"];</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setRulename($var)
    {
        GPBUtil::checkString($var, true);
        $this->rulename = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node where_clause = 3 [json_name = "whereClause"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setWhereClause($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->where_clause = $var;

        return $this;
    }
}
