<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.ScalarArrayOpExpr</code>
 */
class ScalarArrayOpExpr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
     */
    protected $xpr = null;
    /**
     * Generated from protobuf field <code>uint32 opno = 2 [json_name = "opno"];</code>
     */
    protected $opno = 0;
    /**
     * Generated from protobuf field <code>bool use_or = 3 [json_name = "useOr"];</code>
     */
    protected $use_or = false;
    /**
     * Generated from protobuf field <code>uint32 inputcollid = 4 [json_name = "inputcollid"];</code>
     */
    protected $inputcollid = 0;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 5 [json_name = "args"];</code>
     */
    private $args;
    /**
     * Generated from protobuf field <code>int32 location = 6 [json_name = "location"];</code>
     */
    protected $location = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\Node $xpr
     *     @type int $opno
     *     @type bool $use_or
     *     @type int $inputcollid
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $args
     *     @type int $location
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
     * @return \Flow\PostgreSql\Protobuf\AST\Node|null
     */
    public function getXpr()
    {
        return $this->xpr;
    }

    public function hasXpr()
    {
        return isset($this->xpr);
    }

    public function clearXpr()
    {
        unset($this->xpr);
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node $var
     * @return $this
     */
    public function setXpr(\Flow\PostgreSql\Protobuf\AST\Node|null $var)
    {
        $this->xpr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 opno = 2 [json_name = "opno"];</code>
     * @return int
     */
    public function getOpno()
    {
        return $this->opno;
    }

    /**
     * Generated from protobuf field <code>uint32 opno = 2 [json_name = "opno"];</code>
     * @param int $var
     * @return $this
     */
    public function setOpno(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->opno = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_or = 3 [json_name = "useOr"];</code>
     * @return bool
     */
    public function getUseOr()
    {
        return $this->use_or;
    }

    /**
     * Generated from protobuf field <code>bool use_or = 3 [json_name = "useOr"];</code>
     * @param bool $var
     * @return $this
     */
    public function setUseOr(bool $var)
    {
        $this->use_or = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 inputcollid = 4 [json_name = "inputcollid"];</code>
     * @return int
     */
    public function getInputcollid()
    {
        return $this->inputcollid;
    }

    /**
     * Generated from protobuf field <code>uint32 inputcollid = 4 [json_name = "inputcollid"];</code>
     * @param int $var
     * @return $this
     */
    public function setInputcollid(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->inputcollid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 5 [json_name = "args"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node args = 5 [json_name = "args"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setArgs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->args = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 location = 6 [json_name = "location"];</code>
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>int32 location = 6 [json_name = "location"];</code>
     * @param int $var
     * @return $this
     */
    public function setLocation(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

}

