<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;

/**
 * Generated from protobuf message <code>pg_query.ScanToken</code>.
 */
class ScanToken extends Message
{
    /**
     * Generated from protobuf field <code>int32 end = 2;</code>.
     */
    protected $end = 0;

    /**
     * Generated from protobuf field <code>.pg_query.KeywordKind keyword_kind = 5;</code>.
     */
    protected $keyword_kind = 0;

    /**
     * Generated from protobuf field <code>int32 start = 1;</code>.
     */
    protected $start = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Token token = 4;</code>.
     */
    protected $token = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $start
     * @var int $end
     * @var int $token
     * @var int $keyword_kind
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 end = 2;</code>.
     *
     * @return int
     */
    public function getEnd()
    {
        return $this->end;
    }

    /**
     * Generated from protobuf field <code>.pg_query.KeywordKind keyword_kind = 5;</code>.
     *
     * @return int
     */
    public function getKeywordKind()
    {
        return $this->keyword_kind;
    }

    /**
     * Generated from protobuf field <code>int32 start = 1;</code>.
     *
     * @return int
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Token token = 4;</code>.
     *
     * @return int
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>int32 end = 2;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setEnd($var)
    {
        GPBUtil::checkInt32($var);
        $this->end = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.KeywordKind keyword_kind = 5;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setKeywordKind($var)
    {
        GPBUtil::checkEnum($var, KeywordKind::class);
        $this->keyword_kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 start = 1;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkInt32($var);
        $this->start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Token token = 4;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkEnum($var, Token::class);
        $this->token = $var;

        return $this;
    }
}
