<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBType, GPBUtil, Message};
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.ScanResult</code>.
 */
class ScanResult extends Message
{
    /**
     * Generated from protobuf field <code>int32 version = 1;</code>.
     */
    protected $version = 0;

    /**
     * Generated from protobuf field <code>repeated .pg_query.ScanToken tokens = 2;</code>.
     */
    private $tokens;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $version
     * @var array<ScanToken> $tokens
     *                       }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.ScanToken tokens = 2;</code>.
     *
     * @return RepeatedField<ScanToken>
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>.
     *
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.ScanToken tokens = 2;</code>.
     *
     * @param array<ScanToken> $var
     *
     * @return $this
     */
    public function setTokens($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, ScanToken::class);
        $this->tokens = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }
}
