<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

/**
 * Protobuf type <code>pg_query.SetOperation</code>.
 */
class SetOperation
{
    /**
     * Generated from protobuf enum <code>SET_OPERATION_UNDEFINED = 0;</code>.
     */
    public const SET_OPERATION_UNDEFINED = 0;

    /**
     * Generated from protobuf enum <code>SETOP_EXCEPT = 4;</code>.
     */
    public const SETOP_EXCEPT = 4;

    /**
     * Generated from protobuf enum <code>SETOP_INTERSECT = 3;</code>.
     */
    public const SETOP_INTERSECT = 3;

    /**
     * Generated from protobuf enum <code>SETOP_NONE = 1;</code>.
     */
    public const SETOP_NONE = 1;

    /**
     * Generated from protobuf enum <code>SETOP_UNION = 2;</code>.
     */
    public const SETOP_UNION = 2;

    private static $valueToName = [
        self::SET_OPERATION_UNDEFINED => 'SET_OPERATION_UNDEFINED',
        self::SETOP_NONE => 'SETOP_NONE',
        self::SETOP_UNION => 'SETOP_UNION',
        self::SETOP_INTERSECT => 'SETOP_INTERSECT',
        self::SETOP_EXCEPT => 'SETOP_EXCEPT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value,
            ));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string) $name);

        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name,
            ));
        }

        return constant($const);
    }
}
