<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\{GPBUtil, Message};

/**
 * Generated from protobuf message <code>pg_query.SQLValueFunction</code>.
 */
class SQLValueFunction extends Message
{
    /**
     * Generated from protobuf field <code>int32 location = 5 [json_name = "location"];</code>.
     */
    protected $location = 0;

    /**
     * Generated from protobuf field <code>.pg_query.SQLValueFunctionOp op = 2 [json_name = "op"];</code>.
     */
    protected $op = 0;

    /**
     * Generated from protobuf field <code>uint32 type = 3 [json_name = "type"];</code>.
     */
    protected $type = 0;

    /**
     * Generated from protobuf field <code>int32 typmod = 4 [json_name = "typmod"];</code>.
     */
    protected $typmod = 0;

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     */
    protected $xpr;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var Node $xpr
     * @var int $op
     * @var int $type
     * @var int $typmod
     * @var int $location
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearXpr() : void
    {
        $this->xpr = null;
    }

    /**
     * Generated from protobuf field <code>int32 location = 5 [json_name = "location"];</code>.
     *
     * @return int
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>.pg_query.SQLValueFunctionOp op = 2 [json_name = "op"];</code>.
     *
     * @return int
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * Generated from protobuf field <code>uint32 type = 3 [json_name = "type"];</code>.
     *
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 typmod = 4 [json_name = "typmod"];</code>.
     *
     * @return int
     */
    public function getTypmod()
    {
        return $this->typmod;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @return null|Node
     */
    public function getXpr()
    {
        return $this->xpr;
    }

    public function hasXpr()
    {
        return isset($this->xpr);
    }

    /**
     * Generated from protobuf field <code>int32 location = 5 [json_name = "location"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkInt32($var);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.SQLValueFunctionOp op = 2 [json_name = "op"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkEnum($var, SQLValueFunctionOp::class);
        $this->op = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 type = 3 [json_name = "type"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkUint32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 typmod = 4 [json_name = "typmod"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setTypmod($var)
    {
        GPBUtil::checkInt32($var);
        $this->typmod = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node xpr = 1 [json_name = "xpr"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setXpr($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->xpr = $var;

        return $this;
    }
}
