<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use UnexpectedValueException;

/**
 * Protobuf type <code>pg_query.SubLinkType</code>
 */
class SubLinkType
{
    /**
     * Generated from protobuf enum <code>SUB_LINK_TYPE_UNDEFINED = 0;</code>
     */
    const SUB_LINK_TYPE_UNDEFINED = 0;
    /**
     * Generated from protobuf enum <code>EXISTS_SUBLINK = 1;</code>
     */
    const EXISTS_SUBLINK = 1;
    /**
     * Generated from protobuf enum <code>ALL_SUBLINK = 2;</code>
     */
    const ALL_SUBLINK = 2;
    /**
     * Generated from protobuf enum <code>ANY_SUBLINK = 3;</code>
     */
    const ANY_SUBLINK = 3;
    /**
     * Generated from protobuf enum <code>ROWCOMPARE_SUBLINK = 4;</code>
     */
    const ROWCOMPARE_SUBLINK = 4;
    /**
     * Generated from protobuf enum <code>EXPR_SUBLINK = 5;</code>
     */
    const EXPR_SUBLINK = 5;
    /**
     * Generated from protobuf enum <code>MULTIEXPR_SUBLINK = 6;</code>
     */
    const MULTIEXPR_SUBLINK = 6;
    /**
     * Generated from protobuf enum <code>ARRAY_SUBLINK = 7;</code>
     */
    const ARRAY_SUBLINK = 7;
    /**
     * Generated from protobuf enum <code>CTE_SUBLINK = 8;</code>
     */
    const CTE_SUBLINK = 8;

    private static $valueToName = [
        self::SUB_LINK_TYPE_UNDEFINED => 'SUB_LINK_TYPE_UNDEFINED',
        self::EXISTS_SUBLINK => 'EXISTS_SUBLINK',
        self::ALL_SUBLINK => 'ALL_SUBLINK',
        self::ANY_SUBLINK => 'ANY_SUBLINK',
        self::ROWCOMPARE_SUBLINK => 'ROWCOMPARE_SUBLINK',
        self::EXPR_SUBLINK => 'EXPR_SUBLINK',
        self::MULTIEXPR_SUBLINK => 'MULTIEXPR_SUBLINK',
        self::ARRAY_SUBLINK => 'ARRAY_SUBLINK',
        self::CTE_SUBLINK => 'CTE_SUBLINK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

