<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

/**
 * Protobuf type <code>pg_query.TableFuncType</code>.
 */
class TableFuncType
{
    /**
     * Generated from protobuf enum <code>TABLE_FUNC_TYPE_UNDEFINED = 0;</code>.
     */
    public const TABLE_FUNC_TYPE_UNDEFINED = 0;

    /**
     * Generated from protobuf enum <code>TFT_JSON_TABLE = 2;</code>.
     */
    public const TFT_JSON_TABLE = 2;

    /**
     * Generated from protobuf enum <code>TFT_XMLTABLE = 1;</code>.
     */
    public const TFT_XMLTABLE = 1;

    private static $valueToName = [
        self::TABLE_FUNC_TYPE_UNDEFINED => 'TABLE_FUNC_TYPE_UNDEFINED',
        self::TFT_XMLTABLE => 'TFT_XMLTABLE',
        self::TFT_JSON_TABLE => 'TFT_JSON_TABLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value,
            ));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string) $name);

        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name,
            ));
        }

        return constant($const);
    }
}
