<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.TruncateStmt</code>.
 */
class TruncateStmt extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.DropBehavior behavior = 3 [json_name = "behavior"];</code>.
     */
    protected $behavior = 0;

    /**
     * Generated from protobuf field <code>bool restart_seqs = 2 [json_name = "restart_seqs"];</code>.
     */
    protected $restart_seqs = false;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node relations = 1 [json_name = "relations"];</code>.
     */
    private $relations;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var array<Node> $relations
     * @var bool $restart_seqs
     * @var int $behavior
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pg_query.DropBehavior behavior = 3 [json_name = "behavior"];</code>.
     *
     * @return int
     */
    public function getBehavior()
    {
        return $this->behavior;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node relations = 1 [json_name = "relations"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getRelations()
    {
        return $this->relations;
    }

    /**
     * Generated from protobuf field <code>bool restart_seqs = 2 [json_name = "restart_seqs"];</code>.
     *
     * @return bool
     */
    public function getRestartSeqs()
    {
        return $this->restart_seqs;
    }

    /**
     * Generated from protobuf field <code>.pg_query.DropBehavior behavior = 3 [json_name = "behavior"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setBehavior($var)
    {
        GPBUtil::checkEnum($var, DropBehavior::class);
        $this->behavior = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node relations = 1 [json_name = "relations"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setRelations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->relations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool restart_seqs = 2 [json_name = "restart_seqs"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setRestartSeqs($var)
    {
        GPBUtil::checkBool($var);
        $this->restart_seqs = $var;

        return $this;
    }
}
