<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.VacuumStmt</code>
 */
class VacuumStmt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     */
    private $options;
    /**
     * Generated from protobuf field <code>repeated .pg_query.Node rels = 2 [json_name = "rels"];</code>
     */
    private $rels;
    /**
     * Generated from protobuf field <code>bool is_vacuumcmd = 3 [json_name = "is_vacuumcmd"];</code>
     */
    protected $is_vacuumcmd = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $options
     *     @type \Flow\PostgreSql\Protobuf\AST\Node[] $rels
     *     @type bool $is_vacuumcmd
     * }
     */
    public function __construct($data = NULL) {
        \Flow\PostgreSql\Protobuf\Metadata\PgQuery::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 1 [json_name = "options"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setOptions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->options = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node rels = 2 [json_name = "rels"];</code>
     * @return RepeatedField<\Flow\PostgreSql\Protobuf\AST\Node>
     */
    public function getRels()
    {
        return $this->rels;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node rels = 2 [json_name = "rels"];</code>
     * @param \Flow\PostgreSql\Protobuf\AST\Node[] $var
     * @return $this
     */
    public function setRels(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\PostgreSql\Protobuf\AST\Node::class);
        $this->rels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_vacuumcmd = 3 [json_name = "is_vacuumcmd"];</code>
     * @return bool
     */
    public function getIsVacuumcmd()
    {
        return $this->is_vacuumcmd;
    }

    /**
     * Generated from protobuf field <code>bool is_vacuumcmd = 3 [json_name = "is_vacuumcmd"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsVacuumcmd(bool $var)
    {
        $this->is_vacuumcmd = $var;

        return $this;
    }

}

