<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use Flow\PostgreSql\Protobuf\Metadata\PgQuery;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pg_query.ViewStmt</code>.
 */
class ViewStmt extends Message
{
    /**
     * Generated from protobuf field <code>.pg_query.Node query = 3 [json_name = "query"];</code>.
     */
    protected $query;

    /**
     * Generated from protobuf field <code>bool replace = 4 [json_name = "replace"];</code>.
     */
    protected $replace = false;

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar view = 1 [json_name = "view"];</code>.
     */
    protected $view;

    /**
     * Generated from protobuf field <code>.pg_query.ViewCheckOption with_check_option = 6 [json_name = "withCheckOption"];</code>.
     */
    protected $with_check_option = 0;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node aliases = 2 [json_name = "aliases"];</code>.
     */
    private $aliases;

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 5 [json_name = "options"];</code>.
     */
    private $options;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var RangeVar $view
     * @var array<Node> $aliases
     * @var Node $query
     * @var bool $replace
     * @var array<Node> $options
     * @var int $with_check_option
     *          }
     */
    public function __construct($data = null)
    {
        PgQuery::initOnce();
        parent::__construct($data);
    }

    public function clearQuery(): void
    {
        $this->query = null;
    }

    public function clearView(): void
    {
        $this->view = null;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node aliases = 2 [json_name = "aliases"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getAliases()
    {
        return $this->aliases;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 5 [json_name = "options"];</code>.
     *
     * @return RepeatedField<Node>
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node query = 3 [json_name = "query"];</code>.
     *
     * @return null|Node
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * Generated from protobuf field <code>bool replace = 4 [json_name = "replace"];</code>.
     *
     * @return bool
     */
    public function getReplace()
    {
        return $this->replace;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar view = 1 [json_name = "view"];</code>.
     *
     * @return null|RangeVar
     */
    public function getView()
    {
        return $this->view;
    }

    /**
     * Generated from protobuf field <code>.pg_query.ViewCheckOption with_check_option = 6 [json_name = "withCheckOption"];</code>.
     *
     * @return int
     */
    public function getWithCheckOption()
    {
        return $this->with_check_option;
    }

    public function hasQuery()
    {
        return isset($this->query);
    }

    public function hasView()
    {
        return isset($this->view);
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node aliases = 2 [json_name = "aliases"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setAliases($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->aliases = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pg_query.Node options = 5 [json_name = "options"];</code>.
     *
     * @param array<Node> $var
     *
     * @return $this
     */
    public function setOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Node::class);
        $this->options = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.Node query = 3 [json_name = "query"];</code>.
     *
     * @param Node $var
     *
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkMessage($var, Node::class);
        $this->query = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool replace = 4 [json_name = "replace"];</code>.
     *
     * @param bool $var
     *
     * @return $this
     */
    public function setReplace($var)
    {
        GPBUtil::checkBool($var);
        $this->replace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.RangeVar view = 1 [json_name = "view"];</code>.
     *
     * @param RangeVar $var
     *
     * @return $this
     */
    public function setView($var)
    {
        GPBUtil::checkMessage($var, RangeVar::class);
        $this->view = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pg_query.ViewCheckOption with_check_option = 6 [json_name = "withCheckOption"];</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setWithCheckOption($var)
    {
        GPBUtil::checkEnum($var, ViewCheckOption::class);
        $this->with_check_option = $var;

        return $this;
    }
}
