<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

use UnexpectedValueException;

/**
 * Protobuf type <code>pg_query.WCOKind</code>
 */
class WCOKind
{
    /**
     * Generated from protobuf enum <code>WCOKIND_UNDEFINED = 0;</code>
     */
    const WCOKIND_UNDEFINED = 0;
    /**
     * Generated from protobuf enum <code>WCO_VIEW_CHECK = 1;</code>
     */
    const WCO_VIEW_CHECK = 1;
    /**
     * Generated from protobuf enum <code>WCO_RLS_INSERT_CHECK = 2;</code>
     */
    const WCO_RLS_INSERT_CHECK = 2;
    /**
     * Generated from protobuf enum <code>WCO_RLS_UPDATE_CHECK = 3;</code>
     */
    const WCO_RLS_UPDATE_CHECK = 3;
    /**
     * Generated from protobuf enum <code>WCO_RLS_CONFLICT_CHECK = 4;</code>
     */
    const WCO_RLS_CONFLICT_CHECK = 4;
    /**
     * Generated from protobuf enum <code>WCO_RLS_MERGE_UPDATE_CHECK = 5;</code>
     */
    const WCO_RLS_MERGE_UPDATE_CHECK = 5;
    /**
     * Generated from protobuf enum <code>WCO_RLS_MERGE_DELETE_CHECK = 6;</code>
     */
    const WCO_RLS_MERGE_DELETE_CHECK = 6;

    private static $valueToName = [
        self::WCOKIND_UNDEFINED => 'WCOKIND_UNDEFINED',
        self::WCO_VIEW_CHECK => 'WCO_VIEW_CHECK',
        self::WCO_RLS_INSERT_CHECK => 'WCO_RLS_INSERT_CHECK',
        self::WCO_RLS_UPDATE_CHECK => 'WCO_RLS_UPDATE_CHECK',
        self::WCO_RLS_CONFLICT_CHECK => 'WCO_RLS_CONFLICT_CHECK',
        self::WCO_RLS_MERGE_UPDATE_CHECK => 'WCO_RLS_MERGE_UPDATE_CHECK',
        self::WCO_RLS_MERGE_DELETE_CHECK => 'WCO_RLS_MERGE_DELETE_CHECK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

