<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pg_query.proto

namespace Flow\PostgreSql\Protobuf\AST;

/**
 * Protobuf type <code>pg_query.XmlExprOp</code>.
 */
class XmlExprOp
{
    /**
     * Generated from protobuf enum <code>IS_DOCUMENT = 8;</code>.
     */
    public const IS_DOCUMENT = 8;

    /**
     * Generated from protobuf enum <code>IS_XMLCONCAT = 1;</code>.
     */
    public const IS_XMLCONCAT = 1;

    /**
     * Generated from protobuf enum <code>IS_XMLELEMENT = 2;</code>.
     */
    public const IS_XMLELEMENT = 2;

    /**
     * Generated from protobuf enum <code>IS_XMLFOREST = 3;</code>.
     */
    public const IS_XMLFOREST = 3;

    /**
     * Generated from protobuf enum <code>IS_XMLPARSE = 4;</code>.
     */
    public const IS_XMLPARSE = 4;

    /**
     * Generated from protobuf enum <code>IS_XMLPI = 5;</code>.
     */
    public const IS_XMLPI = 5;

    /**
     * Generated from protobuf enum <code>IS_XMLROOT = 6;</code>.
     */
    public const IS_XMLROOT = 6;

    /**
     * Generated from protobuf enum <code>IS_XMLSERIALIZE = 7;</code>.
     */
    public const IS_XMLSERIALIZE = 7;

    /**
     * Generated from protobuf enum <code>XML_EXPR_OP_UNDEFINED = 0;</code>.
     */
    public const XML_EXPR_OP_UNDEFINED = 0;

    private static $valueToName = [
        self::XML_EXPR_OP_UNDEFINED => 'XML_EXPR_OP_UNDEFINED',
        self::IS_XMLCONCAT => 'IS_XMLCONCAT',
        self::IS_XMLELEMENT => 'IS_XMLELEMENT',
        self::IS_XMLFOREST => 'IS_XMLFOREST',
        self::IS_XMLPARSE => 'IS_XMLPARSE',
        self::IS_XMLPI => 'IS_XMLPI',
        self::IS_XMLROOT => 'IS_XMLROOT',
        self::IS_XMLSERIALIZE => 'IS_XMLSERIALIZE',
        self::IS_DOCUMENT => 'IS_DOCUMENT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value,
            ));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . strtoupper((string) $name);

        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name,
            ));
        }

        return constant($const);
    }
}
