on:
  workflow_call:

jobs:
  data-frame-core-tests:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "locked"
          - "lowest"
          - "highest"
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Setup PHP Environment"
        uses: "./.github/actions/setup-php-env"
        with:
          php-version: "${{ matrix.php-version }}"
          dependencies: "${{ matrix.dependencies }}"
          coverage: 'pcov'
          extensions: ':psr, bcmath, dom, hash, json, mbstring, xml, xmlwriter, xmlreader, zlib, curl'
          ini-values: 'memory_limit=-1, post_max_size=32M, upload_max_filesize=32M'

      - name: "Test - ETL Core"
        run: "composer test:core"

      - name: "Test - Examples"
        if: ${{ matrix.php-version == '8.2' && matrix.dependencies == 'locked' }}
        run: "composer test:examples"

      - name: "Download artifact"
        if: ${{ github.event_name == 'pull_request' && matrix.php-version == '8.2' && matrix.dependencies == 'locked' }}
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: test-suite.yml
          name: codecov-base-commit-sha-1.x
          search_artifacts: true

      - name: Read artifact content into variable
        if: ${{ github.event_name == 'pull_request' && matrix.php-version == '8.2' && matrix.dependencies == 'locked' }}
        run: |
          ARTIFACT_CONTENT=$(cat codecov-base-commit-sha-1.x.txt)
          echo "codecov_base_commit_sha=$ARTIFACT_CONTENT" >> $GITHUB_ENV

      - name: Upload test results to Codecov.io for baseline
        if: ${{ github.event_name == 'push' && !cancelled() && matrix.php-version == '8.2' && matrix.dependencies == 'locked' }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./var/phpunit/logs

      - name: Upload code coverage data to Codecov.io for baseline
        if: ${{ github.event_name == 'push' && !cancelled() && matrix.php-version == '8.2' && matrix.dependencies == 'locked' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./var/phpunit/coverage/clover

      - name: Upload code coverage data to Codecov.io for pull request
        if: ${{ github.event_name == 'pull_request' && !cancelled() && matrix.php-version == '8.2' && matrix.dependencies == 'locked' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./var/phpunit/coverage/clover
          commit_parent: ${{ env.codecov_base_commit_sha }}

      - name: Upload test results to Codecov.io for pull request
        if: ${{ github.event_name == 'pull_request' && !cancelled() && matrix.php-version == '8.2' && matrix.dependencies == 'locked' }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./var/phpunit/logs
          commit_parent: ${{ env.codecov_base_commit_sha }}

      - name: Get the branch name and SHA
        if: ${{ github.event_name == 'push' && matrix.php-version == '8.2' && matrix.dependencies == 'locked' }}
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          commit_sha=$(git rev-parse HEAD)
          echo "codecov_branch_name=$branch_name" >> $GITHUB_ENV
          echo "codecov_commit_sha=$commit_sha" >> $GITHUB_ENV

      - name: Save commit SHA to file
        if: ${{ github.event_name == 'push' && matrix.php-version == '8.2' && matrix.dependencies == 'locked' }}
        run: echo -n "${{ env.codecov_commit_sha }}" > codecov-base-commit-sha-${{ env.codecov_branch_name }}.txt

      - name: Upload commit SHA as artifact
        if: ${{ github.event_name == 'push' && matrix.php-version == '8.2' && matrix.dependencies == 'locked' }}
        uses: actions/upload-artifact@v4
        with:
          name: codecov-base-commit-sha-${{ env.codecov_branch_name }}
          path: codecov-base-commit-sha-${{ env.codecov_branch_name }}.txt

      - name: "Put SHA to step summary"
        if: ${{ github.event_name == 'push' && matrix.php-version == '8.2' && matrix.dependencies == 'locked' }}
        run: |
          echo "Baseline commit SHA for Codecov: ${{ env.codecov_commit_sha }}" >> $GITHUB_STEP_SUMMARY