on:
  workflow_call:

jobs:
  website-tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"
        with:
          fetch-depth: 0

      - name: "Get Flow Version"
        id: flow_version
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.x-dev

      - name: "Setup PHP Environment"
        uses: "./.github/actions/setup-php-env"
        with:
          php-version: "${{ matrix.php-version }}"
          dependencies: "locked"
          coverage: "pcov"
          working-directory: "web/landing"
          cache-key-suffix: "-website"
          composer-file: "web/landing/composer.lock"

      - name: "Test"
        run: "composer test"
        working-directory: "web/landing"

      - name: "Test Build"
        run: "composer build"
        working-directory: "web/landing"
        env:
          SCHEME: https
          DOMAIN: flow-php.com
          FLOW_VERSION: ${{ steps.flow_version.outputs.tag }}