name: Build Flow-PHP PHAR

on:
  push:
    branches: [ 1.x ]

jobs:
  build-phar:
    name: "Build Flow-PHP PHAR"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: none
          tools: composer:v2
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v3"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "php-${{ matrix.php-version }}-locked-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            php-${{ matrix.php-version }}-locked-composer-

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Build PHAR file"
        run: "composer build:phar"

      - name: "Validate Flow PHAR"
        run: |
          ./build/flow-php.phar --version

      - name: "Prepare artifact name"
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          BUILD_TAG=${GITHUB_SHA:0:7}
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        with:
          name: flow-php-${{ env.BUILD_TAG }}.phar
          path: build/flow-php.phar
