name: Build

on:
  push:
    branches: [ 1.x ]
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  build:
    name: "Build"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: none
          tools: composer:v2
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v3"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "php-${{ matrix.php-version }}-locked-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            php-${{ matrix.php-version }}-locked-composer-

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Build PHAR file"
        run: "composer build:phar"

      - name: "Validate Flow PHAR"
        run: |
          ./build/flow.phar --version
          ./build/flow.phar run examples/topics/transformations/array_expand.php

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/flow-php/flow:latest
          target: flow
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Prepare artifact name"
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          BUILD_TAG=${GITHUB_SHA:0:7}
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        with:
          name: flow-${{ env.BUILD_TAG }}.phar
          path: build/flow.phar
