name: Documentation Linter

on:
  pull_request:
    paths:
      - 'src/**'
      - 'docs/**'
      - 'examples/**'
      - 'README.md'
  push:
    branches:
      - "1.x"
    paths-ignore:
      - 'CHANGELOG.md'

# See https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  documentation-linter:
    name: "Documentation Linter"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "MD Link Linter"
        uses: "docker://norberttech/md-link-linter:latest"
        with:
          entrypoint: "/composer/vendor/bin/mdlinklint"
          args: "--exclude=vendor --exclude=tests ."
