on:
  pull_request:
    paths:
      - 'src/**'
      - 'documentation/**'
      - 'web/landing/**'
      - 'Justfile'
      - 'README.md'
  push:
    branches:
      - "1.x"
    paths-ignore:
      - 'CHANGELOG.md'

# See https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  documentation-linter:
    runs-on: "blacksmith-2vcpu-ubuntu-2404"
    steps:
      - name: "Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Setup PHP Environment"
        uses: "./.github/actions/setup-php-env"
        with:
          php-version: "8.3"
          dependencies: "locked"
          coverage: "none"
          extensions: ':psr, bcmath, curl, dom, hash, json, mbstring, pdo_sqlite, xml, xmlwriter, xmlreader, zip, zlib'
          cache-key-suffix: "-locked"

      - name: "Build Docs"
        run: "just docs"

      - name: Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Uncommitted changes detected, please run \`just docs\` and commit the changes."
            git status
            exit 1
          else
            echo "No uncommitted changes."
          fi

      - name: "MD Link Linter"
        uses: "docker://norberttech/md-link-linter:latest"
        with:
          entrypoint: "/composer/vendor/bin/mdlinklint"
          args: "--exclude=vendor --exclude=tests --exclude=examples --exclude=documentation ."
