on:
  workflow_call:

jobs:
  static-analyze:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.2"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Setup PHP Environment"
        uses: "./.github/actions/setup-php-env"
        with:
          php-version: "${{ matrix.php-version }}"
          dependencies: "${{ matrix.dependencies }}"
          coverage: "none"

      - name: "Create cache directories"
        run: |
          mkdir -p var/cs-fixer
          mkdir -p var/phpstan/cache

      - name: "Cache cs-fixer results"
        uses: "actions/cache@v4"
        with:
          path: "var/cs-fixer"
          key: "php-${{ matrix.php-version }}-cache-cs-fixer-${{ github.run_id }}"
          restore-keys: |
            php-${{ matrix.php-version }}-cache-cs-fixer-

      - name: "Cache phpstan results"
        uses: "actions/cache@v4"
        with:
          path: "var/phpstan/cache"
          key: "php-${{ matrix.php-version }}-cache-phpstan-${{ github.run_id }}"
          restore-keys: |
            php-${{ matrix.php-version }}-cache-phpstan-

      - name: "Monorepo Validate"
        run: "composer test:monorepo"

      - name: "Static Analyze - CS Fixer"
        run: "composer static:analyze:cs-fixer"

      - name: "Static Analyze - PHPStan"
        run: "composer static:analyze:phpstan -- --error-format=github"

      - name: "Static Analyze - Rector"
        run: "composer static:analyze:rector"