on:
  workflow_call:

jobs:
  extension-tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Install dependencies"
        run: |
          sudo apt-get update && sudo apt-get install libbrotli1 liblz4-1 libzstd1 --assume-yes

      - name: "Setup PHP Environment"
        uses: "./.github/actions/setup-php-env"
        with:
          php-version: "${{ matrix.php-version }}"
          dependencies: "${{ matrix.dependencies }}"
          coverage: "pcov"
          extensions: ':psr, bcmath, dom, hash, json, mbstring, xml, xmlwriter, xmlreader, zlib, brotli, lz4, zstd, snappy-https://github.com/kjdev/php-ext-snappy@0.2.1'
          php-env: '{"SNAPPY_CONFIGURE_PREFIX_OPTS": "CXXFLAGS=-std=c++11"}'
          cache-key-suffix: "-extensions"

      - name: "Test Brotli"
        run: "composer test:lib:parquet -- --group brotli-extension"

      - name: "Test LZ4"
        run: "composer test:lib:parquet -- --group lz4-extension"

      - name: "Test ZSTD"
        run: "composer test:lib:parquet -- --group zstd-extension"

      - name: "Test Snappy"
        run: "composer test:lib:parquet -- --group snappy-extension"