on:
  workflow_call:
    inputs:
      dependencies:
        type: string
        required: false
        default: '["locked"]'

jobs:
  libraries-tests:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 15
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mysql:
        image: mysql:8.0.31-debian
        ports:
          - 3306/tcp
        env:
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_DATABASE: mysql
          MYSQL_ROOT_PASSWORD: root
    strategy:
      fail-fast: false
      matrix:
        dependencies: ${{ fromJSON(inputs.dependencies) }}
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Setup PHP Environment"
        uses: "./.github/actions/setup-php-env"
        with:
          php-version: "${{ matrix.php-version }}"
          dependencies: "${{ matrix.dependencies }}"
          coverage: 'pcov'

      - name: "Test - Libraries"
        run: "composer test:libraries"
        env:
          FLOW_PARQUET_TESTS_DEBUG: "0"
          PGSQL_DATABASE_URL: pgsql://postgres:postgres@127.0.0.1:${{ job.services.postgres.ports[5432] }}/postgres?serverVersion=11&charset=utf8
          MYSQL_DATABASE_URL: mysql://mysql:mysql@127.0.0.1:${{ job.services.mysql.ports[3306] }}/mysql

      - name: Upload to Codecov
        uses: ./.github/actions/codecov-report
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          php-version: ${{ matrix.php-version }}
          dependencies: ${{ matrix.dependencies }}