on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build-archives:
    name: "Release"
    runs-on: ${{ matrix.operating-system }}
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        php-version:
          - "8.3"
        operating-system:
          - "blacksmith-2vcpu-ubuntu-2404"

    steps:
      - name: "Checkout"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Setup PHP Environment"
        uses: "./.github/actions/setup-php-env"
        with:
          php-version: "${{ matrix.php-version }}"
          dependencies: "locked"
          coverage: "none"
          extensions: ':psr, bcmath, dom, hash, json, mbstring, xml, xmlwriter, xmlreader, zlib'
          cache-key-suffix: "-locked-phar"
          apt-packages: "build-essential autoconf automake libtool protobuf-compiler libprotobuf-c-dev"
          pie-extensions: "flow-php/pg-query-ext:1.x-dev"

      - name: "Build PHAR file"
        run: "just phar"

      - name: "Validate Flow PHAR"
        run: |
          ./build/flow.phar --version

      - name: "Import GPG Key"
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: "Sign PHAR"
        run: >
          gpg
          --batch
          --yes
          --local-user="${{ secrets.GPG_USER_EMAIL }}"
          --passphrase="${{ secrets.GPG_PASSPHRASE }}"
          --pinentry-mode="loopback"
          --detach-sign
          --output="./build/flow.phar.asc"
          ./build/flow.phar

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@6ff44f8e5255f9d8aa31ef22f7e57a2d926b7da0 # v1.11.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: useblacksmith/build-push-action@fb9e3e6a9299c78462bfadd0d93352c316adc9b8 # v2.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/flow-php/flow:${{ github.ref_name }}
          target: flow

      - name: "Upload binaries to release"
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$GITHUB_REF_NAME" \
            build/flow.phar \
            build/flow.phar.asc \
            --clobber

