name: Test Mutations

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/adapter/**'
      - 'src/core/**'
      - 'src/lib/**'
      - 'tools/**'
      - 'composer.lock'
  push:
    branches: [ 1.x ]
    paths-ignore:
      - 'CHANGELOG.md'

# See https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  mutation-tests:
    name: "Mutation Tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: pcov
          tools: composer:v2
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v3"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: "php-${{ matrix.php-version }}-locked-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            php-${{ matrix.php-version }}-locked-composer-

      - name: "Create cache directory"
        run: "mkdir -p var/infection/cache"

      - name: "Cache infection results"
        uses: "actions/cache@v3"
        with:
          path: "var/infection/cache"
          key: "php-${{ matrix.php-version }}-cache-infection-${{ github.run_id }}"
          restore-keys: |
            php-${{ matrix.php-version }}-cache-infection-

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Mutation Tests"
        run: "composer test:mutation"
