name: Test Suite

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
      - 'src/**'
      - 'benchmarks/**'
      - 'tools/**'
      - 'composer.lock'
      - 'composer.json'
      - 'phpunit.xml.dist'
  push:
    branches: [ 1.x ]
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
      - 'src/**'
      - 'benchmarks/**'
      - 'tools/**'
      - 'composer.lock'
      - 'composer.json'
      - 'phpunit.xml.dist'
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  static-analyze:
    uses: ./.github/workflows/job-static-analyze.yml

  tests:
    uses: ./.github/workflows/job-tests.yml
    with:
      dependencies: ${{ (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && '["locked","lowest","highest"]' || '["locked","lowest"]' }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  phpunit-telemetry-tests:
    uses: ./.github/workflows/job-phpunit-telemetry-tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  extension-tests:
    uses: ./.github/workflows/job-extension-tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  pg-query-extension:
    uses: ./.github/workflows/job-pg-query-extension.yml

  arrow-extension:
    uses: ./.github/workflows/job-arrow-extension.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  flow-php-extension:
    uses: ./.github/workflows/job-flow-php-extension.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  mutation-tests:
    uses: ./.github/workflows/job-mutation-tests.yml
