name: Test Suite

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/adapter/**'
      - 'src/bridge/**'
      - 'src/core/**'
      - 'src/cli/**'
      - 'src/lib/**'
      - 'tools/**'
      - 'examples/**'
      - 'composer.lock'
  push:
    branches: [ 1.x ]
    paths-ignore:
      - 'CHANGELOG.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  windows-tests:
    uses: ./.github/jobs/job-windows-tests.yml

  website-tests:
    uses: ./.github/jobs/job-website-tests.yml

  libraries-tests:
    uses: ./.github/jobs/job-libraries-tests.yml
    secrets: inherit

  mutation-tests:
    uses: ./.github/jobs/job-mutation-tests.yml

  benchmark-tests:
    uses: ./.github/jobs/job-benchmark-tests.yml

  data-frame-core-tests:
    uses: ./.github/jobs/job-data-frame-core-tests.yml
    secrets: inherit

  extension-tests:
    uses: ./.github/jobs/job-extension-tests.yml

  components-tests:
    uses: ./.github/jobs/job-components-tests.yml
    secrets: inherit