<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: opentelemetry/proto/common/v1/common.proto

namespace Opentelemetry\Proto\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ArrayValue is a list of AnyValue messages. We need ArrayValue as a message
 * since oneof in AnyValue does not allow repeated fields.
 *
 * Generated from protobuf message <code>opentelemetry.proto.common.v1.ArrayValue</code>
 */
class ArrayValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Array of values. The array may be empty (contain 0 elements).
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.common.v1.AnyValue values = 1;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opentelemetry\Proto\Common\V1\AnyValue[] $values
     *           Array of values. The array may be empty (contain 0 elements).
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Opentelemetry\Proto\Common\V1\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Array of values. The array may be empty (contain 0 elements).
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.common.v1.AnyValue values = 1;</code>
     * @return RepeatedField<\Opentelemetry\Proto\Common\V1\AnyValue>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Array of values. The array may be empty (contain 0 elements).
     *
     * Generated from protobuf field <code>repeated .opentelemetry.proto.common.v1.AnyValue values = 1;</code>
     * @param \Opentelemetry\Proto\Common\V1\AnyValue[] $var
     * @return $this
     */
    public function setValues(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField(
            $var,
            \Google\Protobuf\Internal\GPBType::MESSAGE,
            \Opentelemetry\Proto\Common\V1\AnyValue::class,
        );
        $this->values = $arr;

        return $this;
    }
}
